src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ORM_Phone__c</fullName>
        <description>This field is created to use in Email template</description>
        <formula>Account_Executive_Name__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ORM Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QLMS_Account_Executive__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>QLMS Account Executive</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>QLMS_AE__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QLMS_AE__c</referenceTo>
        <relationshipLabel>Related Business Partners</relationshipLabel>
        <relationshipName>QLMS_AE</relationshipName>
        <type>Lookup</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>QLMS_Account_Executive__c</fullName>
        <formula>Account.QLMS_Account_Executive__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QLMS Account Executive</label>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/HomePageContent__c.object
<CustomObject>
    <fields>
        <fullName>DetailText__c</fullName>
        <label>DetailText</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked the value is active or not</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <description>Home Page Contents</description>
    <label>HomePageContent</label>
    <nameField>
        <label>Content Header</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HomePageContents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lender__c.object
<CustomObject>
    <fields>
        <fullName>LenderNumber__c</fullName>
        <label>LenderNumber</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Lender</label>
    <nameField>
        <label>Lender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lender</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LenderLink__c.object
<CustomObject><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checking whether the fields value is active or not</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Link_sequence__c</fullName>
        <label>Link sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields><fields>
        <fullName>Visible_if_QLMS_AE_Assigned_to_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This link only be seen when there is an assigned QLMS Account Executive to the partner.</inlineHelpText>
        <label>Visible if QLMS AE Assigned to Partner</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>LenderLink</label><nameField>
        <label>Link Text</label>
        <type>Text</type>
    </nameField><pluralLabel>LenderLink</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/PartnerHomeAfterLoginController.cls
public class PartnerHomeAfterLoginController{
    @AuraEnabled
    public static integer getMessage() {
        integer msg;
        
        String profileID = UserInfo.getProfileId();
        String userProfile = [SELECT Name FROM Profile WHERE Id = : profileID LIMIT 1].Name;
        if(userProfile == Label.Prospective_Partner_User_Label)
        {
            msg= getContactId(Userinfo.getUserId());
        }
        else{
            msg=0;
        }
        
        return msg;
    }
    @AuraEnabled
    public static integer getContactId(String userId) {  
        integer ReturnMsg;
        dateTime SystemDate = System.now();
        date TodayDate=date.newinstance(SystemDate.year(), SystemDate.month(), SystemDate.day());
        List<Contact> ObjConId = new List<Contact>();         
        String contactId_user  = [Select contactId from User where id =: userId].contactId;
        Integer numberDaysDue;
        Id RecortypeId_old = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Individual Leads').getRecordTypeId();
        Id RecortypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Potential Partner Portal User').getRecordTypeId();
        ObjConId  = [Select id from Contact where id = : contactId_user and (RecordTypeId =: RecortypeId or  RecordTypeId =: RecortypeId_old)];
        if(!ObjConId.isempty())
        {
            Datetime FirstLoginDate=[select LoginTime  from LoginHistory where UserId=:userId order by LoginTime asc limit 1 ].LoginTime;
            Date CreatedDate = date.newinstance(FirstLoginDate.year(), FirstLoginDate.month(), FirstLoginDate.day());
            date Expiredate= CreatedDate.addDays(7);
            numberDaysDue = TodayDate.daysBetween(Expiredate);
            
            ReturnMsg = numberDaysDue;
        }
        else{
            ReturnMsg = 0;
        }
        
        return ReturnMsg;
    }
    
    @AuraEnabled
    public static List<HomePageContent__c> getHomeContents( ) {
        List<HomePageContent__c> lenderslink = 
            [SELECT Id, Name, DetailText__c from  HomePageContent__c where IsActive__c = true
             order by LastModifiedDate desc];        
        return lenderslink;
    }    
    @AuraEnabled
    public static List<Lender__c> getLender( ) {
        List<Lender__c> lenders = 
            [SELECT Id, Name, LenderNumber__c from Lender__c 
             order by LastModifiedDate desc];
        return lenders;
    }    
    @AuraEnabled
    public static List<LenderLink__c> getLenderLinks( ) {
        List<LenderLink__c> lenderslink =new  List<LenderLink__c>();
        id UserAccountID=[select AccountID from user where id=: Userinfo.getUserId()].AccountID;
        if(UserAccountID!=null){
            ID QLMSAccountExecutiveID =[select QLMS_Account_Executive__c from Account
                                        where id=:UserAccountID].QLMS_Account_Executive__c;
            if(QLMSAccountExecutiveID!=null){
                lenderslink=getLenderLinksWithAEData();
            }
            else{
                lenderslink = getLenderLinksData();
            }            
        }
        else
        {
            lenderslink = getLenderLinksData();            
        }
        
        return lenderslink;
    }
    public static List<LenderLink__c> getLenderLinksData() {       
        List<LenderLink__c> lenderslink = 
            [SELECT Id, Name, URL__c from  LenderLink__c where IsActive__c = true 
             and Visible_if_QLMS_AE_Assigned_to_Partner__c=false
             order by Link_sequence__c asc];
        return lenderslink;
    }
    public static List<LenderLink__c> getLenderLinksWithAEData() {       
        List<LenderLink__c> lenderslink = 
            [SELECT Id, Name, URL__c from  LenderLink__c where IsActive__c = true   
             order by Link_sequence__c asc];
        return lenderslink;
    }

    @AuraEnabled
    public static String getAEInfo(String phone) {        
      user u =[SELECT contact.Account.ORM_Phone__c FROM user WHERE  id=:userinfo.getUserId()];
      String aePhone;
      String p = u.contact.Account.ORM_Phone__c;
       if(p == null){
           aePhone = '(888) 980-2898';
       }else{
           aePhone = p;
       }      
    return aePhone; 
    }
}