src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Holding_Company_Federal_Tax_ID_Number_EI__c</fullName>
        <label>Federal Tax ID/EIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>App Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>No Longer In Business</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>App Package Accepted by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Accepted by Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Incomplete per Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Incomplete per Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Sent to prospective partner</fullName>
                    <isActive>false</isActive>
                    <label>App Package Sent to prospective partner</label>
                </value>
                <value>
                    <fullName>Application Package Uploaded</fullName>
                    <isActive>false</isActive>
                    <label>Application Package Uploaded</label>
                </value>
                <value>
                    <fullName>Approved but Not Active</fullName>
                    <isActive>false</isActive>
                    <label>Approved but Not Active</label>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <isActive>false</isActive>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Denied by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>Denied by Credit Risk</label>
                </value>
                <value>
                    <fullName>Do not Call</fullName>
                    <isActive>false</isActive>
                    <label>Do not Call</label>
                </value>
                <value>
                    <fullName>Hot</fullName>
                    <isActive>false</isActive>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <isActive>false</isActive>
                    <label>InActive</label>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Not Qualified</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                    <isActive>false</isActive>
                    <label>Warm</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accounttriggerAETest.cls
@isTest
public class accounttriggerAETest {
    
       @isTest static void testocc(){
   
             Profile profile = [select Id,Name from profile where Name = 'Account Executive/PCS'];
          
            //Profile profile = [select Id,Name from profile where Name = 'System Administrator'];
          
            User u = new User(Alias = 'standt1',Country='United Kingdom',Email='demo1@randomdemodomain.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = profile.Id,TimeZoneSidKey='America/Los_Angeles', UserName='dprobertdemo1@camfed.org');
            insert u;
           
           System.runAs(u){
           
                Account account = new Account();
                account.Main_Phone__c = '1231231235';
                account.Email__c = 'deepyork@gmail.com';
                account.Cell__c = '1231231233';
                account.Partner_Lead_Status__c = 'Processing';
                account.Holding_Company_Federal_Tax_ID_Number_EI__c = '123';
                account.Name = 'Test Account';
          
               insert account;   
               
              Account a = [SELECT Id, Name, Partner_Lead_Status__c FROM Account 
                            WHERE Name = 'Test Account'];
               
               a.Partner_Lead_Status__c = 'Processing';
               
               update a;
               System.assertEquals('Processing', a.Partner_Lead_Status__c);
            
           }
       
          
        }    

          
}