src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_PCS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned PCS</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 3) AND 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist Lead</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>App Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>No Longer In Business</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>App Package Accepted by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Accepted by Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Incomplete per Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Incomplete per Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Sent to prospective partner</fullName>
                    <isActive>false</isActive>
                    <label>App Package Sent to prospective partner</label>
                </value>
                <value>
                    <fullName>Application Package Uploaded</fullName>
                    <isActive>false</isActive>
                    <label>Application Package Uploaded</label>
                </value>
                <value>
                    <fullName>Approved but Not Active</fullName>
                    <isActive>false</isActive>
                    <label>Approved but Not Active</label>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <isActive>false</isActive>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Denied by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>Denied by Credit Risk</label>
                </value>
                <value>
                    <fullName>Do not Call</fullName>
                    <isActive>false</isActive>
                    <label>Do not Call</label>
                </value>
                <value>
                    <fullName>Hot</fullName>
                    <isActive>false</isActive>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <isActive>false</isActive>
                    <label>InActive</label>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Not Qualified</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                    <isActive>false</isActive>
                    <label>Warm</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <description>If you choose Other as your Partner Lead source, you must enter a source name here</description>
        <inlineHelpText>If you choose Other as your Partner Lead source, you must enter a source name here</inlineHelpText>
        <label>Other Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Condition__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                    <default>true</default>
                    <label>Outstanding</label>
                </value>
                <value>
                    <fullName>Revision Requested</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Condition</label><nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Condition</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Conditions</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Assigned_PCS__c</fullName>
        <formula>Account.Assigned_PCS__r.FirstName + ' ' + Account.Assigned_PCS__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned PCS</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Contact_NMLS__c</fullName>
        <label>NMLS ID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Individual_Lead_source__c</fullName>
        <label>Individual Lead source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>TradeShow</fullName>
                </value>
                <value>
                    <fullName>QLMS Website</fullName>
                </value>
                <value>
                    <fullName>Internet search</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Purchased list</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Date</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status - Used By Executive Reporting</description>
        <inlineHelpText>Status - Used By Executive Reporting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Full Package Received</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/PipelineConditionPDFControllerTest.cls
@IsTest
public class PipelineConditionPDFControllerTest {
    @IsTest Static void SaveLoanTest(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Account Executive/PCS'];
        UserRole UR=[Select Id from UserRole where Name='Partner Care Specialist'];        
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User user1 = new User(Alias = uniqueName.substring(18, 23),  email = uniqueName + '@test1' + orgId + '.org',
                              Username = uniqueName + '@test1' + orgId + '.org', 
                              EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id,userroleid=UR.ID, 
                              TimeZoneSidKey='America/Los_Angeles');
        insert user1;            
        system.runAs(user1)
        {
            
            Account portalAccount = new Account(
                Name='portalAccount',
                Cell__c='1236547410',
                Assigned_PCS__c=user1.Id,
                Main_Phone__c='5414147852',
                Company_NMLS_ID__c = '12345',
                Partner_Lead_Status__c='New');
            insert portalAccount;
            Contact contact = new Contact(
                LastName='LastName', 
                Title__c='Loan Officer', 
                Cell__c='1234569874', 
                Office_Phone__c='1234569874', 
                Individual_Lead_source__c='Other', 
                Email = 'Sam@gmail.com',
                Contact_NMLS__c = '12345',
                Source_Name__c='Michael',
                AccountId = portalAccount.Id);
            insert contact;        
            List<Client__c> clientList;
            List<Client__c> clientListReturned;
            Loan_New__c loanInsert = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                                     LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),                                            
                                                     Preferred_Contact_Type__c = 'Loan Officer',Related_Individual__c = contact.Id,                                                     
                                                     Related_Partner__c = portalAccount.Id);
            
            insert loanInsert;  
            list<condition__c> ConditionList = new list<condition__c>();
            Condition__c Conditio = new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Outstanding',
                                                     Description__c = 'Alternate Address Clarification' ,Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                     Loan_Id__c = loanInsert.Id);
            Condition__c Conditio1 = new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Cancelled',
                                                      Description__c = 'Alternate Address Clarification' ,Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                      Loan_Id__c = loanInsert.Id);
            Condition__c Conditio2 = new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Cleared',
                                                      Description__c = 'Alternate Address Clarification' ,Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                      Loan_Id__c = loanInsert.Id);
            Condition__c Conditio3= new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Revision Requested',
                                                     Description__c = 'Alternate Address Clarification' ,Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                     Loan_Id__c = loanInsert.Id);
            Condition__c Conditio5 = new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Cleared',
                                                      Description__c = 'Alternate Address Clarification' ,Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                      Loan_Id__c = loanInsert.Id);
            
            ConditionList.add(Conditio);
            ConditionList.add(Conditio1);
            ConditionList.add(Conditio2);
            ConditionList.add(Conditio3);
            ConditionList.add(Conditio5);
            insert ConditionList;
            Condition__c Conditio6 = new Condition__c(Condition_Number__c= '1', Comment__c ='Funded',Status__c='Outstanding',
                                                      Description__c = 'Alternate Address Clarification',Condition_Created_Date__c=Date.parse('10/11/2019'),Status_Date__c=Date.parse('10/11/2019'),
                                                      Loan_Id__c = loanInsert.Id,id=ConditionList[0].id);
            update Conditio6; 
            
        
            LoanStatus__c LoanStatus = new LoanStatus__c(Name = 'Application Package Received', LoanId__c = loanInsert.Id, 
                                                         PreviousStatus__c = 'Waiting for Full Package');
            Insert LoanStatus;
            PipelineConditionResponse PCR = new PipelineConditionResponse();
           		PCR.Id				= ConditionList[0].Id;
                PCR.ApplicationDate	= '10/11/2017';
                PCR.Status			= ConditionList[0].status__c;
                PCR.PCS_Name		= 'Drush';
                PCR.PhoneNumber		= '1234567890';
                PCR.TodaysDate 		= '01/19/2018';
                PCR.ClientName		= 'JOJO';
            
            
            Test.startTest();
            string num='9630266959';
            
            string Phone = PipelineConditionPDFController.FormatPhone(num);                      
            Test.stopTest();
            try{
                ApexPages.StandardController sc = new ApexPages.StandardController(loanInsert);
                
                ApexPages.currentPage().getParameters().put('id', loanInsert.Id);
                List<ConditionResponsePipeline> lst=PipelineConditionPDFController.getdata(); 
                List<PipelineConditionResponse> lst1=PipelineConditionPDFController.getConditiondetails();
                map<id,list<Condition_Log__c>> GetConditionLogMap=PipelineConditionPDFController.GetConditionLog(loanInsert.Id);
                //System.assertEquals(loanInsert.Id, LoanId);
            }catch(exception ex){}       
            
        }
    }
}