src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Phone_Number__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Account_Executive_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ORM Account Executive Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>DMB - Jesse, DMB - Josh</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>wORMS, Braveheart</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Last_Login_Time__c</fullName>
        <label>Last Login Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>userLoginId__c</fullName>
        <label>userLoginId</label>
        <length>18</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/classes/loginPartner_ctrl.cls
/****Logic to create a task for AE whenever a user logs into Portal*****/

public without sharing class  loginPartner_ctrl {
    
    @AuraEnabled
    public static string create_task(){
               
      LoginHistory tsk = [SELECT Id,UserId,Logintime 
                          FROM LoginHistory 
                          WHERE  UserId=:userinfo.getUserId() 
                          ORDER BY LoginTime 
                          DESC limit 1];       
      
      user u =[SELECT contactId,contact.AccountId 
               FROM user 
               WHERE  id=:userinfo.getUserId()];
      
      Integer TaskCount = [SELECT count() 
                           FROM Task 
                           WHERE  userLoginId__c=:tsk.id]; //this count will limit the task creation
      
       
     Task t = new Task();

          if(TaskCount == 0 ){
               Account a  = new Account();
               try{  
                   a  = [SELECT name,Account_Executive_Name__c,Primary_Contact_Email__c,Primary_Contact_Phone_Number__c 
                         FROM Account 
                         WHERE id=:u.contact.AccountId];  
                }catch(Exception ex){}
                            
            String Partner_Name = a.Name;
            
            t.Subject = userinfo.getfirstname() + ' ' + userinfo.getlastname() +' from '+Partner_Name+' has logged into the portal' ;
            t.Status = 'Open';
            t.Priority = 'Normal';
            t.WhatId = a.id;
            t.userLoginId__c =  tsk.id;
            t.ActivityDate = Date.Today();
            t.OwnerId = a.Account_Executive_Name__c;
            t.WhoId = u.contactId;
            t.Last_login_Time__c = tsk.LoginTime;
            t.Description = userinfo.getfirstname() + ' ' + 'logged into Portal'+ ' ' + 'on' + ' ' + tsk.Logintime.format('MMMM d, yyyy')+ ' ' + 'at'
                            + ' ' + tsk.Logintime.format('hh:mm a')  + ('\n') + 'Primary Contact Email: ' + ' ' +  a.Primary_contact_Email__c + ('\n') + 
                            'Primary Contact Phone:' + ' ' + a.Primary_Contact_Phone_Number__c  ;
            insert t;
               
            }
            return t.id;
     }
}