src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>App Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>No Longer In Business</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>App Package Accepted by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Accepted by Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Incomplete per Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Incomplete per Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Sent to prospective partner</fullName>
                    <isActive>false</isActive>
                    <label>App Package Sent to prospective partner</label>
                </value>
                <value>
                    <fullName>Application Package Uploaded</fullName>
                    <isActive>false</isActive>
                    <label>Application Package Uploaded</label>
                </value>
                <value>
                    <fullName>Approved but Not Active</fullName>
                    <isActive>false</isActive>
                    <label>Approved but Not Active</label>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <isActive>false</isActive>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Denied by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>Denied by Credit Risk</label>
                </value>
                <value>
                    <fullName>Do not Call</fullName>
                    <isActive>false</isActive>
                    <label>Do not Call</label>
                </value>
                <value>
                    <fullName>Hot</fullName>
                    <isActive>false</isActive>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <isActive>false</isActive>
                    <label>InActive</label>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Not Qualified</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                    <isActive>false</isActive>
                    <label>Warm</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <description>If you choose Other as your Partner Lead source, you must enter a source name here</description>
        <inlineHelpText>If you choose Other as your Partner Lead source, you must enter a source name here</inlineHelpText>
        <label>Other Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Contact_NMLS__c</fullName>
        <label>NMLS ID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Individual_Lead_source__c</fullName>
        <label>Individual Lead source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>TradeShow</fullName>
                </value>
                <value>
                    <fullName>QLMS Website</fullName>
                </value>
                <value>
                    <fullName>Internet search</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Purchased list</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/classes/ApexScheduler_UserDeactivationTest.cls
@isTest
public with sharing class ApexScheduler_UserDeactivationTest {

    @isTest
     public static void  testschedule(){
         
         Account portalAccount = new Account(
            Name='portalAccount',
            Cell__c='1236547410',
            Main_Phone__c='5414147852',
            Company_NMLS_ID__c = '1234',
            Partner_Lead_Status__c='New');
        insert portalAccount;
      //   Id RecortypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Individual Leads').getRecordTypeId();
        
          Id RecortypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Potential Partner Portal User').getRecordTypeId();
      
      try{
        Contact contact = new Contact(
            LastName='LastName', 
            Title__c='Processor ', 
            Cell__c='1234569874', 
            Office_Phone__c='1234569874', 
            Individual_Lead_source__c='Other', 
            Email = 'Samasd@gmail.com',
            Contact_NMLS__c = '12345',
            Source_Name__c='Michael',
            AccountId = portalAccount.Id,
          RecordTypeId = RecortypeId);
        insert contact;  
        
        Profile partnerProfile = [SELECT Id FROM Profile WHERE Name='Prospective Partner User' LIMIT 1];        
        User partnerUser = new User();
        partnerUser.Username = 'partner_'+Math.random()+'@test.com';
        partnerUser.FirstName = 'test912';
        partnerUser.LastName = 'user';
        partnerUser.alias = ('test'+Math.random()).subString(0,6);
        partnerUser.Email = 'test'+Math.random()+'@test.com';
        partnerUser.CommunityNickname = String.valueOf(Math.random()).subString(0,6);
        partnerUser.ProfileId = partnerProfile.Id;
        partnerUser.TimeZoneSidKey = 'America/Los_Angeles';
        partnerUser.LocaleSidKey='en_US';
        partnerUser.EmailEncodingKey='UTF-8';
        partnerUser.LanguageLocaleKey='en_US';
        partnerUser.ContactId = contact.Id;
        insert partnerUser;   
        
        }catch(exception ex){}      
         try{
            Test.StartTest();
            string  sh = '0 0 1 23 * ?';
           ApexScheduler_UserDeactivation instScheduler = new ApexScheduler_UserDeactivation();
           system.Schedule('Test check',sh, instScheduler ); 
            Test.stopTest();
         }
         catch(exception ex){}
        
     }
    
}