src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Condition__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Condition_Number__c</fullName>
        <label>Condition Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2 Year Tax Return</fullName>
                </value>
                <value>
                    <fullName>Alternate Address Clarification</fullName>
                </value>
                <value>
                    <fullName>Bank statements</fullName>
                </value>
                <value>
                    <fullName>Client(s) to provide</fullName>
                </value>
                <value>
                    <fullName>Copy of Divorce Decree and/or Settlement Agreement</fullName>
                </value>
                <value>
                    <fullName>Copy of Each Client's Social Security Card</fullName>
                </value>
                <value>
                    <fullName>Credit Report Inquiries Requiring Explanation</fullName>
                </value>
                <value>
                    <fullName>Driver's License for all clients</fullName>
                </value>
                <value>
                    <fullName>Electric Bills (Occupancy Clarification)</fullName>
                </value>
                <value>
                    <fullName>Occupancy Status</fullName>
                </value>
                <value>
                    <fullName>Paystubs-30 days most recent</fullName>
                </value>
                <value>
                    <fullName>Pension Award Letter</fullName>
                </value>
                <value>
                    <fullName>Please provide a copy of your current mortgage statement</fullName>
                </value>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Proof of assets in the amount  needed for funds to close</fullName>
                </value>
                <value>
                    <fullName>Proof of Social Security Income</fullName>
                </value>
                <value>
                    <fullName>Self-Employed 2 years Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Trust Agreement</fullName>
                </value>
                <value>
                    <fullName>Utility Bill (Occupancy Clarification)</fullName>
                </value>
                <value>
                    <fullName>W-2 Form</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Proof of assets in the amount needed for funds to close</fullName>
                    <isActive>false</isActive>
                    <label>Proof of assets in the amount needed for funds to close</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Condition</relationshipLabel>
        <relationshipName>Condition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                    <default>true</default>
                    <label>Outstanding</label>
                </value>
                <value>
                    <fullName>Revision Requested</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Condition</label><nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Condition</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Conditions</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Condition_Log__c.object
<CustomObject><fields>
        <fullName>ConditionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition ID</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Conditions History</relationshipLabel>
        <relationshipName>Conditions_History</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Loan_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipName>ConditionLogs</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Old_Comments__c</fullName>
        <label>Old Comments</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Condition History</label><nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>ConditionLog Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Conditions History</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Requested Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <description>Format: Last Name, First Name</description>
        <inlineHelpText>Format: Last Name, First Name</inlineHelpText>
        <label>Client Name*</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PCS_at_Loan_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PCS at loan level can be different from PCS at Partner level</inlineHelpText>
        <label>PCS at Loan Level</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist Lead</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status - Used By Executive Reporting</description>
        <inlineHelpText>Status - Used By Executive Reporting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Full Package Received</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/PipelineConditionPDFController.cls
public class PipelineConditionPDFController {
    
public static List<ConditionResponsePipeline> getdata() {
        String LoanID=ApexPages.currentPage().getParameters().get('id');
    
    	if(LoanID == null || LoanID == '')
        {
            LoanID= '12354';
             //LoanID= 'a0Q29000002d4seEAA';
        }
        
        List<ConditionResponsePipeline>ObjConFinalListReturn=new List<ConditionResponsePipeline>();
        List<ConditionResponse>ObjConFinalList=new List<ConditionResponse>();
        List<ConditionResponse>ObjConOutstanding=new List<ConditionResponse>();
        List<ConditionResponse>ObjConRevisionRequested=new List<ConditionResponse>();
        List<ConditionResponse>ObjConCancelled =new List<ConditionResponse>();
        List<ConditionResponse>ObjConCleared =new List<ConditionResponse>();
        List<Condition__c> objOutstanding=new List<Condition__c>();
        List<Condition__c> objRevisionRequested=new List<Condition__c>();
        List<Condition__c> objCancelled =new List<Condition__c>();
        List<Condition__c> objCleared =new List<Condition__c>();
        try
        {
            objOutstanding=[Select Id,Condition_Number__c,Comment__c,Status__c,CreatedDate,LastModifiedDate,Description__c from Condition__c where Loan_Id__c=:LoanId and Status__c='Outstanding' ORDER BY LastModifiedDate desc];
            for(Condition__c ObjConc:objOutstanding)
            {
                ConditionResponse objres=new ConditionResponse();
                objres.Index=ObjConc.Condition_Number__c;
                objres.DescText=ObjConc.Comment__c;
                objres.DropDownValue=ObjConc.Description__c;
                objres.Status=ObjConc.Status__c;
                datetime dt=ObjConc.CreatedDate;    
                objres.CreatedDate=dt.date().format();
                datetime dtstatus=ObjConc.LastModifiedDate;  
                objres.StatusDate=dtstatus.date().format();
                objres.Id=ObjConc.Id;
                ObjConOutstanding.add(objres);
            }
            objRevisionRequested=[Select Id,Condition_Number__c,Comment__c,Status__c,CreatedDate,LastModifiedDate,Description__c from Condition__c where Loan_Id__c=:LoanId and Status__c='Revision Requested' ORDER BY LastModifiedDate desc];
            for(Condition__c ObjConc:objRevisionRequested)
            {
                ConditionResponse objres=new ConditionResponse();
                objres.Index=ObjConc.Condition_Number__c;
                objres.DescText=ObjConc.Comment__c;
                objres.DropDownValue=ObjConc.Description__c;
                objres.Status=ObjConc.Status__c;
                datetime dt=ObjConc.CreatedDate;    
                objres.CreatedDate=dt.date().format();
                datetime dtstatus=ObjConc.LastModifiedDate;  
                objres.StatusDate=dtstatus.date().format();
                objres.Id=ObjConc.Id;
                ObjConRevisionRequested.add(objres);
            }
            objCancelled=[Select Id,Condition_Number__c,Comment__c,Status__c,CreatedDate,LastModifiedDate,Description__c from Condition__c where Loan_Id__c=:LoanId and Status__c='Cancelled' ORDER BY LastModifiedDate desc];
            for(Condition__c ObjConc:objCancelled)
            {
                ConditionResponse objres=new ConditionResponse();
                objres.Index=ObjConc.Condition_Number__c;
                objres.DescText=ObjConc.Comment__c;
                objres.DropDownValue=ObjConc.Description__c;
                objres.Status=ObjConc.Status__c;
                datetime dt=ObjConc.CreatedDate;    
                objres.CreatedDate=dt.date().format();
                datetime dtstatus=ObjConc.LastModifiedDate;  
                objres.StatusDate=dtstatus.date().format();
                objres.Id=ObjConc.Id;
                ObjConCancelled.add(objres);
            }
            objCleared=[Select Id,Condition_Number__c,Comment__c,Status__c,CreatedDate,LastModifiedDate,Description__c from Condition__c where Loan_Id__c=:LoanId and Status__c='Cleared' ORDER BY LastModifiedDate desc];
            for(Condition__c ObjConc:objCleared)
            {
                ConditionResponse objres=new ConditionResponse();                
                objres.Index=ObjConc.Condition_Number__c;
                objres.DescText=ObjConc.Comment__c;
                objres.DropDownValue=ObjConc.Description__c;
                objres.Status=ObjConc.Status__c;
                datetime dt=ObjConc.CreatedDate;    
                objres.CreatedDate=dt.date().format();
                datetime dtstatus=ObjConc.LastModifiedDate;  
                objres.StatusDate=dtstatus.date().format();
                objres.Id=ObjConc.Id;
                ObjConCleared.add(objres);
            }
            ObjConFinalList.addAll(ObjConOutstanding);
            ObjConFinalList.addAll(ObjConRevisionRequested);
            ObjConFinalList.addAll(ObjConCancelled);
            ObjConFinalList.addAll(ObjConCleared);
            system.debug(ObjConFinalList.size());
            map<id,list<Condition_Log__c>> MapConditionLogList=new  map<id,list<Condition_Log__c>>();
            MapConditionLogList=GetConditionLog(loanID);
            for(ConditionResponse obj :ObjConFinalList){
                list<string> des=new   list<string> ();       
                
                ConditionResponsePipeline objres=new ConditionResponsePipeline();
                objres.Index=obj.Index;            
                list<Condition_log__c> cl=new list<Condition_log__c>();
                cl=MapConditionLogList.get(obj.id);
                if(cl==null)
                {                   
                    des.add(obj.DescText);
                    objres.DescText=des;
                }
                else
                {
                    des.add(obj.DescText);
                    for( Condition_log__c  logdata:cl)
                    {
                        string a=logdata.Old_Comments__c;
                        des.add(a);                        
                    }                    
                    objres.DescText=des;                    
                }
                objres.DropDownValue=obj.DropDownValue;
                objres.Status=obj.Status;                
                objres.CreatedDate=obj.CreatedDate;                
                objres.StatusDate=obj.StatusDate;
                objres.Id=obj.Id;
                ObjConFinalListReturn.add(objres);
            }
        }
        catch(exception e){
            system.debug('getLoanConditionPipeline--Exception---'+e);
        }
        system.debug(ObjConFinalListReturn);
      return ObjConFinalListReturn;
         
    }
     
    public static map<id,list<Condition_Log__c>> GetConditionLog(string loanID)
    {
        map<id,list<Condition_Log__c>> conLogMap= new map<id,list<Condition_Log__c>>();
        list<Condition_Log__c> ConditionList =new list<Condition_Log__c> ();
        ConditionList= [select Old_Comments__c,ConditionId__c from Condition_Log__c where Loan_Id__c=: loanID  ORDER BY LastModifiedDate desc];
        for(Condition_Log__c conObj:ConditionList)
        {
            List<Condition_Log__c> l = conLogMap.get(conObj.ConditionId__c);
            if (l == null) {
                l = new List<Condition_Log__c>();
                conLogMap.put(conObj.ConditionId__c, l);
            }
            l.add(conObj);   
        }
        return conLogMap;        
    }
    
    public static List<PipelineConditionResponse> getConditiondetails() {
        //string LoanID= 'a0Q29000002d4seEAA';
        String LoanID=ApexPages.currentPage().getParameters().get('id');
        string OwnerId;
        
        List<PipelineConditionResponse>ObjConFinalList=new List<PipelineConditionResponse>();
        Loan_New__c ObjLoan=new Loan_New__c();
        User user = new User();
        
        try
        {
            ObjLoan=[SELECT Client_Name__c, Name,LoanNumber__c,Application_Date__c,Id,LoanStatus__c,PCS_at_Loan_Level__c,PCS_at_Partner_Level__c,Related_Partner__r.Assigned_PCS__c
                     FROM Loan_New__c where Id=:LoanID];
            
            if (ObjLoan.PCS_at_Loan_Level__c != null) {
                OwnerId = ObjLoan.PCS_at_Loan_Level__c;
            } else {
                OwnerId = ObjLoan.Related_Partner__r.Assigned_PCS__c;
            }
            
            user = [SELECT Name,Phone FROM User where Id=:OwnerId];
            
            PipelineConditionResponse objres=new PipelineConditionResponse();
            if(ObjLoan.LoanNumber__c=='' ||ObjLoan.LoanNumber__c==null)
            {
                objres.Id = ObjLoan.Name;
                 objres.LoanNumberorId = 'Loan Id:';
                
            }
            else
            {
                objres.Id = ObjLoan.LoanNumber__c;
                 objres.LoanNumberorId = 'Loan Number:';
            }
            
            objres.ClientName = ObjLoan.Client_Name__c;
            datetime dtstatus=ObjLoan.Application_Date__c;  
            objres.ApplicationDate=dtstatus.date().format();
            objres.Status = ObjLoan.LoanStatus__c;
            objres.PCS_Name = user.Name;
            objres.PhoneNumber = FormatPhone(user.Phone);
            datetime TodaysDate = system.now();
            objres.TodaysDate = TodaysDate.format('MM/dd/yyyy', 'America/New_York');
            ObjConFinalList.add(objres);
            System.debug(ObjConFinalList);
        }
        catch(exception e){
            system.debug('getLoanConditionPipeline--Exception---'+e);
        }
        return ObjConFinalList;
    }
    
    public static String FormatPhone(String Phone) {
        try{
            string nondigits = '[^0-9]';
            string PhoneDigits;
            
            // remove all non numeric
            PhoneDigits = Phone.replaceAll(nondigits,'');
            
            // 10 digit: reformat with dashes
            if (PhoneDigits.length() == 10) 
                return '('+PhoneDigits.substring(0,3) + ') ' +
                PhoneDigits.substring(3,6) + '-' +
                PhoneDigits.substring(6,10);
        }
        catch(exception e)
        {
            system.debug('FormatPhone--Exception---'+ e);
        }
        return(Phone);
    }
}