src/objects/Account.object
<CustomObject>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>IsLoanCreatedByLoanProcessor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanCreatedByLoanProcessor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Processor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Portal Loan Processors</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Portal Loan Processor</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>ORM Partner</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>ORM Partners</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Processor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Loan Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/LoanSharingHandlerTest.cls
/**
 * @description Apex Tests for LoanSharingHandler
 * @author Mike Gill
 * @date 28th June 2018
 *
 * @todo implement test constants
 *
 */
@isTest(SeeAllData=false)
private class LoanSharingHandlerTest {

    private static String queryString = TestUtils.getAllFieldQueryString('Loan_New__c');

    @testSetup static void testSetupData(){


        Id profileId = TestUtils.getProfileId('System Administrator');
        Id userRoleId = TestUtils.getRoleId('System Administrator');


        User testUser = (User)TestFactory.createSObject(new User(   ProfileId = profileId,
                                                                    UserRoleId = userRoleId), 'TestFactory.UserDefaults');
        insert testUser;


        System.runAs(testUser){

            Map<String, Id> recTypeMap = TestUtils.getRecordTypes('Account');

            Account testAccount = (Account)TestFactory.createSObject(new Account (
                                                                    OwnerId = testUser.Id,
                                                                    RecordTypeId = recTypeMap.get('Partners')),
                                                                    'TestFactory.AccountDefaults');
            insert testAccount;

            Contact testContact = (Contact)TestFactory.createSObject(new Contact (
                                                                AccountId = testAccount.Id,
                                                                OwnerId = testUser.Id),
                                                                'TestFactory.ContactDefaults');

            insert testContact;
            System.assertEquals(testAccount.OwnerId, testUser.Id, 'Owner is not Test User');
            User testPortalUser = TestUtils.createPortalLoanProcessorUser(testContact.Id);
            insert testPortalUser;

            Loan_New__c testLoan = (Loan_New__c)TestFactory.createSObject(new Loan_New__c(
                    LoanCompleteFlag__c = false,
                    Originating_Loan_Officer__c = testPortalUser.Id,
                    Related_Individual__c = testContact.Id,
                    Related_Partner__c = testAccount.Id
            ), 'TestFactory.LoanDefaults');

            insert testLoan;



        }

    }

    @isTest static void testLoanInsert(){

        // Query Test Data from Test Setup
        List<User> partnerUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test Partner%' ];
        List<User> ormUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test ORM%' ];
        List<Account> partnerAcct = [SELECT Id, Name FROM Account];
        List<Contact> partnerContact = [SELECT Id, Name FROM Contact];
        List<Loan_New__c> loans = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        // Validate Test Data is loaded into Test Method
        System.assertEquals(ormUsers.size(), 1);
        System.assertEquals(partnerUsers.size(), 1);
        System.assertEquals(partnerContact.size(), 1);
        System.assertEquals(partnerAcct.size(), 1);


        Loan_New__c testLoan = (Loan_New__c)TestFactory.createSObject(new Loan_New__c(
                LoanCompleteFlag__c = false,
                Originating_Loan_Officer__c = partnerUsers[0].Id,
                Related_Individual__c = partnerContact[0].Id,
                Related_Partner__c = partnerAcct[0].Id
        ), 'TestFactory.LoanDefaults');


        Test.startTest();

            insert testLoan;

        Test.stopTest();

        List<Loan_New__c> queryInsertedLoan = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        System.debug('loanStatus='+queryInsertedLoan[0].LoanStatus__c);




    }

    @isTest static void testLoanUpdate(){

        // Query Test Data from Test Setup
        List<User> partnerUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test Partner%' ];
        List<User> ormUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test ORM%' ];
        List<Account> partnerAcct = [SELECT Id, Name FROM Account];
        List<Contact> partnerContact = [SELECT Id, Name FROM Contact];
        List<Loan_New__c> loans = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        // Validate Test Data is loaded into Test Method
        System.assertEquals(ormUsers.size(), 1);
        System.assertEquals(partnerUsers.size(), 1);
        System.assertEquals(partnerContact.size(), 1);
        System.assertEquals(partnerAcct.size(), 1);


        Loan_New__c testLoan = (Loan_New__c)TestFactory.createSObject(new Loan_New__c(
                LoanCompleteFlag__c = false,
                Originating_Loan_Officer__c = partnerUsers[0].Id,
                Related_Individual__c = partnerContact[0].Id,
                Related_Partner__c = partnerAcct[0].Id
        ), 'TestFactory.LoanDefaults');


        insert testLoan;

        Test.startTest();

        Loan_New__c l = new Loan_New__c (Id = testLoan.Id, LoanStatus__c = 'Proposal', LoanCompleteFlag__c = true, IsLoanCreatedByLoanProcessor__c = true);
        update l;

        Test.stopTest();

        List<Loan_New__c> queryInsertedLoan = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        System.debug('loanStatus='+queryInsertedLoan[0].LoanStatus__c);
        System.debug('LoanCompleteFlag__c='+queryInsertedLoan[0].LoanCompleteFlag__c);




    }

    @isTest static void testLoanUpdateChangeOfOwnerAndStatus(){

        // Query Test Data from Test Setup
        List<User> partnerUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test Partner%' ];
        List<User> ormUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test ORM%' ];
        List<Account> partnerAcct = [SELECT Id, Name FROM Account];
        List<Contact> partnerContact = [SELECT Id, Name FROM Contact];
        List<Loan_New__c> loans = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        // Validate Test Data is loaded into Test Method
        System.assertEquals(ormUsers.size(), 1);
        System.assertEquals(partnerUsers.size(), 1);
        System.assertEquals(partnerContact.size(), 1);
        System.assertEquals(partnerAcct.size(), 1);


        Loan_New__c testLoan = (Loan_New__c)TestFactory.createSObject(new Loan_New__c(
                LoanCompleteFlag__c = false,
                Originating_Loan_Officer__c = partnerUsers[0].Id,
                Related_Individual__c = partnerContact[0].Id,
                Related_Partner__c = partnerAcct[0].Id,
                OwnerId = partnerUsers[0].Id
        ), 'TestFactory.LoanDefaults');


        insert testLoan;

        Loan_New__c l = new Loan_New__c (Id = testLoan.Id, LoanStatus__c = 'Proposal', LoanCompleteFlag__c = true, IsLoanCreatedByLoanProcessor__c = true);
        update l;

        Test.startTest();

        Loan_New__c testLoanUpdate = new Loan_New__c (Id = testLoan.Id,
                                                                LoanStatus__c = 'Incomplete',
                                                                LoanCompleteFlag__c = false,
                                                                IsLoanCreatedByLoanProcessor__c = true);

        update testLoanUpdate;


        Test.stopTest();



        List<Loan_New__c> queryInsertedLoan = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        System.debug('loanStatus='+queryInsertedLoan[0].LoanStatus__c);
        System.debug('LoanCompleteFlag__c='+queryInsertedLoan[0].LoanCompleteFlag__c);




    }
    @isTest static void testLoanUpdateLoanProcessorIsNotNull(){

        // Query Test Data from Test Setup
        List<User> partnerUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test Partner%' ];
        List<User> ormUsers = [SELECT Id, UserName, ContactId FROM User where LastName like 'Test ORM%' ];
        List<Account> partnerAcct = [SELECT Id, Name FROM Account];
        List<Contact> partnerContact = [SELECT Id, Name FROM Contact];
        List<Loan_New__c> loans = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        // Validate Test Data is loaded into Test Method
        System.assertEquals(ormUsers.size(), 1);
        System.assertEquals(partnerUsers.size(), 1);
        System.assertEquals(partnerContact.size(), 1);
        System.assertEquals(partnerAcct.size(), 1);


        Loan_New__c testLoan = (Loan_New__c)TestFactory.createSObject(new Loan_New__c(
                LoanCompleteFlag__c = false,
                Originating_Loan_Officer__c = partnerUsers[0].Id,
                Related_Individual__c = partnerContact[0].Id,
                Related_Partner__c = partnerAcct[0].Id,
                OwnerId = partnerUsers[0].Id
        ), 'TestFactory.LoanDefaults');


        insert testLoan;

        Loan_New__c l = new Loan_New__c (Id = testLoan.Id, LoanStatus__c = 'Proposal', LoanCompleteFlag__c = true,
                IsLoanCreatedByLoanProcessor__c = true, Loan_Processor__c = partnerUsers[0].Id);


        Test.startTest();

        update l;


        Test.stopTest();

        List<Loan_New__c> queryInsertedLoan = Database.query('SELECT ' + queryString + ' FROM Loan_New__c');

        System.debug('loanStatus='+queryInsertedLoan[0].LoanStatus__c);
        System.debug('LoanCompleteFlag__c='+queryInsertedLoan[0].LoanCompleteFlag__c);




    }

}