src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Premier_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check the checkbox of this Partner a Premier partner</description>
        <inlineHelpText>Check the checkbox of this Partner a Premier partner</inlineHelpText>
        <label>Premier Partner</label>
        <type>Checkbox</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fixed_Price_Tier1__mdt.object
<CustomObject>
    <fields>
        <fullName>Credit_to_Borrower__c</fullName>
        <label>Credit to Borrower</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Origination_to_ORM__c</fullName>
        <label>Origination to ORM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><label>Fixed Price Tier1</label><pluralLabel>Fixed Price Tier1</pluralLabel><visibility>Public</visibility>
</CustomObject>

src/objects/Proprietary_Tier_1__mdt.object
<CustomObject><fields>
        <fullName>Credit_to_Borrower__c</fullName>
        <label>Credit to Borrower</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Origination_to_Partner__c</fullName>
        <label>Origination to Partner</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><label>Proprietary Tier 1</label><pluralLabel>Proprietary Tier 1</pluralLabel><visibility>Public</visibility></CustomObject>

src/objects/Proprietary_Tier_2__mdt.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Credit_to_Borrower__c</fullName>
        <label>LPC</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Origination_to_Partner__c</fullName>
        <label>Orig to ORM</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Broker Comp</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Servicing_Fee__c</fullName>
        <label>Servicing Fee</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
<label>Proprietary Tier 2</label><pluralLabel>Proprietary Tier 2</pluralLabel><visibility>Public</visibility>
</CustomObject>

src/objects/Tier1__mdt.object
<CustomObject><fields>
        <fullName>Margin__c</fullName>
        <inlineHelpText>Enter Margin Value</inlineHelpText>
        <label>Margin</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>X0_to_10__c</fullName>
        <label>0-10%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X10_to_20__c</fullName>
        <label>10.01-20%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X20_to_30__c</fullName>
        <label>20.01-30%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X30_to_40__c</fullName>
        <label>30.01-40%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X40_to_50__c</fullName>
        <label>40.01-50%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X50_to_60__c</fullName>
        <label>50.01-60%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X60_to_70__c</fullName>
        <label>60.01-70%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X70_to_80__c</fullName>
        <label>70.01-80%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X80_to_90__c</fullName>
        <label>80.01-90%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>X90_to_100__c</fullName>
        <label>90.01-100%</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields><description>show the Tier 1 pricing table if the Premier Partner checkbox on the Partner is NOT checked.</description><label>Tier 1</label><pluralLabel>Tier 1</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/get_metadata.cls
/**
 * @description: fetch Pricing metadata and refer to these values in Lightning component  
 * @author: Ravi
 * @date: 1/17/2018
 *
 * changelog:
 * 07/17/2018: Sahitya - added method for fetching Helo metadata tables
 */
public class get_metadata{
    public static map<string,map<String,String>> get_tierData(String fetchFrom){
        //craete a map which store map<margin,map<percentage,LOC>>()  data
        map<string,map<String,String>> metataDataFields = new map<string,map<String,String>>();
        IF(fetchFrom==NULL || fetchFrom==''){
            fetchFrom = 'Tier1__mdt';
        }
        list<string> metadatfields = 'X0_to_10__c,X10_to_20__c,X20_to_30__c,X30_to_40__c,X40_to_50__c,X50_to_60__c,X60_to_70__c,X70_to_80__c,X80_to_90__c,X90_to_100__c'.split(',');
        String metadataQuery = 'SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Margin__c, X0_to_10__c, X10_to_20__c, X20_to_30__c, X30_to_40__c, X40_to_50__c, X50_to_60__c, X60_to_70__c, X70_to_80__c, X80_to_90__c, X90_to_100__c FROM '+fetchFrom;
        list<sObject>metadataResults = database.query(metadataQuery);
        System.debug(metadataResults);
        for(sObject eachsObject:metadataResults){
            map<String,String> percentage_and_Loc = new map<String,String>(); 
            for(Integer i=0;i<metadatfields.size();i++){
                percentage_and_Loc.put(String.valueOf((i+1)*10),String.valueOf(eachsObject.get(metadatfields[i])));
            }
            metataDataFields.put(String.valueOf(eachsObject.get('Margin__c')),percentage_and_Loc);
        }
        return metataDataFields;
    }
    
    public static map<string,map<String,String>> get_tierData_fixed(String fetchFrom){
        //craete a map which store map<margin,map<percentage,LOC>>()  data
        map<string,map<String,String>> metataDataFields = new map<string,map<String,String>>();
        IF(fetchFrom==NULL || fetchFrom==''){
            fetchFrom = 'Fixed_Price_Tier1__mdt';
        }
        list<string> metadatfields = 'Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Credit_to_Borrower__c, Origination_to_ORM__c, Price__c, Rate__c'.split(',');
        String metadataQuery = 'SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Credit_to_Borrower__c, Origination_to_ORM__c, Price__c, Rate__c FROM '+fetchFrom;
        list<sObject>metadataResults = database.query(metadataQuery);
        System.debug(metadataResults);
        map<String,String> percentage_and_Loc = new map<String,String>(); 
        map<String,String> percentage_and_LocNew = new map<String,String>(); 
        
        for(sObject eachsObject:metadataResults){
            percentage_and_Loc.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Price__c')));
        }
        metataDataFields.put('fixed',percentage_and_Loc);
        for(sObject eachsObject:metadataResults){
            percentage_and_LocNew.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Origination_to_ORM__c')));
        }
        metataDataFields.put('fixed_orm',percentage_and_LocNew);
        return metataDataFields;
    }
    
    //Fetch Helo Tier data
    public static map<string,map<String,String>> get_tierData_Helo(String fetchFrom){
        system.debug('fetchFrom '+fetchFrom);
        
        boolean isAccPremier = [select id,Contact.AccountId,Contact.Account.Premier_Partner__c from user where id=:userinfo.getUserId()].Contact.Account.Premier_Partner__c;        
        
        map<string,map<String,String>> metataDataFields = new map<string,map<String,String>>();
        IF((fetchFrom==NULL || fetchFrom=='') && isAccPremier == false){
            fetchFrom = 'Proprietary_Tier_1__mdt';
        }
        ELSE IF((fetchFrom==NULL || fetchFrom=='') && isAccPremier == true){
            fetchFrom = 'Proprietary_Tier_2__mdt';
        }
        fetchFrom = fetchFrom.replace(',','');
         system.debug('fetchFrom '+fetchFrom);
       
        list<string> metadatfields = 'Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Credit_to_Borrower__c, Origination_to_Partner__c, Price__c, Rate__c, Servicing_Fee__c'.split(',');
        String metadataQuery = 'SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Credit_to_Borrower__c, Origination_to_Partner__c, Price__c, Rate__c, Servicing_Fee__c FROM '+fetchFrom;
        list<sObject>metadataResults = database.query(metadataQuery);
        System.debug('>>>metadataResults '+metadataResults);
        map<String,String> heloPrice = new map<String,String>(); 
        map<String,String> heloRate = new map<String,String>(); 
        map<String,String> heloOrigination = new map<String,String>(); 
        map<String,String> rateToServiceFee = new map<String,String>(); 
        
        for(sObject eachsObject:metadataResults){
            heloPrice.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Price__c')));
        }
        metataDataFields.put('Helo',heloPrice);
        
        for(sObject eachsObject:metadataResults){ 
            heloRate.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Rate__c')));        
        }
        metataDataFields.put('Helo_rate',heloRate);
        
        for(sObject eachsObject:metadataResults){
            heloOrigination.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Origination_to_Partner__c')));
        }
        metataDataFields.put('Helo_orm',heloOrigination);
        
        for(sObject eachsObject:metadataResults){
            rateToServiceFee.put(String.valueOf(eachsObject.get('Rate__c')),String.valueOf(eachsObject.get('Servicing_Fee__c')));
        }
        system.debug('>>>rateToServiceFee '+rateToServiceFee);
        metataDataFields.put('Helo_service',rateToServiceFee);
        
        return metataDataFields;
    }
}