src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>BarChartResponse__c</fullName>
        <label>BarChartResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>CashFlow10__c</fullName>
        <label>CashFlow10</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>CashFlow1__c</fullName>
        <label>CashFlow1</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>CashFlow5__c</fullName>
        <label>CashFlow5</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Cash_Flow_12_months_Amount__c</fullName>
        <label>Cash Flow 12 Months Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Cash_Flow_60_months_Amount__c</fullName>
        <label>Cash Flow 60 Months Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Cash_Flow_Remaining_months_Amount__c</fullName>
        <label>Cash Flow Remaining Months Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Cash_at_close__c</fullName>
        <label>Cash at close</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Cash_to_close__c</fullName>
        <label>Cash to close</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Current_Mortgage_Balance__c</fullName>
        <label>Current Mortgage Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields><fields>
        <fullName>EOF__c</fullName>
        <label>EOF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Estimated_home_value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Home_Value_10_years__c</fullName>
        <label>Home Value 10 Years</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Initial_Growth_Rate__c</fullName>
        <label>Initial Growth Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Line_of_Credit__c</fullName>
        <label>Line of Credit</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>MIP__c</fullName>
        <label>MIP</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Monthly_Mortgage_Payment__c</fullName>
        <label>Monthly Mortgage Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>PieChartResponse__c</fullName>
        <label>PieChartResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Principal_Limit__c</fullName>
        <label>Principal Limit</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adjust</fullName>
                    <label>ARM</label>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Scenario_Type__c</fullName>
        <label>Scenario Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FHA Traditional HECM</fullName>
                </value>
                <value>
                    <fullName>HECM for Purchase</fullName>
                </value>
                <value>
                    <fullName>Hecm</fullName>
                    <isActive>false</isActive>
                    <label>Hecm</label>
                </value>
                <value>
                    <fullName>Purchase</fullName>
                    <isActive>false</isActive>
                    <label>Purchase</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/PdfSavedScenarioController.cls
/**
 * @description: used for printing scenario results
 * @author: Prsn
 * @date: 2/24/2018
 *
 * changelog:
 * 08/07/2018: Don - Modified Funds to Close - SFDC-241
 * 08/22/2018: Sahitya - Updated results for Helo SFDC - 269
 */
public without sharing class PdfSavedScenarioController {
    
    public String scenarioID {get;set;}
    public user u {get;set;}
    public contact con{get;set;}
    public Scenario__c scenario {get;set;}
    public Integer age{get;set;}
    public Decimal finalEOF{get;set;}
    public Decimal cashAtClose{get;set;}
    public Decimal fundsNeedToClose{get;set;}
    public Decimal equityReserves{get;set;}
    public Decimal financingFees{get;set;}
    public Decimal firstAmount{get;set;}
    public boolean isTraditional {get;set;}
    public string RateTypeis {get;set;}    
    public boolean isOld{get;set;}
    //SFDC -229
    public Decimal estclosingcost{get;set;} 
    public Decimal heloEquity{get;set;} 
    public Decimal mmp{get;set;}
    
    public PdfSavedScenarioController() {
    RateTypeis  = 'Margin';
        isTraditional  = true;
        isOld = false;
        scenarioID =ApexPages.currentPage().getParameters().get('id');
        
        u = [select id,contactid, contact.Account.Name,Contact.Phone,contact.Account.Company_NMLS_ID__c,email from user where id=:UserInfo.getUserId()];
        
        List<Contact> contactList = [select Account.Name, Account.Company_NMLS_ID__c, Account.Logo__c, Account.Main_Phone__c from contact where id =: u.contactid];
        if(contactList.size() > 0 && contactList != Null) {
            con = contactList[0];
        }
  List<Scenario__c> scenarioList = [Select Id,Estimated_home_value__c,
                                          MIP__c,
                                          PieChartResponse__c,
                                          Initial_Growth_Rate__c,
                                          Date_of_birth__c,
                                          BarChartResponse__c, 
                                          Current_Mortgage_Balance__c,
                                          Home_Value_10_years__c,
                                          Monthly_Mortgage_Payment__c,
                                          Margin__c,
                                          Principal_Limit__c,
                                          Index__c,
                                          Line_of_Credit__c,
                                          Cash_Flow_Remaining_months_Amount__c,
                                          Cash_Flow_12_months_Amount__c,
                                          Cash_Flow_60_months_Amount__c,
                                          Cash_at_close__c,
                                          Cash_to_close__c, //SFDC-241
                                          CashFlow1__c,
                                          CashFlow10__c,
                                          CashFlow5__c,
                                          Scenario_Type__c,
                                          RateType__c,
                                          EOF__c,
                                          Other_Estimated_Closing_Costs__c //SFDC -269
                                          From Scenario__c Where Id =: scenarioID];
        
        if(scenarioList != Null && scenarioList.size()>0) {
   //         try{
            scenario = scenarioList[0];
            estClosingcost = scenario.Other_Estimated_Closing_Costs__c; //SFDC -269
            mmp = scenario.Monthly_Mortgage_Payment__c; //SFDC -269
            
            if(scenario.Estimated_home_value__c<=200000) {
             finalEOF = scenario.Estimated_home_value__c *0.02;
              }
            else { 
            finalEOF = (200000 *0.02) + ((scenario.Estimated_home_value__c-200000)*0.01);
             }  
             
            
            if(finalEOF<2500)       { 
            finalEOF = 2500;
             }
            else if (finalEOF>6000) {     finalEOF = 6000; 
            
            }
            
            if(null != scenario.EOF__c ){    finalEOF =    scenario.EOF__c;
            }
            
            if(scenario.Date_of_birth__c != Null)  
            age                           = System.today().year() - scenario.Date_of_birth__c.year(); 
            if(null != scenario.PieChartResponse__c){
            isOld = true;
            Map<String,Object> jsonMap    = (Map<String,Object>)JSON.deserializeUntyped(scenario.PieChartResponse__c);
            
            cashAtClose                   = (Decimal)jsonMap.get('maxCash');
            fundsNeedToClose              = (Decimal)jsonMap.get('cashToClose');
            }else{
              //SFDC - 269
              if(scenario.Scenario_Type__c=='FHA Traditional HECM'){
                    cashAtClose                   = Decimal.valueOf(scenario.Cash_at_close__c);
                }else{
                    cashAtClose                   = scenario.Principal_Limit__c;
              }//SFDC - 269
              fundsNeedToClose              = Decimal.valueOf(scenario.Cash_to_close__c); //SFDC-241
               //hecm
                if(scenario.Scenario_Type__c=='FHA Traditional HECM'){  isTraditional  = true;
                }else{
                    isTraditional  = false;
                }
                
                if(scenario.RateType__c == 'Adjust'){    RateTypeis ='Margin';
                }else{
                    RateTypeis = 'Rate';
                }
            }
            equityReserves                = scenario.Estimated_home_value__c;
            financingFees                 =  finalEOF + estClosingcost; //SFDC -269
           if(null != scenario.PieChartResponse__c) {
            firstAmount                   = ((scenario.Principal_Limit__c-scenario.Current_Mortgage_Balance__c-scenario.MIP__c-financingFees).setScale(2, RoundingMode.HALF_UP));
            }else{
            firstAmount                   =decimal.valueOf(scenario.Cash_at_close__c);
            }
            
            //start SFDC -269
            heloEquity = scenario.Estimated_home_value__c - financingFees - firstAmount; 
            Decimal calc = equityReserves - (scenario.MIP__c + scenario.Line_of_Credit__c + financingFees + cashAtClose + scenario.Current_Mortgage_Balance__c);

            if(scenario.Scenario_Type__c=='FHA Traditional HECM'){ 
                if(Scenario.RateType__c == 'Helo'){
                    equityReserves = heloEquity;
                }
                else{
                    if(calc < 0 ) { 
                        equityReserves = 0.00; 
                    }else{
                        equityReserves = calc; 
                    } 
                }
            }else{
                equityReserves = 0.00;
            }  //end          
        }
    }
    
}