src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead_status_change_date__c</fullName>
        <label>Lead status change date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>App Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>No Longer In Business</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>App Package Accepted by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Accepted by Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Incomplete per Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Incomplete per Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Sent to prospective partner</fullName>
                    <isActive>false</isActive>
                    <label>App Package Sent to prospective partner</label>
                </value>
                <value>
                    <fullName>Application Package Uploaded</fullName>
                    <isActive>false</isActive>
                    <label>Application Package Uploaded</label>
                </value>
                <value>
                    <fullName>Approved but Not Active</fullName>
                    <isActive>false</isActive>
                    <label>Approved but Not Active</label>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <isActive>false</isActive>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Denied by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>Denied by Credit Risk</label>
                </value>
                <value>
                    <fullName>Do not Call</fullName>
                    <isActive>false</isActive>
                    <label>Do not Call</label>
                </value>
                <value>
                    <fullName>Hot</fullName>
                    <isActive>false</isActive>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <isActive>false</isActive>
                    <label>InActive</label>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Not Qualified</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                    <isActive>false</isActive>
                    <label>Warm</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Status_Change_Date__c</fullName>
        <label>Loan Status Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Closing_Date__c</fullName>
        <description>The Actual Closing Date.</description>
        <inlineHelpText>The Actual Closing Date.</inlineHelpText>
        <label>Actual Closing Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/partnerStatus.cls
public class partnerStatus{

    public Id accountId{get;set;}     
        
    //Folders Recieved, loans Inprocess
    public Integer getFolder1(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE LoanStatus__c = 'In Processing' AND Loan_Status_Change_Date__c= THIS_WEEK];
        return count;    
    }
    public Integer getFolder2(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE LoanStatus__c = 'In Processing' AND Loan_Status_Change_Date__c= LAST_WEEK];
        return count;    
    }
    public Integer getFolder3(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE LoanStatus__c = 'In Processing' AND Loan_Status_Change_Date__c= THIS_MONTH];
        return count;    
    }
    public Integer getFolder4(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE LoanStatus__c = 'In Processing' AND Loan_Status_Change_Date__c= THIS_YEAR];
        return count;    
    }
    
    
    //Loans Closing
    public Integer getLoan1(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE Closing_Date__c = THIS_WEEK];
        return count;    
    }
        public Integer getLoan2(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE Closing_Date__c = LAST_WEEK];
        return count;    
    }
        public Integer getLoan3(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE Closing_Date__c = THIS_MONTH];
        return count;    
    }
        public Integer getLoan4(){
        Integer count = 0;
        count = [SELECT count() FROM Loan_New__c WHERE Closing_Date__c = THIS_YEAR];
        return count;    
    }
    
    
    
    //Partners Approval request
    public Integer getStatusProcessing() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Processing' AND Lead_status_change_date__c = THIS_WEEK];
        return count;        
    }
    public Integer getStatusProcessing2() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Processing' AND Lead_status_change_date__c = LAST_WEEK];
        return count;        
    }
    public Integer getStatusProcessing3() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Processing' AND Lead_status_change_date__c = THIS_MONTH];
        return count;        
    }
    public Integer getStatusProcessing4() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Processing' AND Lead_status_change_date__c = THIS_YEAR];
        return count;        
    }
    
    
    //Partners Approved
    public Integer getStatusApproved() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Approved' AND Lead_status_change_date__c = THIS_WEEK];
        return (count);        
    }
    public Integer getStatusApproved2() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Approved' AND Lead_status_change_date__c = LAST_WEEK];
        return (count);        
    }
    public Integer getStatusApproved3() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Approved' AND Lead_status_change_date__c = THIS_MONTH];
        return (count);        
    }
     public Integer getStatusApproved4() {        
        Integer count = 0;
        count = [SELECT count() FROM Account WHERE Partner_Lead_Status__c = 'Approved' AND Lead_status_change_date__c = THIS_YEAR];
        return (count);        
    }
    
    
    //Attempted to contact
    public Integer getAllActivities1(){
        Integer taskCount = 0;
        Integer eventCount = 0;
        taskCount = [SELECT count() FROM Task WHERE Subject != Null AND createdDate = THIS_WEEK AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson') ];
        eventCount = [SELECT count() FROM Event WHERE Subject != Null AND createdDate = THIS_WEEK AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson') ];
        system.debug('all activities' +taskCount);    
        return (taskCount + eventCount);
    }   
    public Integer getAllActivities2() {
        
        Integer taskCount = 0;
        Integer eventCount = 0;
        taskCount = [SELECT count() FROM Task WHERE Subject != Null AND CreatedDate = LAST_WEEK AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        eventCount = [SELECT count() FROM Event WHERE Subject != Null AND CreatedDate = LAST_WEEK AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        return (taskCount + eventCount);
    }
    public Integer getAllActivities3() {
        
        Integer taskCount = 0;
        Integer eventCount = 0;
        taskCount = [SELECT count() FROM Task WHERE Subject != Null AND CreatedDate = THIS_MONTH AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        eventCount = [SELECT count() FROM Event WHERE Subject != Null AND CreatedDate = THIS_MONTH AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        return (taskCount + eventCount);
    }
    public Integer getAllActivities4() {
        
        Integer taskCount = 0;
        Integer eventCount = 0;
        taskCount = [SELECT count() FROM Task WHERE Subject != Null AND CreatedDate = THIS_YEAR AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        eventCount = [SELECT count() FROM Event WHERE Subject != Null AND CreatedDate = THIS_YEAR AND (Owner.Name = 'Josh Evink' OR Owner.Name = 'Joe Rizzo' OR Owner.Name = 'Raymond Kangas' OR Owner.Name = 'Jesse Hanson')];
        return (taskCount + eventCount);
    }   
    
    
    
    
    public Integer getScenarios1(){
        Integer count = 0;
        count = [SELECT count() FROM Scenario__c where createdDate = THIS_WEEK];
        return count; 
    }
    public Integer getScenarios2(){
        Integer count = 0;
        count = [SELECT count() FROM Scenario__c where createdDate = LAST_WEEK];
        return count; 
    }
    public Integer getScenarios3(){
        Integer count = 0;
        count = [SELECT count() FROM Scenario__c where createdDate = THIS_MONTH];
        return count; 
    }
    public Integer getScenarios4(){
        Integer count = 0;
        count = [SELECT count() FROM Scenario__c where createdDate = THIS_YEAR];
        return count; 
    }   
    
}