src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/loanOfficer_ctrl.cls
public without sharing  class loanOfficer_ctrl {
    public user u {get;set;}
    public contact con{get;set;}

    public loanOfficer_ctrl (){
     u = [select id,contactid, contact.Account.Name,Contact.Phone,contact.Account.Company_NMLS_ID__c,email from user where id=:userinfo.getuserid() ];
   try{
    con = [select Account.Name ,Account.Company_NMLS_ID__c,Account.Logo__c from contact where id =: u.contactid];
    
    }catch(Exception ex){}
    }
}