src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ClientInfo__c.object
<CustomObject>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scenario Client</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>ClientIName__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ClientIName</label>
        <referenceTo>ClientInfo__c</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinalCompleteFlag__c</fullName>
        <label>FinalCompleteFlag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>OldLoan</label>
    <nameField>
        <displayFormat>Loan_{000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OldLoans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClientID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>ClientInfo__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanOfficerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanOfficerName</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>11</length>
        <type>Text</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LoanMenuControllerTest.cls
@isTest()
public with sharing class LoanMenuControllerTest {
    
    @isTest static void testValue(){}
    /*@isTest static void testValue(){
        //Insert Record for testing the If situation
        
        ClientInfo__c C1=new ClientInfo__c(Name='john');
             
        insert C1;
        
        Loan__c LC1 = new Loan__c(ClientIName__c=C1.Id,FinalCompleteFlag__c='N');
        insert LC1;
        string loanId1=LC1.Id;
      
        //Test that Records are Inserted
          Loan__c Loan1 = LoanMenuController.getValue(loanId1);
     
        System.assertEquals(Loan1.Id,loanId1);
       
    }
     @isTest static void testClientValue(){
        //Insert Record for testing the If situation
        
        ClientInfo__c C1=new ClientInfo__c(Name='john');
             
        insert C1;
            
     
        //Test that Records are Inserted
          ClientInfo__c C2 = LoanMenuController.getclientValue(c1.Id);
     
        System.assertEquals(C2.Id,c1.Id);
       
    }
    
    @isTest static void testScreen(){
          //Insert Record for testing the If situation
        
        ClientInfo__c C1=new ClientInfo__c(Name='john');
             
        insert C1;
        
        Loan__c LC1 = new Loan__c(ClientIName__c=C1.Id,FinalCompleteFlag__c='N');
        insert LC1;
        string loanId1=LC1.Id;
      
        //Test that Records are Inserted
          Loan__c Loan1 = LoanMenuController.setScreen(loanId1);
     
        System.assertEquals(Loan1.Id,LC1.Id);
         
    }
    
    @isTest static void testLoan() {
         ClientInfo__c c1=new ClientInfo__c(Name='clientTest2');
         insert c1;
         Loan__c l1 = new Loan__c(  ClientIName__c=c1.Id,FinalCompleteFlag__c='N');
         insert l1;
            
         String resultID = l1.Id;
        String result = '';
         //Test that Records are Inserted
      
       if (resultID != '') {
              Loan__c loans = LoanMenuController.saveLoan(l1,resultID);
             System.assertEquals(loans.Id,resultID);
        }
        resultID = '';
        if(resultID =='') 
        {
           Loan__c loans = LoanMenuController.saveLoan(l1,'');
           System.assertnotEquals(loans.Id,resultID);
      
        }
       
    }
   

    @isTest static void fetchAccountTest(){
         String searchKey = 'SK';
         
         ClientInfo__c Len1 = new ClientInfo__c(Name = 'Sachin', Last_Name__c  = 'Sharma',State__c = 'Detroit', Zip__c = '123456', Email_Optional__c ='a@b.com',Phone_Number__c = '1234456678',Street_Address__c = 'GZB');
         ClientInfo__c Len2 = new ClientInfo__c(Name = 'SK', Last_Name__c  = 'Sharma',State__c = 'Detroit', Zip__c = '123456', Email_Optional__c ='a@b.com',Phone_Number__c = '1234456678',Street_Address__c = 'GZB');
         list<ClientInfo__c> ClientList = new list<ClientInfo__c>();
         ClientList.add(Len1);
         ClientList.add(Len2);
         insert  ClientList;
        
        //Test that Records are Inserted
        List<ClientInfo__c> Client1 = LoanMenuController.fetchAccount(searchKey);        
        System.assertEquals(Client1.size(),1);
         
        //Delete Records For testing the Else situation
       delete ClientList;
        //searchKey='abc';
        //Test that Records are Deleted
        List<ClientInfo__c> Client2= LoanMenuController.fetchAccount(searchKey);       
        System.assertEquals(Client2.size(),0); 
    }

    @isTest static void testSaveClient(){
        try{
       Id proId;
       Profile p = [SELECT Id FROM Profile limit 1]; 
       proId=p.Id;
       //Account accounts = [select Id, Name from Account limit 1];
       User ojUser = [SELECT Id,Name FROM User where AccountId != null limit 1];
        system.debug(proId);
       system.runas(ojUser)
       {       
        
        ClientInfo__c Len1 = new ClientInfo__c(Name = 'Sachin', Last_Name__c  = 'Sharma',State__c = 'Detroit', Zip__c = '123456', Email_Optional__c ='a@b.com',Phone_Number__c = '1234456678',Street_Address__c = 'GZB');
        insert  Len1;
       
        //Insert Record for testing the If situation
        Loan__c LC1 = new Loan__c(ClientIName__c=Len1.Id);
        insert LC1;
  
       // insert LoanList;
        string loanId = LC1.Id;
        string CID = Len1.Id;
        String loanIdBlank= '';
        system.debug('LC1='+ LC1);
           system.debug('Len1=' + Len1);
           system.debug('loanId=' +loanId);
           system.debug('CID='+CID);
         //Test that Records are Inserted
      		 test.startTest();
             LoanMenuController.SaveClient(LC1,Len1,loanId,CID);   
           	 LoanMenuController.SaveClient(LC1,Len1, loanIdBlank,CID);
            test.stopTest(); 
  
          
     
        User users = [select Id,Name,AccountId,ContactId from User Limit 1];
        Account accounts=[select Id,Name from Account Limit 1];
           Id UserId = users.id;
           Opportunity obj1=new Opportunity();
           obj1.name=Len1.Name+'_'+accounts.Name;
           obj1.AccountId=accounts.Id;
           obj1.LoanOfficerName__c=users.ContactId;
           obj1.StageName='Proposal';
           obj1.Status__c='New';
           obj1.ClientID__c=Len1.id;
           obj1.CloseDate=System.today();
        
           Opportunity obj2=new Opportunity();
           obj2.name=Len1.Name+'_'+accounts.Name;
           obj2.AccountId=accounts.Id;
           obj2.LoanOfficerName__c=users.ContactId;
           obj2.StageName='Proposal';
           obj2.Status__c='New';
           obj2.ClientID__c=Len1.id;
           obj2.CloseDate=System.today();
           
        
             List<Opportunity> oppList= new List<Opportunity>();
        oppList.Add(obj1);
        oppList.Add(obj2);
     
       insert oppList;
         LoanMenuController.SaveClient(LC1,Len1,LC1.Id,Len1.Id);
        system.assertEquals(oppList.size(), 2); 
       
    }
  }
            catch(exception e){}
    }
*/
}