src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <description>If you choose Other as your Partner Lead source, you must enter a source name here</description>
        <inlineHelpText>If you choose Other as your Partner Lead source, you must enter a source name here</inlineHelpText>
        <label>Other Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Non Premier</fullName>
                    <default>true</default>
                    <label>Non Premier</label>
                </value>
                <value>
                    <fullName>Premier Plus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Current State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/ClientInfo__c.object
<CustomObject>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Client State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scenario Client</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Contact_NMLS__c</fullName>
        <label>NMLS ID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
  <sharingModel>ReadWriteTransfer</sharingModel>

</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Received_Date__c</fullName>
        <label>Appraisal Received Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Household_Members__c</fullName>
        <label>Household Members</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Real_Estate_Taxes__c</fullName>
        <label>Monthly Real Estate Taxes</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QLMS_AE__c.object
<CustomObject>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <description>This object is specifically to store the information of the QLMS AEs so that they can be assigned to each Partner in the system</description>
    <label>QLMS AE</label>
    <nameField>
        <label>QLMS AE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QLMS AEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/lookUpControllerTest.cls
@isTest(seeAlldata=true)
public with sharing class lookUpControllerTest {
    @isTest static void getScenarioResponseTest(){
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        string dt = date.today().format();
        decimal hv=1.0;
        decimal mb=2.0;
        decimal mp=3.0;
        string ir='ir';
        string str = lookUpController.getScenarioResponse(dt,hv,mb,mp,ir,'2.0');
        System.debug(str);
        System.assertEquals(str.contains('200'), true);
    }
    
    @isTest static void getScenarioCashFlowResponseTest(){
        //Test that Records are Inserted
        Test.setMock(HttpCalloutMock.class, new MockHttpCashFlowResponseGenerator());        
        // Call method to test. This causes a fake response to be sent from the class that implements HttpCalloutMock.         
        decimal mb=1.0;
        decimal mp=2.0;
        string ir='ir';
        string str = lookUpController.getScenarioCashFlowResponse(mb,mp,ir);
        System.debug(str);
    }  
    
    @isTest static void fetchAccountTest(){
        String searchKey = 'Dh';
        ClientInfo__c Len1 = new ClientInfo__c(Name = 'Dhiresh', Last_Name__c  = 'Khare',Client_State__c = 'Alabama', Zip__c = '123456', Email_Optional__c ='d@k.com',Phone_Number__c = '1234456678',Street_Address__c = 'Noida Sector-62',  DOB__c=date.today());
        ClientInfo__c Len2 = new ClientInfo__c( Name = 'Dh', Last_Name__c  = 'Khare',Client_State__c = 'Alabama', Zip__c = '123456', Email_Optional__c ='d@k.com',Phone_Number__c = '1234456678',Street_Address__c = 'Noida Sector-62',  DOB__c=date.today());
        list<ClientInfo__c> ClientList = new list<ClientInfo__c>();
        ClientList.add(Len1);
        ClientList.add(Len2);
        insert  ClientList;
        
        //Test that Records are Inserted
        List<lead> Client1 = lookUpController.fetchAccount(searchKey);        
        System.assertEquals(0,Client1.size());
    }

    @isTest static void getClientDetailsTest(){        
        
        lead ClientInsert = new lead(FirstName = 'Dhiresh', Last_Name__c  = 'Khare', 
                                    DOB__c=date.today(),lastName='sdfsdf',Company='sdfsdf');
        Insert ClientInsert;
        Id ClientId = ClientInsert.Id;        
        lead ReturnValue = lookUpController.getClientDetails(ClientId); 
    } 
    
    //SFDC - 289
    @isTest
    Public static void SendMailTMPTest()  
    { 
       Profile p = [SELECT Id FROM Profile WHERE Name='ORM Partner'];
        
        Account portalAccount = new Account(
                Name='portalAccount',
                Cell__c='1236547410',                                
                Main_Phone__c='5414147852',
                Company_NMLS_ID__c = '1234',
                Partner_Type__c='Premier');
            insert portalAccount;
            Contact contact = new Contact(
                LastName='LastName777999', 
                Title__c='Processor ', 
                Cell__c='1237779874', 
                Office_Phone__c='1234569874',  
                Email = 'Sam777@gmail.com',
                Contact_NMLS__c = '12345777',
                Source_Name__c='Michael777',
                AccountId = portalAccount.Id);
            insert contact;
        
        User u = new User(Alias = 'standt1',Country='United Kingdom',Email='demo1@randomdemodomain.com',EmailEncodingKey='UTF-8', 
                          LastName='Testing989', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', 
                          UserName='dprobertdemo9891@camfed.org',ContactId = contact.Id );        
        
        
        system.runAs(u){
            List<Client__c> clientList;
            List<Client__c> clientListReturned;   
            Loan_New__c loanInsert = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true, LoanStatus__c ='In Processing',
                                                     LoanNumber__c = '12345',Appraisal_Received_Date__c= Date.parse('10/10/2017'),
                                                     Household_Members__c='2', Real_Estate_Taxes__c = 1200.00,
                                                     Hazard_Insurance__c = 350.00,HOA_PUD_Condo_Fees__c = 400.00,
                                                     Square_Footage__c = '2000', Subject_Property_State__c = 'California',Related_Individual__c = contact.Id,
                                                     Related_Partner__c = contact.AccountId);
            insert loanInsert;
            string LoanId = LoanInsert.Id;
            
            //Create LeadInfo
            
            Lead l1 = new Lead(Phone = '1234567899',PostalCode= '92081',FirstName = 'atest',LastName= 'btest',State = 'California',Street = 'Stewart',DOB__c = date.today(),Email = 'test@pk.com', Company = 'abc' );
            Lead l2 = new Lead(Phone = '1234567899',PostalCode= '92081',FirstName = 'atest',LastName= 'btest',State = 'California',Street = 'Stewart',DOB__c = date.today(),Email = 'test@pk.com', Company = 'abc');
            List<Lead> LeadList = new List<Lead>();
            LeadList.add(l1);
            LeadList.add(l2);
            try{
            insert LeadList;
            }catch(exception ex){
                LeadList = new list<Lead>();
                LeadList = [select id,phone,postalcode,FirstName,LastName,State,street,DOB__c,Email,company from lead limit 2];
            }
            id LeadId0 = LeadList[0].id;
            id LeadId1 = LeadList[1].id;                
                        
            Scenario__c Scenario1 = new Scenario__c(Estimated_home_value__c = 500.00, 
                                                    Current_Mortgage_Balance__c = 200.00, Current_Mortgage_Interest_Rate__c = 300.00, 
                                                    Monthly_Mortgage_Payment__c = 400.00, Client_Lead__c =LeadId0, priority__c = 'LOC And CashFlow',
                                                    partnerid__c=u.id);
            Scenario__c Scenario2 = new Scenario__c(Estimated_home_value__c = 500.00, 
                                                    Current_Mortgage_Balance__c = 200.00, Current_Mortgage_Interest_Rate__c = 300.00, 
                                                    Monthly_Mortgage_Payment__c = 400.00, Client_Lead__c=LeadId1, priority__c = 'LOC And CashFlow');
            list<Scenario__c> ScenarioList = new list<Scenario__c>();
            ScenarioList.add(Scenario1);
            ScenarioList.add(Scenario2);
            insert ScenarioList;
            String priority='LOC And CashFlow';
            ScenarioResponse objScenario = new ScenarioResponse();
            objScenario.modelType ='test';     
            objScenario.modelType ='test';
            objScenario.annualLiborChangeDate ='01/01/2017';
            objScenario.annualMIP =100.00;
            objScenario.lendersMargin =100.00;
            objScenario.growthRateInitial =100.00;
            objScenario.growthRateAverage10yr =100.00;
            objScenario.growthRateAverage20yr =100.00;
            objScenario.apr =100.00;
            objScenario.annualLibor =100.00;            
            System.assertEquals(objScenario.modelType, 'test');            
            DateTime DT=LeadList[0].DOB__c;
            string ClientDOB= '10/10/1945';                
            string Email_Temp =LeadList[0].Email;
            string Phone_Number = LeadList[0].Phone;
            String getUserEmailID ='dkhar@galaxe.com';
            String getUsername ='drush';
            
            Test.startTest(); 
            try{
                lookUpController.SendMailTMP(ScenarioList[0].id); 
                lookUpController.SendMailTMP(ScenarioList[1].id);
                lookUpController.doUpdateCount(); 
                lookUpController.createAETask(ScenarioList[0].id);//SFDC_396
            }catch(exception ex){}
            test.stopTest();        
        }        
    }
    
   @istest static void SaveScenarioTest()
    {
        QLMS_AE__c QLMSAE= new QLMS_AE__c();
        
        QLMSAE.Email__c='abc@glx.com';
        QLMSAE.isActive__c=true;
        QLMSAE.Office_Phone__c='9630266959';
        QLMSAE.Name='Latika';
        insert QLMSAE;
        Account portalAccount = new Account(
            Name='portalAccount',
            Cell__c='1236547410',
            QLMS_Account_Executive__c=QLMSAE.ID,
            // Email__c='test@noemail.com',
            Main_Phone__c='5414147852',
            Partner_Lead_Status__c='New');
        insert portalAccount;
        
        Profile Objprofile = [select Id, Name from profile where Name = 'System Administrator'];
        UserRole ObjUserRole = [SELECT Id, Name, ParentRoleId FROM UserRole limit 1];
        User users = [select Id,Name from user limit 1];
        ClientInfo__c objClient = new ClientInfo__c();
        date mydate = date.today();
        objClient.PartnerID__c = users.Id;
        objClient.DOB__c = mydate; 
        objClient.Last_Name__c = 'Sharma';
        objClient.Zip__c = '45678';
        insert objClient; 
        
        id cid=objClient.id;
        id Cpid = objClient.PartnerID__c;
        
        lead  l = new lead();
        l.FirstName= 'test';
        l.LastName = 'test';
        l.Company = 'test';
        insert l;
        Scenario__c scenario = new Scenario__c();
        Test.startTest();
        
        try{
       id scenerioId1 = lookUpController.SaveScenario(l,date.today().format().replace('/','-'), 10, 10, 14, 20, 1, 13, 
                                                      10, 23, 13, 12, 'High', 12, 14, 7, 10, 12,'abc','xyz',1.0,1.1,'Hecm','Test','123','123','123',123,'Adjust',120,10,new scenario__c());  
        }catch(exception ex){}
        Test.stopTest();    
        lookUpController.getLoggedInProfile();
        
        try{
     //   lookUpController.createLoan([select id from Scenario__c limit 1].id ,10,10);
        }catch(exception ex){}
        
         Blob FileData = Blob.valueOf('');
        Attachment ObjAttachment = new Attachment();
        objAttachment.Name='Dtest';
        objAttachment.Body = FileData;
        objAttachment.ParentId = [select id from Scenario__c limit 1].id;
        objAttachment.contentType = 'Application/PDF';
        //(Id)apexPages.CurrentPage().getParameters().put('id',string.valueOf());
       // insert objAttachment;
        string Base64Data = 'test Base64Data'; 
      //  test.startTest();
      try{
            lookUpController.getFNMData(objAttachment.Body, objAttachment.Name, Base64Data, objAttachment.contentType, date.today().format(),[select id from Scenario__c limit 1].id,10,100 );
        }catch(exception ex){}
        
        try{
        }catch(exception ex){}        
    } 
    
    //SFDC-275
    @istest static void getZipDataTest()
    {
        lookUpController.getZipData('12345');
        lookupcontroller.get_states();
        lookupcontroller.get_statesPur();
        lookupcontroller.get_helostatesRefi();
        lookupcontroller.get_heloStatesPur();
        lookupController.get_metadataValues('Tier1');
        lookupController.FormatPhone('1234567890');
        lookupController.getScenarioMarginsResponse('10/10/1967',1200,1000,1000,'12');
    }
    
    @istest static void getScenariDataTest(){              
       lookupcontroller.getScenariData('10/10/1967','1200','1000','12','Tier1');//SFDC - 289 added Tier1       
    }
       
    @istest static void GetMonthlyAssetIncomeTest(){
        lookUpController.GetMonthlyAssetIncome([select id from Scenario__c limit 1].id,1000);
    }

    @istest static void createLoanTest(){
        Scenario__c s =   [select id,Client_Lead__c from Scenario__c  limit 1];
        s.Client_Lead__c = [select id from lead limit 1].id;
        update s;
        lookUpController.createLoan(s.id ,10,10);
        lookUpController.getPrintCount(10, s.id);//SFDC-566 
        lookUpController.getcapacityCount(10,s.id);    
    }
       
    @istest static void getCashFlowDataTest(){
        lookUpController.getCashFlowData(10,10,10,10,10,[select id from Scenario__c limit 1].id,100);        
        ScenarioResponceUtil.getScenariData('test','test','test');
    }
}