src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_PCS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned PCS</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 3) AND 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist Lead</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Main_Phone__c</fullName>
        <label>Main Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>App Sent</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>No Longer In Business</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>App Package Accepted by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Accepted by Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Incomplete per Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>App Package Incomplete per Credit Risk</label>
                </value>
                <value>
                    <fullName>App Package Sent to prospective partner</fullName>
                    <isActive>false</isActive>
                    <label>App Package Sent to prospective partner</label>
                </value>
                <value>
                    <fullName>Application Package Uploaded</fullName>
                    <isActive>false</isActive>
                    <label>Application Package Uploaded</label>
                </value>
                <value>
                    <fullName>Approved but Not Active</fullName>
                    <isActive>false</isActive>
                    <label>Approved but Not Active</label>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <isActive>false</isActive>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Denied by Credit Risk</fullName>
                    <isActive>false</isActive>
                    <label>Denied by Credit Risk</label>
                </value>
                <value>
                    <fullName>Do not Call</fullName>
                    <isActive>false</isActive>
                    <label>Do not Call</label>
                </value>
                <value>
                    <fullName>Hot</fullName>
                    <isActive>false</isActive>
                    <label>Hot</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                    <isActive>false</isActive>
                    <label>InActive</label>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                    <isActive>false</isActive>
                    <label>Not Qualified</label>
                </value>
                <value>
                    <fullName>Warm</fullName>
                    <isActive>false</isActive>
                    <label>Warm</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QLMS_Account_Executive__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>QLMS Account Executive</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>QLMS_AE__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QLMS_AE__c</referenceTo>
        <relationshipLabel>Related Business Partners</relationshipLabel>
        <relationshipName>QLMS_AE</relationshipName>
        <type>Lookup</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
</CustomObject>

src/objects/Branches__c.object
<CustomObject><fields>
        <fullName>Business_Partners_Acc__c</fullName>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Branches</relationshipLabel>
        <relationshipName>BankBranches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Branch</label><nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Branches</pluralLabel><sharingModel>ControlledByParent</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Current State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/ClientInfo__c.object
<CustomObject>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Client State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartnerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scenario Client</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Assigned_PCS__c</fullName>
        <formula>Account.Assigned_PCS__r.FirstName + ' ' + Account.Assigned_PCS__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned PCS</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Cell__c</fullName>
        <label>Cell</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>QLMS_Account_Executive__c</fullName>
        <formula>Account.QLMS_Account_Executive__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QLMS Account Executive</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Related_Branch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branches__c.Business_Partners_Acc__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branches__c</referenceTo>
        <relationshipLabel>Business Individuals</relationshipLabel>
        <relationshipName>Business_Individuals</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Declaration__c.object
<CustomObject><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Declaration</label><nameField>
        <label>Declaration Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Declarations</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>QLMS_AE__c</fullName>
        <formula>Related_Partner__r.QLMS_Account_Executive__r.Name</formula>
        <label>QLMS AE</label>
        <type>Text</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QLMS_AE__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Please uncheck this checkbox if this AE cannot be tagged to any of the ORMS Partners</inlineHelpText>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <description>This object is specifically to store the information of the QLMS AEs so that they can be assigned to each Partner in the system</description>
    <label>QLMS AE</label>
    <nameField>
        <label>QLMS AE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QLMS AEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>PartnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/TriggerLoanStatusTrackHandlerTest.cls
/** * File Name   : TriggerLoanStatusTrackHandlerTest.apxt
*     Description : Test class
*     Created     : 11/26/2017
*     covers      : TriggerLoanStatusTrackHandler,TriggerLoanStatusTrack
*   * @author     : prsn
* */
@isTest
public class TriggerLoanStatusTrackHandlerTest {
     @isTest
    public static void loanShareTest() {
        
        Test.startTest();
        
        QLMS_AE__c QLMSAE = new QLMS_AE__c();        
        QLMSAE.Email__c='abc@glx.com';
        QLMSAE.isActive__c=true;
        QLMSAE.Office_Phone__c='9630266959';
        QLMSAE.Name='Nausad';
        insert QLMSAE;
        
        Account portalAccount = new Account(
            Name='portalAccount',
            Cell__c='1236547410',
            QLMS_Account_Executive__c=QLMSAE.ID,
            // Assigned_PCS__c= UserInfo.getUserId(),
            Main_Phone__c='5414147852',
            Company_NMLS_ID__c = '1234',
            Partner_Lead_Status__c='New');
        insert portalAccount;
        
        Branches__c branch = new Branches__c();
        branch.Name = 'Test Branch';
        branch.Business_Partners_Acc__c = portalAccount.Id;
        insert branch;

        Contact contact = getContact(portalAccount.Id);
        contact.Related_Branch__c = branch.Id;
        insert contact;
        
        User partnerUser = CreatePartnerUser(Contact.Id);
        
        ClientInfo__c clientInsert1 = new ClientInfo__c(Name = 'Dhiresh', 
                                                       Last_Name__c  = 'Khare',
                                                       Client_State__c = 'Alabama', 
                                                       Zip__c = '123456', 
                                                       Email_Optional__c ='d@k.com',
                                                       Phone_Number__c = '1234456678',
                                                       Street_Address__c = 'Noida Sector-62',
                                                       PartnerID__c = partnerUser.Id,
                                                       DOB__c=date.today());
        insert  clientInsert1;
        
        Scenario__c scenario1 = new Scenario__c(Estimated_home_value__c = 500.00, 
                                                     Current_Mortgage_Balance__c = 200.00, Current_Mortgage_Interest_Rate__c = 300.00, 
                                                     Monthly_Mortgage_Payment__c = 400.00, PartnerID__c = partnerUser.Id, ClientId__c = ClientInsert1.Id, priority__c = 'LOC And CashFlow');
        
        insert scenario1;
        
        Loan_New__c loanInsert1 = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                                 LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),                                            
                                                 Preferred_Contact_Type__c = 'Loan Officer',Related_Individual__c = contact.Id,
                                                 Related_Partner__c = portalAccount.Id);
        
        insert loanInsert1; 
        loanInsert1.LoanNumber__c = '23456';
        update loanInsert1;
        
        Contact contact1 = getContact(portalAccount.Id);
        contact1.Related_Branch__c = branch.Id;
        insert contact1;
        
        Contact executiveContact = getContact(portalAccount.Id);
        executiveContact.Related_Branch__c = branch.Id;
        insert executiveContact;
        
        Contact executiveWithoutBranch = getContact(portalAccount.Id);
        insert executiveWithoutBranch;
        User partnerUserManager;
        
        Contact loanProcessorContact = getContact(portalAccount.Id);
        insert loanProcessorContact;
        User loanProcessorUser;
        
        Test.stopTest();
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            
            partnerUserManager = CreatePartnerUser(contact1.Id); 
            partnerUserManager.UserRoleId = [Select Id From UserRole Where Name = 'portalAccount Partner Manager'].Id;
            Update partnerUserManager;
            
            User partnerUserExecutive = CreatePartnerUser(executiveContact.Id); 
            partnerUserExecutive.UserRoleId = [Select Id From UserRole Where Name = 'portalAccount Partner Executive'].Id;                
            update partnerUserExecutive;
            
            User partnerUserExecutiveWithoutBranch = CreatePartnerUser(executiveWithoutBranch.Id); 
            partnerUserExecutiveWithoutBranch.UserRoleId = [Select Id From UserRole Where Name = 'portalAccount Partner Executive'].Id;                
            update partnerUserExecutiveWithoutBranch;
            
            loanProcessorUser = CreatePartnerUser(loanProcessorContact.Id);
            loanProcessorUser.ProfileId = [Select Id from profile Where Name = 'Portal Loan Processors'].Id;
            update loanProcessorUser;
        }
        
        Loan_New__c loanInsert = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                                 LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),                                            
                                                 Preferred_Contact_Type__c = 'Loan Officer',Related_Individual__c = contact.Id,
                                                 Related_Partner__c = portalAccount.Id);
        
        insert loanInsert; 
        loanInsert.LoanNumber__c = '23456';
        update loanInsert;
        
        Loan_New__c loanManager = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',Loan_Processor__c = loanProcessorUser.Id,
                                                  LoanNumber__c = '12459',Appraisal_Received_Date__c=Date.parse('10/11/2017'),                                            
                                                  Preferred_Contact_Type__c = 'Loan Officer',Related_Individual__c = contact1.Id,
                                                  Related_Partner__c = portalAccount.Id);
        
  //      insert loanManager; 
        
        Client__c client = new Client__c(Name = 'sample client', LoanId__c = loanManager.Id);
        insert client;
        
        Declaration__c declaration = new Declaration__c(Name = 'sample declaration', DeclarationLoan__c = loanManager.Id);
        insert declaration;
        
        loanInsert.LoanNumber__c = '27456';
       // update loanManager;
          
        ClientInfo__c clientInsert = new ClientInfo__c(Name = 'Dhiresh', 
                                                       Last_Name__c  = 'Khare',
                                                       Client_State__c = 'Alabama', 
                                                       Zip__c = '123456', 
                                                       Email_Optional__c ='d@k.com',
                                                       Phone_Number__c = '1234456678',
                                                       Street_Address__c = 'Noida Sector-62',
                                                       PartnerID__c = partnerUser.Id,
                                                       DOB__c=date.today());
     //   insert  clientInsert;
        
        Scenario__c scenario = new Scenario__c(Estimated_home_value__c = 500.00, 
                                                     Current_Mortgage_Balance__c = 200.00, Current_Mortgage_Interest_Rate__c = 300.00, 
                                                     Monthly_Mortgage_Payment__c = 400.00, PartnerID__c = partnerUser.Id, ClientId__c = ClientInsert.Id, priority__c = 'LOC And CashFlow');
        
     //   insert scenario;
        
        Scenario__c scenarioManager = new Scenario__c(Estimated_home_value__c = 500.00, 
                                                     Current_Mortgage_Balance__c = 200.00, Current_Mortgage_Interest_Rate__c = 300.00, 
                                                     Monthly_Mortgage_Payment__c = 400.00, PartnerID__c = partnerUserManager.Id, ClientId__c = ClientInsert.Id, priority__c = 'LOC And CashFlow');
        
      //  insert scenarioManager;
        
        
    }
    
    private Static User createPartnerUser(Id contactId) {
        Profile partnerProfile = [SELECT Id FROM Profile WHERE Name='ORM Partners'];        
        User partnerUser = new User();
        partnerUser.Username = 'partner_'+Math.random()+'@test.com';
        partnerUser.FirstName = 'test';
        partnerUser.LastName = 'user';
        partnerUser.alias = ('test'+Math.random()).subString(0,6);
        partnerUser.Email = 'test'+Math.random()+'@test.com';
        partnerUser.CommunityNickname = String.valueOf(Math.random()).subString(0,6);
        partnerUser.ProfileId = partnerProfile.Id;
        partnerUser.TimeZoneSidKey = 'America/Los_Angeles';
        partnerUser.LocaleSidKey='en_US';
        partnerUser.EmailEncodingKey='UTF-8';
        partnerUser.LanguageLocaleKey='en_US';
        partnerUser.ContactId = contactId;
        insert partnerUser;
        return partnerUser;
    }
    
    private static Contact getContact(Id accountId) {
        String randomText = (''+math.random()).subString(4,8);
        Contact contact = new Contact();
        contact.LastName= 'Schwartz'+randomText; 
        contact.Title__c='Processor';
        contact.Cell__c='123456'+randomText;
        contact.Office_Phone__c='123456'+randomText; 
        contact.Individual_Lead_source__c='Other';
        contact.Email = 'Sam'+randomText+'@gmail.com';
        contact.Contact_NMLS__c = randomText;
        contact.Source_Name__c='Michael'+ randomText;
        contact.AccountId = accountId;
        //insert contact;
        return contact;
    }
}