src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ORMS_Number_of_Scenarios_Run__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ORMS Number of Scenarios Run</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ORMS Scenario Packages Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>ORMS_Number_of_Scenarios_Run__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ORMS Number of Scenarios Run</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Request_Scenario_Package_Count__c</fullName>
        <label>Request Scenario Package Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/updateCountonAccount.cls
public class updateCountonAccount{


    public static void countUpdate(list<Scenario__c > oldRec,list<Scenario__c > newRec){
    
    try{
        user u = [select Contact.AccountId from user where id=:userinfo.getuserid()];
        
        Account acc = [select Request__c,ORMS_Number_of_Scenarios_Run__c from Account where id=:u.Contact.AccountId];
        //acc.
        if(oldRec[0].Request_Scenario_Package_Count__c != newRec[0].Request_Scenario_Package_Count__c){ acc.Request__c= null != acc.Request__c?acc.Request__c+1:1; update acc;
        }
        
        }catch(Exception ex){}
    }
}