src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_PCS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned PCS</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 3) AND 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist Lead</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Executive_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ORM Account Executive Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>DMB - Jesse, DMB - Josh</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>wORMS, Braveheart</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>ClientDetails</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Assigned_PCS__c</fullName>
        <formula>Account.Assigned_PCS__r.FirstName + ' ' + Account.Assigned_PCS__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned PCS</label>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Client_s_credit_score__c</fullName>
        <label>Client's credit score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirm_Credit_Reference_Number__c</fullName>
        <label>Confirm Credit Reference Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Indicator__c</fullName>
        <label>Credit Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pull New Credit</fullName>
                </value>
                <value>
                    <fullName>Reissue Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Reference_Number__c</fullName>
        <label>Credit Reference Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Report_type__c</fullName>
        <label>Credit Report type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Joint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAssetsFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAssetsFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsClientFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClientFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCreditInfoFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCreditInfoFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDeclarationFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDeclarationFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsEmploymentFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEmploymentFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsIncomeFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field for income tab</description>
        <label>IsIncomeFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLaibilitiesFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLaibilitiesFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanContactFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanContactFilled_Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanCreatedByLoanProcessor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanCreatedByLoanProcessor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanDetailsFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanDetailsFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubjectPropertyFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSubjectPropertyFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Application_Filled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Application Filled Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_CashFlow_Viewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CashFlow Viewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Loan_Created_Manually__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the loan is create from FNM or from Manual.</description>
        <label>Is Loan Created Manually?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Originating_Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Loan Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Reissue_Vendor__c</fullName>
        <label>Credit Reissue Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CredStar</fullName>
                </value>
                <value>
                    <fullName>Credco</fullName>
                </value>
                <value>
                    <fullName>Equifax</fullName>
                </value>
                <value>
                    <fullName>FundingSuite</fullName>
                </value>
                <value>
                    <fullName>KFD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanAppSubmitted__e.object
<CustomObject><fields>
        <fullName>LoanId__c</fullName>
        <description>The ID of the completed loan.</description>
        <label>LoanId</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Event raised when a loan application has been submitted.</description><eventType>StandardVolume</eventType><label>Loan Application Submitted</label><pluralLabel>Loan Application Submitted</pluralLabel></CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>LoanStatus</relationshipLabel>
        <relationshipName>LoanStatus</relationshipName>
        <type>Lookup</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/SAL_CreditInfoController.cls
public with sharing class SAL_CreditInfoController {
    public class ButtonEnableResponse{
        @AuraEnabled public   Boolean  CompleteStatus { get;set; }
        @AuraEnabled public   Boolean  IsLoancreatedMAnually { get;set; }
    }   
    @AuraEnabled
    public static Loan_New__c  CreditInfo_TabsValidatedData(string RecordId) 
    {    
        Loan_New__c objLoan = new Loan_New__c();  
        try
        { 
            objLoan  = GenericController.TabsData(RecordId);           
        }
        catch(Exception ex)
        {
            system.debug(' CreditInfo_TabsValidatedData----Exception---'+ex);
        }
        return objLoan;
        
    } 
    @AuraEnabled
    public static ButtonEnableResponse GetButtonEnableFlag(Id LoanID)
    {
        ButtonEnableResponse BtnResponese=new ButtonEnableResponse();
        boolean IsLoancreatedManuallyStatus=[select Is_Loan_Created_Manually__c from Loan_New__c where id=:LoanID].Is_Loan_Created_Manually__c;
        boolean ReturnValue=false;
        integer count=0;
        try
        {
            count=[SELECT count() FROM Loan_New__c  where IsLoanFilled_Flag__c=:true and
                   IsSubjectPropertyFilled_Flag__c=:true and  IsClientFilled_Flag__c=:true and
                   IsEmploymentFilled_Flag__c=:true and IsAssetsFilled_Flag__c=:true and
                   IsIncomeFilled_Flag__c=:true and  IsLaibilitiesFilled_Flag__c=:true and 
                   IsDeclarationFilled_Flag__c=:true  and IsLoanDetailsFilled_Flag__c=:true and
                   Is_CashFlow_Viewed__C=:true and IsLoanContactFilled_Flag__c=:true and  Id=:LoanID];
            if(count>0)
                //True means Tabs Validated
                ReturnValue=true;            
        }
        catch(Exception ex)
        {
            system.debug('GetButtonenableFlag--Exception---'+ex);
        } 
        //True means Loan created MAnually
        BtnResponese.IsLoancreatedMAnually=IsLoancreatedManuallyStatus;
        //True means Tabs Validated
        BtnResponese.CompleteStatus=ReturnValue;
        return BtnResponese;
        
    }
    @AuraEnabled
    public static Loan_New__c GetcreditInfoById(string LoanID)
    {
        Loan_New__c CreditInfo=new Loan_New__c();
        try
        {
            CreditInfo =  [SELECT Id,Is_Application_Filled_Flag__c, Client_s_credit_score__c, Credit_Indicator__c,Credit_Report_type__c, Credit_Reissue_Vendor__c, Credit_Reference_Number__c, 
                           Confirm_Credit_Reference_Number__c, LoanStatus__c  FROM Loan_New__c where Id = :LoanId];
        }
        catch(Exception ex)
        {
            system.debug('GetcreditInfoById--Exception---'+ex);
        } 
        return CreditInfo;
    }  
      
    @AuraEnabled
    public static  void  SaveCreditInfo(Loan_New__c ObjCreditInfo,string loanID) 
    {
        try
        {
            ObjCreditInfo.IsCreditInfoFilled_Flag__c = true;
            ObjCreditInfo.Is_Application_Filled_Flag__c = true;
            ObjCreditInfo.Id=loanID;
            ObjCreditInfo.LoanCompleteFlag__c = true;
            ObjCreditInfo.LoanStatus__c = 'Proposal';
            Loan_New__C loanObj  = [Select id,Name, IsLoanCreatedByLoanProcessor__c, LoanCompleteFlag__c, Originating_Loan_Officer__c 
                                    from Loan_New__C Where Id =: LoanID];
           If(loanObj.IsLoanCreatedByLoanProcessor__c )
            {
                ObjCreditInfo.ownerid=loanObj.Originating_Loan_Officer__c;
            }
            else{
                 ID LoanCreatorID=[select createdbyid from loan_new__c where id=:loanID ].createdbyid;
             ObjCreditInfo.Originating_Loan_Officer__c=LoanCreatorID;
            }
            upsert ObjCreditInfo; 
           // Publish completed loan event
           LoanAppSubmitted__e appSubmittedEvent = new LoanAppSubmitted__e(LoanId__c=loanID);
            Database.SaveResult sr = EventBus.publish(appSubmittedEvent);
            if (sr.isSuccess()) {
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                }
            }  
           // This could be moved into an event handler that listens to the platform event above.
            //MailSend.SendMail2Partnernew(LoanName);
            //MailSend.SendMail2ORMnew(LoanName);      
        }
        catch(Exception ex)
        {
             //Exception_log.Log_exception(ex,'SAL_CreditInfoController','SaveCreditInfo');
            system.debug('SaveCreditInfo--Exception---'+ex);
        }        
    }
    @AuraEnabled
    public static integer  GetAllClientByLoanId(string LoanID)
    {
        List<Client__c> AllClientByLoanId=new List<Client__c>();
        try
        {
            AllClientByLoanId =  [SELECT Id, Name,First_Name__c,Last_Name__c, LoanId__c FROM Client__c 
                                  where  is_Active__c  = true and LoanId__c = :LoanId  ];
        }
        catch(Exception ex)
        {
            system.debug('GetAllClientByLoanId--Exception---'+ex);
        } 
        return AllClientByLoanId.size();
    }
    
    @AuraEnabled //Balaa, A task will be created for AE when Application Package is requested - 4/20
        public static string createAETask(String LoanID){
            
            List<Loan_New__c> ls= new List<Loan_New__c>();
            ls =  [SELECT Id,LoanStatus__c FROM Loan_New__c WHERE Id =:LoanID and IsActiveFlag__c=: true and LoanCompleteFlag__c=: true               
                   ORDER BY LoanStatus__c];
                            
            user u = [SELECT contactId, contact.AccountId FROM user WHERE id=:userinfo.getUserId()];
            
            Task t = new Task();
                    Account a = new Account();
                    a = [SELECT name, Account_Executive_Name__c,Assigned_PCS__r.id FROM Account WHERE id =:u.contact.AccountId ];
                    t.Subject = 'An Application has been requested by the Partner';
                    t.Status = 'Open';
                    t.Priority = 'Normal';
                    t.WhatId = LoanID;
                    system.debug('###' +LoanID);
                    t.ActivityDate = Date.Today();
                    t.OwnerId = a.Account_Executive_Name__c;                    
                    t.WhoId = u.contactId;        
                    insert t;               
            return t.id;
        }   
}