src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_NMLS_ID__c</fullName>
        <label>Company NMLS ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Contact_NMLS__c</fullName>
        <label>NMLS ID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/classes/pricingWholesaleScheduler_Test.cls
@istest
class pricingWholesaleScheduler_Test{

   static testmethod void test() {
        System.Test.startTest();              
            
            Account a = new Account();
            a.Name = 'pricingwholesale';
            a.Company_NMLS_ID__c = '55555';            
            a.recordtypeId = '01239000000EGZp';
            insert a;
                    
            Contact c = new Contact();
            c.Lastname = 'tewsting12';
            c.Email = 'test2@test2.com';           
            c.Office_Phone__c = '1224577899';
            c.Contact_NMLS__c = '998233';
            c.title__c = 'Processor';
            c.recordtypeId = '01239000000N6e1';
            insert c;

            // Schedule the test job
            pricingWholesaleScheduler pw1 = new pricingWholesaleScheduler();
            String pws = '0 0 23 * * ?'; 
            system.schedule('pricingWholesaleScheduler', pws, pw1); 
            
            pricingWholesale pw =  new pricingWholesale();
            try{
            Database.executeBatch(pw, 200);}catch(Exception ex){}
            pw.execute(null,[select id,Email from contact ]);
       System.Test.stopTest();
    }
}