src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Received_Date__c</fullName>
        <label>Appraisal Received Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>PreviousStatus__c</fullName>
        <label>Previous Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status - Used By Executive Reporting</description>
        <inlineHelpText>Status - Used By Executive Reporting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Full Package Received</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/LoanStatusHandlerTest.cls
/**
 * @description Apex Tests for LoanStatusHandler
 * @author Mike Gill
 * @date 28th June 2018
 * 
 * 07/27/18 MG/QDA BUG FIX - Tighten up tests for to explicitly check SFDC-222 (update)
 *
 */

@isTest (SeeAllData=false)
private class LoanStatusHandlerTest {

    @testSetup
    static void testSetupData(){

        // Insert Test Partner record with name (Test Partner) to bypass PB
        Account a = (Account)TestFactory.createSObject(new Account( Name = 'Test Partner')); 
        insert a;

        // Insert Skinny Loan record for testing
        Loan_New__c loan = new Loan_New__c(
                    IsActiveFlag__c= true,
                    LoanCompleteFlag__c= true,
                    Related_Partner__c = a.Id,
                    LoanStatus__c ='Funded',
                    LoanNumber__c = '12345',
                    Appraisal_Received_Date__c=Date.parse('10/11/2017')
        );
        insert loan;
    }

    @isTest static void testLoanStatusHistory(){

        List<Loan_New__c> testLoans = [SELECT Id,LoanStatus__c FROM Loan_New__c];
        System.assertEquals(testLoans.size(), 1);
        List<Loan_New__c> loanUpdates = new List<Loan_New__c>();

        Test.startTest();
        for (Loan_New__c l: testLoans){
            l.LoanStatus__c = 'Incomplete';
            loanUpdates.add(l);
        }
        update loanUpdates;

        Test.stopTest();
        List<LoanStatus__c> loanStatusHistory = [SELECT Id FROM LoanStatus__c];
        System.assertEquals(loanStatusHistory.size(), 1);

    }

	/**
	 * @description Test Labels are recorded in Loan Status History object and not API names
	 */
	@isTest static void testLabelValueSet(){

        List<Loan_New__c> testLoans = [SELECT Id,LoanStatus__c FROM Loan_New__c];
        System.assertEquals(testLoans.size(), 1);
        List<Loan_New__c> loanUpdates = new List<Loan_New__c>();

        Test.startTest();
        for (Loan_New__c l: testLoans){
            l.LoanStatus__c = 'Proposal';
            loanUpdates.add(l);
        }
        update loanUpdates;

        Test.stopTest();
        List<LoanStatus__c> loanStatusHistory = [SELECT Id, Name, PreviousStatus__c, Status__c FROM LoanStatus__c];
        System.assertEquals(loanStatusHistory.size(), 1);
		System.assertEquals(loanStatusHistory[0].Name, 'Application Requested');
		System.assertEquals(loanStatusHistory[0].PreviousStatus__c, 'Funded');
		System.assertEquals(loanStatusHistory[0].Status__c, 'Application Requested');
		

    }


}