src/objects/Address__c.object
<CustomObject><fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields><fields>
        <fullName>Zip__c</fullName>
        <description>Can have only numbers and/or one - (Hyphen)</description>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Address</label><nameField>
        <label>Street Address</label>
        <type>Text</type>
    </nameField><pluralLabel>Addresses</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith><visibility>Public</visibility></CustomObject>

src/objects/AttachmentStatus__c.object
<CustomObject>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <label>AttachmentID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>AttachmentStatus</relationshipLabel>
        <relationshipName>AttachmentStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AttachmentStatus</label>
    <nameField>
        <label>Status</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AttachmentStatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>ResponsePayload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <inlineHelpText>JSON representation of Response from External Service</inlineHelpText>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SourceID__c</fullName>
        <description>Source Id</description>
        <inlineHelpText>Source Id</inlineHelpText>
        <label>Source ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestingUserID__c</fullName>
        <description>The ID of the User originating this request.</description>
        <inlineHelpText>The ID of the User originating this request.</inlineHelpText>
        <label>Requesting User ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>Mandatory if Real Estate Schedule is selected in the category</description>
        <label>Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Mandatory if Real Estate Schedule is selected in the category</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>Must have only digits or can have one hyphen(-)</description>
        <label>County</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Liability_Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alimony</fullName>
                </value>
                <value>
                    <fullName>Job Expense</fullName>
                </value>
                <value>
                    <fullName>Liability</fullName>
                </value>
                <value>
                    <fullName>Real Estate Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Liability_Monthly_Payment__c</fullName>
        <label>Monthly Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Liability_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Liability_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Divorce</fullName>
                </value>
                <value>
                    <fullName>Child Support</fullName>
                </value>
                <value>
                    <fullName>Separate Maintenance.</fullName>
                </value>
                <value>
                    <fullName>Job Related Expenses</fullName>
                </value>
                <value>
                    <fullName>Other expense</fullName>
                </value>
                <value>
                    <fullName>Collections/Judgements/Liens</fullName>
                </value>
                <value>
                    <fullName>Home Equity Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Lease Payments</fullName>
                </value>
                <value>
                    <fullName>Mortgage Loans</fullName>
                </value>
                <value>
                    <fullName>Open 30 day Charge Accounts</fullName>
                </value>
                <value>
                    <fullName>Revolving</fullName>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Mechnic Lien</fullName>
                </value>
                <value>
                    <fullName>Property Taxes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Liability_Unpaid_Balance__c</fullName>
        <label>Unpaid Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name_of_Company__c</fullName>
        <description>Mandatory if Real Estate Schedule is selected in the category</description>
        <label>Name of Company</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Mandatory if Real Estate Schedule is selected in the category</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Mandatory if Real Estate Schedule is selected in the category</description>
        <inlineHelpText>Must have only digits or can have one hyphen(-)</inlineHelpText>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Liability object</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_s_credit_score__c</fullName>
        <label>Client's credit score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirm_Credit_Reference_Number__c</fullName>
        <label>Confirm Credit Reference Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Report_Date__c</fullName>
        <label>Credit Report Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_of_Company__c</fullName>
        <label>Name of Company</label>
        <length>254</length>
        <type>Text</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/CreditReportDomainService.cls
/**
 * @description Credit Report Domain Class
 * @author Dennis Wilson
 * @date 06/29/2018
 *
 * changelog:
 */
public without sharing class CreditReportDomainService implements ExternalServiceInterface {

	// Static Constants
	private static final String ES_PRODUCT_UPDATED = 'Product Updated';
	private static final String ES_UPDATE_ERROR = 'Error/Exception';
	private static final String LIABLIITY_CATEGORY = 'Liability';

	/*******************************************************************************************************
	* @description used to induce exception coverage by test methods
	*/
	@TestVisible
	private static Boolean testException = FALSE;

	/**
	 * @description Prepare & Process Response Data
	 * @param  sourceIds   External Service records from CreditReport service to process
	 */
	public void processResponses( List<ExternalService__c> esList ) {

		System.debug( '>>> esList: ' + esList );
		Logger.push( 'processResponses', 'CreditReportDomainService' );
		Logger.debug( 'Starting processing records' );
		// list of loans to update
		List<Loan_New__c> loanUpdateList = new List<Loan_New__c>();
		// list of liability records to create
		List<Liability__c> liabilityInsertList = new List<Liability__c>();
		// list of external service records to update
		List<ExternalService__c> esUpdateList = new List<ExternalService__c>();
		// iterate through incoming list of external service records
		for ( ExternalService__c es : esList ) {
			// pull values for loan from external service record
			// safe convert Id
			Id loanId;
			try { loanId = Id.valueOf( es.SourceID__c ); }
			catch ( Exception e ) {}

			// parse json payload into response object
			creditResponse cr = ( creditResponse )JSON.deserialize( es.ResponsePayload__c, creditResponse.class );
			System.debug( '>>> parsed cr: ' + cr );

			// ensure we've got everything needed
			if ( loanId != NULL && cr != NULL ) {
				// loan values to update
				Loan_New__c loan = new Loan_New__c (
					Id = loanId,
					Client_s_credit_score__c            = ( String.isNotBlank( cr.creditScore ) ? Integer.valueOf( cr.creditScore ) : NULL ),
					Credit_Report_Date__c               = ( String.isNotBlank( cr.creditReportDate ) ? Date.valueOf( cr.creditReportDate ) : NULL ),
					Confirm_Credit_Reference_Number__c  = cr.creditReferenceNumber,
					CreditIsComplete__c                 = TRUE
				);
				// build up loan and external lists in parallel so that indexing by save result is possible
				loanUpdateList.add( loan );
				esUpdateList.add( es );
				// create the related liability records
				if ( cr.creditReportLine != NULL ) {
					for ( reportLineResponse rLineResp : cr.creditReportLine ) {
						Liability__c liability = new Liability__c(
							RelatedLoan__c                  = loanId,
							Liability_Category__c           = LIABLIITY_CATEGORY,
							Account_Number__c               = rLineResp.accountNumber,
							Address__c                      = rLineResp.addressCreditor,
							Liability_Monthly_Payment__c    = Decimal.valueOf( rLineResp.monthlyPayment ),
							City__c                         = rLineResp.cityCreditor,
//						County__c                       = rLineResp.countyCreditor,
							Name_of_Company__c              = rLineResp.creditor,
							State__c                        = rLineResp.stateCreditor,
							Liability_Type__c               = ( String.isNotBlank( rLineResp.liabilityType ) ? rLineResp.liabilityType : 'Other' ),
							Liability_Unpaid_Balance__c     = Decimal.valueOf( rLineResp.balance ),
							Zip__c                          = rLineResp.zipCreditor
						);
						liabilityInsertList.add( liability );
					}
				}

				// TODO: create related ORM Document with Credit Report URL
				// json structure allows for multiple doc entries, but usually just one
				if ( cr.docs != NULL ) {
					for ( docResponse doc : cr.docs ) {
						retrieveReportPDF( loanId, doc.downloadUrl, es.RequestingUserID__c );
					}
				}
			}

		}
		// allow for partial success, and test each individual update result
		// note that ordering of save results matches order of external service update list
		System.debug( '>>> updating loanUpdateList: ' + loanUpdateList );
		List<Database.SaveResult> saveResultList = Database.update( loanUpdateList, FALSE );
		// iterate through results, update external service appropriately
		Integer listIndex = 0;
		for ( Database.SaveResult result : saveResultList ) {
			if ( result.isSuccess() && !testException ) {
				// update es with success
				esUpdateList[listIndex].Status__c = ES_PRODUCT_UPDATED;
			} else {
				// update es with failure
				esUpdateList[listIndex].Status__c = ES_UPDATE_ERROR;
				String errorInfo ='\r\n[Loan Update Errors:]\r\n' + String.join( result.getErrors(), ', ' );
				String currentPayload = esUpdateList[listIndex].ResponsePayload__c;
				// protect against null payload
				esUpdateList[listIndex].ResponsePayload__c = (
					String.isNotBlank( currentPayload )
						? currentPayload + errorInfo
						: errorInfo
				);
			}
			// advance to the next pair of loan update result and external service record in parallel lists
			listIndex++;
		}
		// TODO: refactor this sequence to rollback entire sequence if a problem updating loan, or creating liabilities
		try {
			Database.insert( liabilityInsertList );
		}
		catch ( DmlException e ){
			System.debug( '>>> liabilityInsertList exception: ' + e );
			Logger.debugException( e );
		}
		// update the original external service records passed in
		try {
			Database.update( esUpdateList );
		}
		catch ( DmlException e ){
			Logger.debugException( e );
		}
		Logger.pop();
	}


	/*******************************************************************************************************
	* @description retrieves credit report PDF and constructs ORM Document (Attachment) related to loan
	* @param reportURL fully formed URL to use for retrieval of PDF
	* @return String:  results of retrieval
	*/
	@future( callout = TRUE )
	public static void retrieveReportPDF( String loanId, String reportURL, String userId ) {

		// retrieve file from AWS using provided URL
		// construct http request
		HttpRequest req = new HttpRequest();
		req.setEndpoint( reportURL );
		req.setMethod( 'GET' );
		Http http = new Http();
		// send request
		HttpResponse res = http.send( req );
		System.debug( '>>> retrieveReportPDF: returned response status: ' + res.getStatusCode() );
		Attachment attach = new Attachment();
		if ( res.getStatusCode() == 200 ) {
			// good response, create attachment
			attach.Body = res.getBodyAsBlob();
			// construct file name using users time zone
			attach.Name = 'Credit Report - ' + Datetime.now().format( 'yyyy-MM-dd hh:mm:ssa', System.UserInfo.getTimeZone().toString() ) + '.pdf';
			attach.ContentType = 'application/pdf';
			attach.IsPrivate = FALSE;
			attach.ParentId = loanId;
			// guard against null or malformed user id
			if ( String.isNotBlank( userId ) ) {
				Id validId;
				try {
					validId = ( Id )userId;
				} catch ( Exception e ) {}
				if ( validId != NULL ) {
					attach.OwnerId = validId;
				}
			}
			Database.insert( attach );
		} else {
		}
		// construct attachment status record to achieve a complete ORM Document
		// compatible with LoanOfficerDocument component
/*
		AttachmentStatus__c attachmentStatus = new AttachmentStatus__c(
			AttachmentID__c = attach.Id,
			LoanId__c = loanId,
			Name = attach.Name
		);
		Database.insert( attachmentStatus );
*/
	}

	/*******************************************************************************************************
	* @description inner classes used for deserializing JSON response
	*/
	class docResponse {
		String downloadUrl;
		String contentType;
		String expiresAtEpochMs;
	}

	class reportLineResponse {
		String accountNumber;
		String addressCreditor;
		String cityCreditor;
		String stateCreditor;
		String zipCreditor;
		String balance;
		String monthlyPayment;
		String creditor;
		String liabilityType;
	}

	class creditResponse {
		String status;
		List<docResponse> docs;
		List<reportLineResponse> creditReportLine;
		String creditScore;
		String creditReportDate;
		String creditReferenceNumber;
		String reference;
	}
}