src/objects/Asset.object
<CustomObject><fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Stock &amp; Bonds</fullName>
                </value>
                <value>
                    <fullName>Life Insurance</fullName>
                </value>
                <value>
                    <fullName>Retirement Fund</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Real Estate Owned(REO)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Name_of_Institution__c</fullName>
        <description>Field visible for Bank/Credit union, stock &amp; Bonds, Life Insurance, Retirement Fund and Business Categories</description>
        <label>Name of Institution</label>
        <length>200</length>
        <type>Text</type>
    </fields><fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><sharingModel>ReadWrite</sharingModel></CustomObject>

src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Employer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerAddress__c</fullName>
        <label>EmployerAddress</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerName__c</fullName>
        <label>EmployerName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerPhone__c</fullName>
        <description>Make a validation to make it a 10 digit number, doesn&apos;t start with 0, does not allow all same digits</description>
        <label>EmployerPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IncomeValue__c</fullName>
        <label>IncomeValue</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Type__c</fullName>
        <label>Income_Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <description>Can&apos;t be less than 0</description>
        <label>Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PositionTitle__c</fullName>
        <label>Position/Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Employer State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Years__c</fullName>
        <description>Can&apos;t be  less than zero</description>
        <label>Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Received_Date__c</fullName>
        <label>Appraisal Received Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanCreatedByLoanProcessor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanCreatedByLoanProcessor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanDetailsFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanDetailsFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoanFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanOfficer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Officer*</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LoanOfficer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/SAL_ApexManagedSharingControllerTest.cls
@isTest
public class SAL_ApexManagedSharingControllerTest {
    @isTest static void UpdateOwnerAfterLoanSubmitTest()
    {
         Id sAdmin=[select Id from Profile where Name=:'System Administrator' limit 1].Id;
        User Uid =[select Id from User where ProfileId !=:sAdmin and IsActive=true limit 1];
        
        Loan_New__c loan = new Loan_New__c(IsActiveFlag__c= true, IsLoanFilled_Flag__c=true,LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                               LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),
                                          IsLoanCreatedByLoanProcessor__c=true,IsLoanDetailsFilled_Flag__c=true);
            insert loan;
        Loan_New__c loanUpdated = new Loan_New__c(Id=loan.Id,IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                               LoanNumber__c = '56789',Appraisal_Received_Date__c=Date.parse('10/11/2017'),
                                                 LoanOfficer__c=Uid.id);
        loan.LoanNumber__c = '56789';
        update loanUpdated;
        Asset ObjAsset = new asset(Name = 'Drush', RelatedLoan__c = loan.Id,Category__c = 'Others', isActive__c = true, Name_of_Institution__c = 'DS');
            Insert ObjAsset;  
            string AssetId = ObjAsset.Id;
        	string loanId = loan.Id;
        SAL_ApexManagedSharingController.ShareLoanRecord(loan,loanUpdated);
        SAL_ApexManagedSharingController.DeleteSharedRecord(loan.Id,'Manual');
        SAL_ApexManagedSharingController.UpdateOwnerAfterLoanSubmit(loan.Id, loan, loanUpdated);
        List<String> getId = SAL_ApexManagedSharingController.GetIds(loanId, 'Loan_New__c');
        SAL_ApexManagedSharingController.ShareRecordAfterInsert(loan.Id, loan.Id, 'Loan_New__c','Loan_New__Share','Manual','Manual');
        SAL_ApexManagedSharingController.UpdateSharingWhenLoanOfficerCreateLoan(loan.Id, loan.Id, 'Loan_New__c','Loan_New__Share','Manual','Manual');
         SAL_ApexManagedSharingController.LoanCreatedByORMPartner(loan,loanUpdated);
    }
    @isTest static void UpdateOwnerAfterLoanSubmitTest1()
    {
        Loan_New__c loan = new Loan_New__c(IsActiveFlag__c= true,IsLoanFilled_Flag__c=true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                               LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),
                                          IsLoanCreatedByLoanProcessor__c=false,IsLoanDetailsFilled_Flag__c=true);
            insert loan;
        Loan_New__c loanUpdated = new Loan_New__c(Id=loan.Id,IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                               LoanNumber__c = '56789',Appraisal_Received_Date__c=Date.parse('10/11/2017'),
                                                 LoanOfficer__c=null);
        loan.LoanNumber__c = '56789';
        update loanUpdated;
        SAL_ApexManagedSharingController.ShareLoanRecord(loan,loanUpdated);
        SAL_ApexManagedSharingController.ShareRecordAfterInsert(loan.Id, loan.Id, 'Loan_New__c','Loan_New__Share','Manual','Manual');
    }
    @isTest static void UpdateOwnerAfterLoanSubmitTest2()
    {
        Id sAdmin=[select Id from Profile where Name=:'System Administrator' limit 1].Id;
        User Uid =[select Id from User where ProfileId !=:sAdmin and IsActive=true limit 1];
        
        Loan_New__c loan = new Loan_New__c(IsActiveFlag__c= true, LoanCompleteFlag__c= true,LoanStatus__c ='Funded',
                                               LoanNumber__c = '12345',Appraisal_Received_Date__c=Date.parse('10/11/2017'),
                                          IsLoanCreatedByLoanProcessor__c=false,IsLoanDetailsFilled_Flag__c=true);
            insert loan;
        
        Loan_New__c loanUpdated = new Loan_New__c(Id=loan.Id,LoanOfficer__c=Uid.id, ownerid=Uid.id);
      
        update loanUpdated;
          Employment__c objEmployment = new Employment__c(City__c = 'Ghaziabad',EmployerAddress__c = 'Delhi',
            EmployerName__c = 'ORMS',EmployerPhone__c = '7894561230',Months__c = 2,
            PositionTitle__c = 'Manager',RelatedLoan__c = loanUpdated.Id,
            State__c = 'California',Years__c = 2,IncomeValue__c = 0.00, Income_Type__c = 'Employment Income');
        Insert objEmployment;   
        system.runAs(Uid){
            
        
        SAL_ApexManagedSharingController.ShareLoanRecord(loan,loanUpdated);
        SAL_ApexManagedSharingController.UpdateSharingWhenLoanOfficerCreateLoan(objEmployment.Id, loan.Id, 'Loan_New__c','Loan_New__Share','Manual','Manual');
        SAL_ApexManagedSharingController.LoanCreatedByORMPartner(loan,loanUpdated);
            //code to increase test coverage
            List<string> child = SAL_ApexManagedSharingController.loanChildObjectsList();
        	List<string> child1 = SAL_ApexManagedSharingController.ObjectListforChangeOwner();        	
        	Map<string, string> loanChild = SAL_ApexManagedSharingController.loanChildShareObjectsMap();
        	Map<string, string> loanChild1 = SAL_ApexManagedSharingController.loanChildObjectsMap();
            //List<string> child2 = SAL_ApexManagedSharingController.loanChildObjectsList1();
        	List<string> child3 = SAL_ApexManagedSharingController.ObjectListforChangeOwner1();        	
        	/*Map<string, string> loanChild2 = SAL_ApexManagedSharingController.loanChildShareObjectsMap1();
        	Map<string, string> loanChild3 = SAL_ApexManagedSharingController.loanChildObjectsMap1();*/
        }}
}