src/objects/Asset.object
<CustomObject><fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>200</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Cash_or_Market_Value__c</fullName>
        <description>Value must be greater than 0</description>
        <label>Cash or Market Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Stock &amp; Bonds</fullName>
                </value>
                <value>
                    <fullName>Life Insurance</fullName>
                </value>
                <value>
                    <fullName>Retirement Fund</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Real Estate Owned(REO)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Is_Asset_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Asset Validated?</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Life_Insurance_Policy_Face_Value__c</fullName>
        <description>Value must be greater than 0</description>
        <label>Life Insurance Policy - Face Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Net_Worth_of_Business_es_Owned__c</fullName>
        <description>Value must be greater than 0</description>
        <label>Net Worth of Business(es) Owned</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Other_Asset_Amount__c</fullName>
        <description>Value must be greater that 0</description>
        <label>Other Asset Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Other_Assets_Type__c</fullName>
        <label>Other Assets Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Deposit on Sales Contract</fullName>
                </value>
                <value>
                    <fullName>Gifts Not Deposited</fullName>
                </value>
                <value>
                    <fullName>Secured Borrower Funds not Deposited</fullName>
                </value>
                <value>
                    <fullName>Bridge Loan Not Deposited</fullName>
                </value>
                <value>
                    <fullName>Other Non-Liquid Asset</fullName>
                </value>
                <value>
                    <fullName>Other Liquid Asset</fullName>
                </value>
                <value>
                    <fullName>Net Equity</fullName>
                </value>
                <value>
                    <fullName>Liquid Assets</fullName>
                    <isActive>false</isActive>
                    <label>Liquid Assets</label>
                </value>
                <value>
                    <fullName>Non-Liquid Assets</fullName>
                    <isActive>false</isActive>
                    <label>Non-Liquid Assets</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Present_Market_Value__c</fullName>
        <label>Present Market Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Retirement_Funds__c</fullName>
        <label>Retirement Funds</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Schedule_of_REO_Address_Line_2__c</fullName>
        <label>Schedule of REO Address Line 2</label>
        <length>200</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Schedule_of_REO_City__c</fullName>
        <label>Schedule of REO City</label>
        <length>200</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Schedule_of_REO_Property_Address__c</fullName>
        <label>Schedule of REO Property Address</label>
        <length>200</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Schedule_of_REO_State__c</fullName>
        <label>Schedule of REO State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields><fields>
        <fullName>Schedule_of_REO_Zip_Code__c</fullName>
        <description>can have numbers or one hyphen (-)</description>
        <label>Schedule of REO Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>250</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type of Stock Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Stock</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Mutual fund</fullName>
                </value>
                <value>
                    <fullName>Gift of Equity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Type_of_Account__c</fullName>
        <description>Savings, Money Market, Checking Account</description>
        <label>Type of Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Certificate of Deposit/Time Deposit</fullName>
                </value>
                <value>
                    <fullName>Checking Account</fullName>
                </value>
                <value>
                    <fullName>Trust Account</fullName>
                </value>
                <value>
                    <fullName>Cash on Hand</fullName>
                </value>
                <value>
                    <fullName>Money Market Fund</fullName>
                </value>
                <value>
                    <fullName>Savings Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Vested_Interest_in_Retirement_Fund__c</fullName>
        <description>Value must be greater than 0</description>
        <label>Vested Interest in Retirement Fund</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>isJoint__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pointer to all the clients</description>
        <label>isJoint</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><sharingModel>ReadWrite</sharingModel></CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>ClientDetails</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Client_for_the_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Client for the Loan</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Present_Market_Value__c</fullName>
        <label>Present Market Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/SAL_AssetController.cls
public class SAL_AssetController {
    
    //get Client List 
    @AuraEnabled
    public static List<Client__c> getClientList(string LoanId) {
        return GenericController.getAllClientList(LoanId);  
    }
     @AuraEnabled
    public static Loan_New__c  Asset_TabsValidatedData(string RecordId) 
    {    
        Loan_New__c objLoan = new Loan_New__c();  
        try
        { 
            objLoan  = GenericController.TabsData(RecordId);
            
        }
        catch(Exception ex)
        {
            system.debug(' Asset_TabsValidatedData----Exception---'+ex);
        }
        return objLoan;
    } 
    //Save Asset(Insert/Update)
    @AuraEnabled
    public static void SaveAsset(Asset ObjAsset,string ClientId,string LoanId, string assetCategory) {
        try{
            Loan_New__c ObjL=[SELECT Id,Related_Individual__c,Related_Partner__c from Loan_New__c where Id=: LoanId ];
            if(ClientId=='Joint')
            {
                system.debug('Joint Call'+ClientId);
                string PrimaryClientId=[Select Id from Client__c where LoanId__c=:LoanId and  Primary_Client_for_the_Loan__c=true].Id;
                ObjAsset.RelatedClient__c =PrimaryClientId;
                ObjAsset.isJoint__c = true;
            }
            else
            {
                ObjAsset.RelatedClient__c = ClientId;
                ObjAsset.isJoint__c = false;
            }
            
            ObjAsset.RelatedLoan__c = LoanId;
            ObjAsset.Category__c =assetCategory;
            ObjAsset.Name='Ast_'+assetCategory;
            ObjAsset.ContactId=ObjL.Related_Individual__c;//objusercontaid.ContactId;
            ObjAsset.AccountId=ObjL.Related_Partner__c;//objusercontaid.AccountId;
            ObjAsset.Is_Asset_Validated__c=true;
            upsert ObjAsset;
            GenericController.UpdateAssetFlag(LoanId);
        }
        catch(Exception ex)
        {
            system.debug(' SaveAsset----Exception---'+ex);
        }
    }
    
    //Get Asset Based On Client and Loan
    @AuraEnabled
    public static List <Asset> getAsset(string LoanId) {
        List <Asset> objAsset =new List <Asset>(); 
        try{ 
            objAsset = [SELECT Id, Is_Asset_Validated__c,Category__c,Type__c,Cash_or_Market_Value__c,Type_of_Account__c,Other_Assets_Type__c,Life_Insurance_Policy_Face_Value__c,Net_Worth_of_Business_es_Owned__c,Other_Asset_Amount__c,Vested_Interest_in_Retirement_Fund__c, 
                        Schedule_of_REO_Property_Address__c,Schedule_of_REO_Address_Line_2__c,Schedule_of_REO_City__c,Schedule_of_REO_State__c,Schedule_of_REO_Zip_Code__c,Present_Market_Value__c,Source_Name__c,RelatedClient__r.Name,isJoint__c  FROM Asset 
                        where isActive__c= true and RelatedLoan__c=: LoanId];
            
        }
        catch(Exception ex)
        {
            system.debug(' getAsset----Exception---'+ex);
        }
        return objAsset;
    }
    @AuraEnabled
    public static decimal getAllAssets(string LoanId) {
        List<AggregateResult> results = new List<AggregateResult>();
        decimal AssetTotal=0.00;
        decimal cash = 0.00,lic = 0.00,vInterest = 0.00, NetWorth = 0.00, PreMarVAlue = 0.00, OtherAsset = 0.00;
        try{ 
            results = [SELECT sum(Cash_or_Market_Value__c),                        
                       sum(Life_Insurance_Policy_Face_Value__c),
                       sum(Vested_Interest_in_Retirement_Fund__c),
                       sum(Net_Worth_of_Business_es_Owned__c),
                       sum(Present_Market_Value__c),
                       sum(Other_Asset_Amount__c)
                       FROM Asset where isActive__c= true and RelatedLoan__c =: LoanId];
            
            cash = ((decimal)results[0].get('expr0')==null?0:(decimal)results[0].get('expr0'));
            lic = ((decimal)results[0].get('expr1')==null?0:(decimal)results[0].get('expr1'));
            vInterest = ((decimal)results[0].get('expr2')==null?0:(decimal)results[0].get('expr2'));
            NetWorth = ((decimal)results[0].get('expr3')==null?0:(decimal)results[0].get('expr3'));
            PreMarVAlue = ((decimal)results[0].get('expr4')==null?0:(decimal)results[0].get('expr4'));
            OtherAsset = ((decimal)results[0].get('expr5')==null?0:(decimal)results[0].get('expr5'));
            AssetTotal = cash + lic + vInterest + NetWorth + PreMarVAlue + OtherAsset;
        }
        catch(Exception ex)
        {
            system.debug(' getAllAssets----Exception---'+ex);
        }
        return AssetTotal;
    }
    
    //Get Asset Based On Asset ID
    @AuraEnabled
    public static Asset  getAssetById(string RecordId) {
        Asset objEmp = new Asset();  
        try
        {
            objEmp = [SELECT Id, Category__c,Type__c,Type_of_Account__c,Cash_or_Market_Value__c,Other_Assets_Type__c ,Life_Insurance_Policy_Face_Value__c,Net_Worth_of_Business_es_Owned__c,Other_Asset_Amount__c,Vested_Interest_in_Retirement_Fund__c,Retirement_Funds__c,Account_Number__c ,
                      Schedule_of_REO_Property_Address__c,Schedule_of_REO_Address_Line_2__c,Schedule_of_REO_City__c,Schedule_of_REO_State__c,Schedule_of_REO_Zip_Code__c,Present_Market_Value__c,Source_Name__c,RelatedClient__c,isJoint__c 
                      FROM Asset  where isActive__c= true and Id=: RecordId];
        }
        catch(Exception ex)
        {
            system.debug(' getAssetById----Exception---'+ex);
        }
        return objEmp;
    }
    
    //Delete(Make Inactive) Asset
    @AuraEnabled
    public static  void DeleteAsset(String RecordId) {
        Asset objAsset = new Asset();
        try
        {
            objAsset= [Select Id,Category__c from Asset where Id = :RecordId];
            ObjAsset.isActive__c=false;
            upsert ObjAsset;
             String loanID=[select RelatedLoan__c from Asset where id=:RecordId limit 1].RelatedLoan__c;
             GenericController.UpdateAssetFlagAfterDelete(loanID);
        }
        catch(Exception ex)
        {
            system.debug(' DeleteAsset----Exception---'+ex);
        }
    }
    
}