src/objects/Asset.object
<CustomObject><fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type of Stock Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Stock</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Mutual fund</fullName>
                </value>
                <value>
                    <fullName>Gift of Equity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><sharingModel>ReadWrite</sharingModel></CustomObject>

src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>ClientDetails</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_Borrowing_Resident__c</fullName>
        <label>Non-Borrowing Resident</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_Borrowing_Spouse_Name__c</fullName>
        <label>Non-Borrowing Spouse Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Declaration__c.object
<CustomObject><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Declaration</label><nameField>
        <label>Declaration Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Declarations</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Client_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_New__c.object
<CustomObject>
    <fields>
        <fullName>Income_Source__c</fullName>
        <label>Source Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Value__c</fullName>
        <label>Income Value</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipName>Income_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipName>Income_New</relationshipName>
        <type>Lookup</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Income</label><nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Incomes</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Liability__c.object
<CustomObject>
    <fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Liability Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Collections/Judgments/Liens</fullName>
                </value>
                <value>
                    <fullName>Home Equity Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Installment</fullName>
                </value>
                <value>
                    <fullName>Lease Payments</fullName>
                </value>
                <value>
                    <fullName>Mortgage Loans</fullName>
                </value>
                <value>
                    <fullName>Open 30 day Charge Accounts</fullName>
                </value>
                <value>
                    <fullName>Revolving</fullName>
                </value>
                <value>
                    <fullName>Taxes</fullName>
                </value>
                <value>
                    <fullName>Mechanic Lien</fullName>
                </value>
                <value>
                    <fullName>Property Taxes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <description>Liability object</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Originating_Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Loan Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARM</fullName>
                    <default>true</default>
                    <label>ARM</label>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TitleFeeEstimateResponse__c</fullName>
        <description>Saved response from TitleFee response for reuse by Baydocs request.</description>
        <inlineHelpText>Saved response from TitleFee response for reuse by Baydocs request.</inlineHelpText>
        <label>TitleFeeEstimateResponse</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Non_Borrowing_Resident__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Non-Borrowing Resident</relationshipLabel>
        <relationshipName>Non_Borrowing_Resident</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Non Borrowing Resident Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActiveNBR__c</fullName>
        <defaultValue>true</defaultValue>
        <description>if checked means alive NBR</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Non-Borrowing Resident</relationshipLabel>
        <relationshipName>Non_Borrowing_Resident</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_Borrowing_Resident_Name__c</fullName>
        <label>Non Borrowing Resident</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Non-Borrowing Resident</label>
    <nameField>
        <displayFormat>NBR-{0}</displayFormat>
        <label>Non-Borrowing Resident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Borrowing Resident</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppPackageRequestHandlerTest.cls
/**
 * @description Apex Tests for AppPackageRequestHandler
 * @author Mike Gill
 * @date 15th August 2018
 *
 */
@isTest(SeeAllData=false)
private class AppPackageRequestHandlerTest {

    @TestSetup static void testSetupData() {
        // Create common test data for use in all test methods
        // @TestSetup initializes test data for each method

        // create test user for runAs
        Id profileId = TestUtils.getProfileId('System Administrator');
        Id userRoleId = TestUtils.getRoleId('System Administrator');
        User testUser = (User) TestFactory.createSObject(new User(ProfileId = profileId,
                UserRoleId = userRoleId), 'TestFactory.UserDefaults');
        Database.insert(testUser);
        // runAs to avoid mixed DML errors
        System.runAs(testUser) {
            // create Account for Loan
            Map<String, Id> recTypeMap = TestUtils.getRecordTypes('Account');
            Account testAccount = (Account) TestFactory.createSObject(new Account(
                    OwnerId = testUser.Id,
                    RecordTypeId = recTypeMap.get('Partners')),
                    'TestFactory.AccountDefaults');
            Database.insert(testAccount);
            // create Contact for Loan
            Contact testContact = (Contact) TestFactory.createSObject(new Contact(
                    AccountId = testAccount.Id,
                    OwnerId = testUser.Id),
                    'TestFactory.ContactDefaults');
            Database.insert(testContact);
            System.assertEquals(testAccount.OwnerId, testUser.Id, 'Owner is not Test User');
            // create portal User
            User testPortalUser = TestUtils.createPortalLoanProcessorUser(testContact.Id);
            Database.insert(testPortalUser);
            // create test Loan
            Loan_New__c testLoan = (Loan_New__c) TestFactory.createSObject(new Loan_New__c(
                    LoanCompleteFlag__c = false,
                    Originating_Loan_Officer__c = testPortalUser.Id,
                    Related_Individual__c = testContact.Id,
                    Related_Partner__c = testAccount.Id,
                    TitleFeeEstimateResponse__c = testTitleFeeResponse,
                    Rate_Type__c = 'ARM'
            ), 'TestFactory.LoanDefaults');
            Database.insert (testLoan);
            // create test Client for Loan
            Client__c testClient = (Client__c) TestFactory.createSObject(new Client__c(
                    LoanId__c = testLoan.Id,
                    First_Name__c = 'Test',
                    Last_Name__c = 'Client',
                    is_Active__c = TRUE,
                    Non_Borrowing_Spouse_Name__c = 'Test Me'
            ));
            Database.insert (testClient);
            // create test Non_Borrowing_Resident__c for Loan
            Non_Borrowing_Resident__c testNonBorrowingResident = (Non_Borrowing_Resident__c) TestFactory.createSObject(new Non_Borrowing_Resident__c(
                    Loan_Id__c = testLoan.Id,
                    Client_Id__c = testClient.Id,
                    IsActiveNBR__c = TRUE,
                    Non_Borrowing_Resident_Name__c = 'Test Me',
                    Date_of_Birth__c = Date.today().addYears(-62)
            ));
            Database.insert (testNonBorrowingResident);
            // create test Income_New__c for Loan
            Income_New__c testIncome = (Income_New__c) TestFactory.createSObject(new Income_New__c(
                    Related_Loan__c = testLoan.Id,
                    Income_Value__c = 100000.00,
                    IsActive__c = TRUE,
                    RelatedClient__c = testClient.Id,
                    Income_Source__c = 'Under Mattress'
            ));
            Database.insert (testIncome);
            // create test Asset for Loan
            Asset testAsset = (Asset) TestFactory.createSObject(new Asset(
                    RelatedLoan__c = testLoan.Id,
                    IsActive__c = TRUE,
                    RelatedClient__c = testClient.Id,
                    Name = 'Test Asset',
                    Category__c = 'Others'
            ));
            Database.insert (testAsset);
            // create test Liability__c for Loan
            Liability__c testLiability = (Liability__c) TestFactory.createSObject(new Liability__c(
                    RelatedLoan__c = testLoan.Id,
                    RelatedClient__c = testClient.Id,
                    IsActive__c = TRUE,
                    Liability_Type__c = 'Divorce',
                    Type__c = 'Revolving',
                    Liability_Category__c = 'Alimony'
            ));
            Database.insert (testLiability);
            // create test Declaration__c for Loan
            Declaration__c testDeclaration = (Declaration__c) TestFactory.createSObject(new Declaration__c(
                    DeclarationLoan__c = testLoan.Id,
                    DeclarationClient__c = testClient.Id
            ));
            Database.insert (testDeclaration);
            // create test Employment__c for Loan
            Employment__c testEmployment = (Employment__c) TestFactory.createSObject(new Employment__c(
                    RelatedLoan__c = testLoan.Id,
                    Client_id__c = testClient.Id
            ));
            Database.insert (testEmployment);
            // setup EnglishChannelConfig__c custom settings (required by EnglishChannelClient)
            EnglishChannelConfig__c eccSetting = new EnglishChannelConfig__c(
                    ApiGatewayEndpoint__c = 'https://test.org',
                    ApiGatewayEndpoint1__c = 'https://test.org'
            );
            Database.insert(eccSetting);
        }
    }

    /**
     * @description Test Invocable Method AppPackageRequestHandler
     */
    @isTest
    private static void testAppPackRequestHandler(){

        // Enable Logging
        Logging_Settings__c logSettings = new Logging_Settings__c(
                Enable_Debug__c = true,
                Enable_Exceptions__c = true
        );
        Database.insert(logSettings);

        List<Loan_New__c> testLoans = [SELECT Id, Name FROM Loan_New__c];

        Test.startTest();
        AppPackageRequestHandler.requestAppPackage( new List<Id>{testLoans[0].Id} );
        Test.stopTest();

        // Use logs to validate - EnglishChannelClient - Send to BayDocs request
        List<Log__c> testLogs = [SELECT Id, Sequence__c, ApexClass__c, ApexMethod__c, Message__c FROM Log__c order by Sequence__c];
        System.assertEquals(testLogs[0].ApexClass__c, 'LoanExportUtil');
        System.assertEquals(testLogs[1].ApexClass__c, 'EnglishChannelClient');
        System.assertEquals(testLogs[2].Message__c, 'request setEndpoint https://test.org');


    }

    /***************************************************************************************************
    *						 Static Test Data
    *************************************************************************************************/

    private static String testTitleFeeResponse {
        get {
            // create enough of a title fee response to be parsed by LoanExportUtil.cls
            // this contains just the minimum sections and tokens to make parsing happy
            Map<Object, Object> titleFeeResponseMap = new Map<Object, Object>{
                    'results' => 'nothing here interesting',
                    'meta' => 'nothing here either',
                    'summary' =>
                            new Map<Object, Object>{
                                    'sections' =>
                                            new Map<Object, Object>{
                                                    'Title Fees' => '900',
                                                    'Closing Fees' => '770',
                                                    'Recording Fees' => '671',
                                                    'Additional Charges and Available Endorsements' => '25'
                                            },
                                    'required' =>
                                            new List<Object>{
                                                    new Map<Object, Object>{
                                                            'FeeTypeName' => 'Mortgage Title Premium',
                                                            'HUDLine' => '1104',
                                                            'Price' => '$900.00',
                                                            'quoteStatus' => 'formulary'
                                                    },
                                                    new Map<Object, Object>{
                                                            'FeeTypeName' => 'Closing Full Escrow 1st Mortgage Fee',
                                                            'HUDLine' => '1102',
                                                            'Price' => '$650.00',
                                                            'quoteStatus' => 'formulary'
                                                    }
                                            }
                            }
            };
            return JSON.serializePretty(titleFeeResponseMap);
        }
        private set;
    }


}