src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Client_for_the_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Client for the Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Contact.object
<CustomObject><fields>
        <fullName>Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Officer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/classes/ContactFieldPopulator.cls
public class ContactFieldPopulator{



    public static void CreateContactFromClient(list<Client__c> Clients){
    
    list<contact> contacts = new list<contact>();
    for(Client__c cli:clients){
        if(cli.Primary_Client_for_the_Loan__c){
            Contact c = new Contact();
            c.Firstname = cli.First_Name__c;
            c.LastName= cli.Last_Name__c;
          //  c.Last_Name__c = 
          user u =  [select contactId,contact.AccountId from user where id=:userinfo.getuserId()];
          c.AccountId = u.contact.AccountId;
          c.Loan_Officer__c = u.contactId;
          c.MailingStreet = cli.Street_Address__c;
          c.MailingCity = cli.City__c;
          c.MailingState = cli.State__c;
          c.MailingPostalcode = cli.Zip__c;
          c.email = cli.Email_Optional__c;
          c.recordtypeid =   Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Portal User').getRecordTypeId();
  
            contacts.add(c);
        
        }
    
    }
    
    if(!contacts.isEmpty()){
    
        insert contacts ;
    }
    
    
    }
}