src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Current State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_has_Email_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client has Email Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <description>Validate it to phone format -10 digits, not starting with 0 and must not accept all same digits like 4444444444</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>ClientDetails</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Client_for_the_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Client for the Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/ClientInfo__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_State__c</fullName>
        <label>Client State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scenario Client</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Name</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Home_Value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>is_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Converted</label>
        <type>Checkbox</type>
    </fields>
  <sharingModel>ReadWriteTransfer</sharingModel>

</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <label>OldLoan</label>
    <nameField>
        <displayFormat>Loan_{000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OldLoans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Requested Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BayDocsOrderNumber__c</fullName>
        <label>BayDocsOrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimate_of_Appraised_Value__c</fullName>
        <label>Estimate of Appraised Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin*</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1.750</fullName>
                </value>
                <value>
                    <fullName>1.875</fullName>
                </value>
                <value>
                    <fullName>2.000</fullName>
                </value>
                <value>
                    <fullName>2.125</fullName>
                </value>
                <value>
                    <fullName>2.250</fullName>
                </value>
                <value>
                    <fullName>2.375</fullName>
                </value>
                <value>
                    <fullName>2.500</fullName>
                </value>
                <value>
                    <fullName>2.625</fullName>
                </value>
                <value>
                    <fullName>2.750</fullName>
                </value>
                <value>
                    <fullName>2.875</fullName>
                </value>
                <value>
                    <fullName>3.000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Property_Address__c</fullName>
        <description>Property Address</description>
        <inlineHelpText>Property Address</inlineHelpText>
        <label>Subject Property Address*</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Property_City__c</fullName>
        <description>Property City</description>
        <inlineHelpText>Property City</inlineHelpText>
        <label>Subject Property City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Property_State__c</fullName>
        <description>Property State</description>
        <inlineHelpText>Property State</inlineHelpText>
        <label>Subject Property State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_Property_Zip_Code__c</fullName>
        <description>Property Zip Code</description>
        <inlineHelpText>Property Zip Code</inlineHelpText>
        <label>Subject Property Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>BayDocsOrderNumber__c</fullName>
        <label>BayDocsOrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>ClientInfo__c</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Client_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Estimated_home_value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>is_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Converted</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/CreateLoanFromScenario.cls
public class CreateLoanFromScenario {
    
    
    @AuraEnabled
    public static void updateSenario(String senarioid,String loanId){
        
        
        Scenario__c se = [select id,ClientId__r.Email_Optional__c,ClientId__c,ClientId__r.State__c,ClientId__r.Street_Address__c,ClientId__r.DOB__c,
                          ClientId__r.Name,ClientId__r.Last_Name__c,ClientId__r.Phone_Number__c,
                          is_Converted__c,Loan__c,Date_of_birth__c,Estimated_home_value__c,Margin__c from Scenario__c where id=:senarioid];
        
        se.is_Converted__c = true;
        //   se.Loan__c = loanId ;
        
        update se;
        
    }
    
    @AuraEnabled
    public static string getFNMData(Blob filedata, String fileName, String base64Data, String contentType, String applicationDate,String senario_id) {
        
        Scenario__c se = [select id,Client_Lead__r.Postalcode,Client_Lead__r.email,Client_Lead__c,Client_Lead__r.State,Client_Lead__r.street,Client_Lead__r.DOB__c,
                          Client_Lead__r.FirstName,Client_Lead__r.Lastname,Client_Lead__r.Phone,Client_Lead__r.city,
                          is_Converted__c,Loan__c,Date_of_birth__c,Estimated_home_value__c,Margin__c from Scenario__c where id=:senario_id];
        
        
        
        
        id loanid;
        try{
            Loan_New__c loan = new Loan_New__c();
            if(!test.isRunningTest()){
                // try{
                // Call fannie mae parser and map response details to loan object
                FNMResponse fnmResponse = FNMParseService.parseFNM(filedata);
                //Code Modified by Dev4 for ORMSFDC-1471
                loan = FNMMapperService.createLoanFromFNMResponse(fnmResponse, Date.valueOf(applicationDate),'ARM','FHA Traditional HECM');
                //Code ended by Dev4 for ORMSFDC-1471
                loanid = loan.id;
                
            }
            if(loan.Subject_Property_Address__c ==null || loan.Subject_Property_Address__c ==''){ 
             loan.Subject_Property_Address__c = se.Client_Lead__r.Street;
                                                                                                 
                                                                                                }
            
            if(loan.Subject_Property_City__c ==null || loan.Subject_Property_City__c ==''){ 
        //    loan.Subject_Property_City__c = se.Client_Lead__c.City__c;
                                                                                           
                                                                                          }
            
            if(loan.Subject_Property_State__c ==null || loan.Subject_Property_State__c ==''){  
             loan.Subject_Property_State__c =se.Client_Lead__r.State;
                                                                                             
                                                                                            }
            
            if(loan.Subject_Property_Zip_Code__c ==null || loan.Subject_Property_Zip_Code__c ==''){    
            loan.Subject_Property_Zip_Code__c =se.Client_Lead__r.Postalcode;
                                                                                                   
                                                                                                  }
            loan.Margin__c = ''+se.Margin__c;
            try{   
                update loan;
            }catch(Exception ex){}
            se.is_Converted__c = true; se.Loan__c = loanid ;
            try{
                update se;
            }catch(exception ex){}
            try{
                System.debug('>>>>>> '+loanid);
                String LoanIDName = [select Name from Loan_New__c where id=: loanid].Name;
                
                
                //MailSend.SendMail2ORM(LoanIDName);
                //MailSend.SendMail2Partner(LoanIDName);
                LoanDateController.saveTheFile(loanid, fileName,  base64Data,  contentType);
            }
            catch(exception e)
            {
                system.debug('getFNMData--Exception---'+e);
            }
            
        }
        catch(exception e)
        {
            system.debug('getFNMData--Exception---'+e);
        }
        
        return loanid;
    }
    
    
    
    @AuraEnabled
    public Static Loan_New__c createLoan(String senarioid){
        
        Scenario__c se = [select id,BayDocsOrderNumber__c,Client_Lead__c,Client_Lead__r.Street,Client_Lead__r.Postalcode,Client_Lead__r.State,Client_Lead__r.Email,ClientId__c,Client_Lead__r.DOB__c,
                          Client_Lead__r.FirstName,Client_Lead__r.LastName,Client_Lead__r.Phone,Client_Lead__r.city,
                          is_Converted__c,Loan__c,Date_of_birth__c,Estimated_home_value__c,Margin__c from Scenario__c where id=:senarioid];
       
     //  try{
       Lead ld = [select id,status from lead where id=:se.Client_Lead__c]; 
       ld.status='Scenario Converted';
     
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(ld.id);
        
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        user u = [select id,contactid,Contact.AccountId from user where id=:userinfo.getuserid()];
        lc.setAccountId(u.contact.AccountId);
       // lc.setAccountId(u.contactid);
        
       // Database.LeadConvertResult lcr = Database.convertLead(lc);
        //System.assert(lcr.isSuccess());
     update ld;
      // }catch(Exception e){}
        Client__c cl = new client__c();
        cl.Name = se.Client_Lead__r.FirstName+ ' '+ se.Client_Lead__r.LastName;
        cl.Primary_Client_for_the_Loan__c = true;
        cl.DOB__c = se.Client_Lead__r.DOB__c;
        cl.First_Name__c = se.Client_Lead__r.FirstName;
        cl.Last_Name__c = se.Client_Lead__r.LastName;
        cl.Home_Phone__c = se.Client_Lead__r.Phone;
        cl.Email_Optional__c= se.Client_Lead__r.Email;
        //   cl.State__c = se.ClientId__r.Client_State__c;
        //   cl.Street_Address__c = se.ClientId__r.Street_Address__c;
        //   cl.Zip__c = se.ClientId__r.Zip__c;
        
        // if(null != se.ClientId__r.Email_Optional__c)
        // cl.Client_has_Email_Address__c = true;
        
        cl.Primary_Client_for_the_Loan__c = true;
        
        
        Loan_New__c newLoan = new Loan_New__c();
        newLoan.Estimate_of_Appraised_Value__c = se.Estimated_home_value__c;
        newLoan.Margin__c = String.valueOf(se.Margin__c);
        newLoan.Application_Date__c = System.today();        
        newLoan.Subject_Property_Address__c = se.Client_Lead__r.Street;
        newLoan.Subject_Property_City__c = se.Client_Lead__r.city;//se.ClientId__r.City__c;
        newLoan.Subject_Property_State__c =se.Client_Lead__r.State;
        newLoan.Subject_Property_Zip_Code__c =se.Client_Lead__r.Postalcode;
        newLoan.Related_Partner__c = [select Contact.AccountId from user Where id=:userinfo.getUserid()].Contact.AccountId;
        newLoan.Account_Number__c = '1234';
        newLoan.BayDocsOrderNumber__c = se.BayDocsOrderNumber__c;
        // try{
        insert newLoan;
        //}catch(Exception ex){}
        se.is_Converted__c = true;
        se.Loan__c = newLoan.id ;
        update se;
        cl.LoanId__c =  newLoan.Id;
        insert cl;
        SAL_ClientController.CreateDeclaration(cl,newLoan.Id);
        System.debug('>>>> newLoan.id '+newLoan.id);
        return [select id,name from Loan_New__c where id=:newLoan.id][0];
    } 
    
}