src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LoanId</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>ClientDetails</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Client_for_the_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Client for the Loan</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <label>OldLoan</label>
    <nameField>
        <displayFormat>Loan_{000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OldLoans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Requested Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimate_of_Appraised_Value__c</fullName>
        <label>Estimate of Appraised Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin*</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1.750</fullName>
                </value>
                <value>
                    <fullName>1.875</fullName>
                </value>
                <value>
                    <fullName>2.000</fullName>
                </value>
                <value>
                    <fullName>2.125</fullName>
                </value>
                <value>
                    <fullName>2.250</fullName>
                </value>
                <value>
                    <fullName>2.375</fullName>
                </value>
                <value>
                    <fullName>2.500</fullName>
                </value>
                <value>
                    <fullName>2.625</fullName>
                </value>
                <value>
                    <fullName>2.750</fullName>
                </value>
                <value>
                    <fullName>2.875</fullName>
                </value>
                <value>
                    <fullName>3.000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Home_Value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Individual</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
<enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <businessProcess>NewProcess</businessProcess>
        <label>Loan</label>
    </recordTypes>
</CustomObject>

src/classes/Opportunity_field_populator.cls
/****
* Author :Ravi
********/

public class Opportunity_field_populator{
    
    
    
    public static void CreateOpportunityForLoan(List<Loan_new__c> newLoans){
        Contact Acc ;
        try{
            try{
            Acc  = [select firstname,lastname,AccountId,Account.name,Id from Contact where id=:[select ContactId from user where id=:Userinfo.getuserid()].ContactId]; 
            system.debug('Contact Value---  '+Acc);
            }catch(exception ex){
                
                Acc = new Contact();
                Acc.firstname = 'aasd';
                Acc.lastname = 'test';
            }
            list<Opportunity> RelatedOpportunities = new list<Opportunity>();
            
            for(Loan_new__c  eachloan:newLoans){
                system.debug('eachloan---  '+eachloan);
                Opportunity opp = new Opportunity();
                Opp.Accountid = Acc.AccountId  ;
                Opp.Name= Acc.firstname +' '+Acc.lastname;
                try{
                Opp.Estimated_Home_Value__c = eachloan.Estimate_of_Appraised_Value__c;
                     }catch(exception ex){}
                try{
                if(null!=eachloan.Margin__c){         Opp.Margin__c = Decimal.ValueOf(eachloan.Margin__c);
                }
                }catch(exception ex){}
                Opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Loan').getRecordTypeId();
                Opp.StageName = 'Proposal';
                Opp.Loan__c = eachloan.id;
                Opp.Application_Date__c = System.Today();
                // Opp.Probability = System.now().addDays(45);
                
                Opp.CloseDate=  System.Today().addDays(45);
                Opp.Related_Individual__c = userinfo.getUserId();
                
                RelatedOpportunities.add(Opp);
            }
            
            //    if(!RelatedOpportunities.isEmpty()){
            
            insert RelatedOpportunities;
            system.debug('RelatedOpportunities---  '+RelatedOpportunities);
        }catch(exception ex){
            system.debug('ex---  '+ex.getMessage());
        }
    }
    
    
    
    
    
    public static void update_opportunity(String loanID){
        
        try{list< Opportunity> opp = [select id,Name from opportunity where Loan__c=:loanID];
            Client__c   ClientRecord = [SELECT Id,  Last_Name__c, First_Name__c FROM Client__c where LoanId__c = :loanID and Primary_Client_for_the_Loan__c = true];
            
            list< Opportunity> updateList = new list<Opportunity>();
            for(Opportunity op:opp){
                op.name = ClientRecord.Last_Name__c+' '+ClientRecord.First_Name__c;  updateList.add(op);
            }
            if(!updateList.isEmpty()){ update updateList;
            }       
            
        }catch(Exception ex){}
    }
    
}