src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Employer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmployerAddress__c</fullName>
        <label>EmployerAddress</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerName__c</fullName>
        <label>EmployerName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerPhone__c</fullName>
        <description>Make a validation to make it a 10 digit number, doesn&apos;t start with 0, does not allow all same digits</description>
        <label>EmployerPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IncomeValue__c</fullName>
        <label>IncomeValue</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Type__c</fullName>
        <label>Income_Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Employment_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Employment Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PositionTitle__c</fullName>
        <label>Position/Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Employer State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Employer Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_New__c.object
<CustomObject>
    <fields>
        <fullName>Income_Source__c</fullName>
        <label>Source Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Value__c</fullName>
        <label>Income Value</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Income_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Income Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipName>Income_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipName>Income_New</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Income_Types__c</fullName>
        <label>Income Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accessory Unit Income</fullName>
                </value>
                <value>
                    <fullName>Alimony/Child Support Income</fullName>
                </value>
                <value>
                    <fullName>Automobile Expense Amount</fullName>
                </value>
                <value>
                    <fullName>Boarder Income</fullName>
                </value>
                <value>
                    <fullName>Capital Gains</fullName>
                </value>
                <value>
                    <fullName>Disability Income</fullName>
                </value>
                <value>
                    <fullName>Employment Related Assets</fullName>
                </value>
                <value>
                    <fullName>Foreign Income</fullName>
                </value>
                <value>
                    <fullName>Foster Care</fullName>
                </value>
                <value>
                    <fullName>Housing Choice Voucher (Sec 8)</fullName>
                </value>
                <value>
                    <fullName>Military Base Pay</fullName>
                </value>
                <value>
                    <fullName>Military Clothes Allowance</fullName>
                </value>
                <value>
                    <fullName>Military Combat Pay</fullName>
                </value>
                <value>
                    <fullName>Military Flight Pay</fullName>
                </value>
                <value>
                    <fullName>Military Hazard Pay</fullName>
                </value>
                <value>
                    <fullName>Military Overseas Pay</fullName>
                </value>
                <value>
                    <fullName>Military Prop Pay</fullName>
                </value>
                <value>
                    <fullName>Military Quarters Allowance</fullName>
                </value>
                <value>
                    <fullName>Military Rations Allowance</fullName>
                </value>
                <value>
                    <fullName>Military Variable Housing Allowance</fullName>
                </value>
                <value>
                    <fullName>Mortgage Credit Certificate</fullName>
                </value>
                <value>
                    <fullName>Mortgage Differential</fullName>
                </value>
                <value>
                    <fullName>Non-Borrower Household Income</fullName>
                </value>
                <value>
                    <fullName>Notes Receivable/Installment</fullName>
                </value>
                <value>
                    <fullName>Other Type Of Income</fullName>
                </value>
                <value>
                    <fullName>Royalty Payment</fullName>
                </value>
                <value>
                    <fullName>Seasonal Income</fullName>
                </value>
                <value>
                    <fullName>Subject Property Net Cash Flow</fullName>
                </value>
                <value>
                    <fullName>Temporary Leave Income</fullName>
                </value>
                <value>
                    <fullName>Tip Income</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Income</label><nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Incomes</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/SAL_NewIncomeController.cls
public with sharing class SAL_NewIncomeController {
    @AuraEnabled
    public static List <Client__c> getclientValue(string LoanId) {
        return GenericController.getAllClientList(LoanId);
    }    
    
     @AuraEnabled
    public static Loan_New__c  Income_TabsValidatedData(string RecordId) 
    {    
        Loan_New__c objLoan = new Loan_New__c();  
        try
        { 
            objLoan  = GenericController.TabsData(RecordId);
            
        }
        catch(Exception ex)
        {
            system.debug(' Income_TabsValidatedData----Exception---'+ex);
        }
        return objLoan;
    }  
     @AuraEnabled
    public static Income_New__c  getOneIncome(string IncomeId) {
        Income_New__c objIncome= new Income_New__c();
        try
        {
          objIncome = [SELECT Id,Income_Source__c,Income_Types__c,Income_Value__c,RelatedClient__c,Related_Loan__c
                               FROM Income_New__c where Id= : IncomeId and IsActive__c =: true];  
        }
        catch(Exception ex)
        {
            system.debug(' getOneIncome----Exception---'+ex);
        }
        return objIncome;
    }
    @AuraEnabled
    public static decimal getAllIncome(string LoanId) {
        List<AggregateResult> results = new List<AggregateResult>();
        List<AggregateResult> resultsEmp = new List<AggregateResult>();
        decimal IncomeTotal=0.00;
        decimal EmpTotal=0.00;
        try
        {
            results = [SELECT Related_Loan__c,
                     sum(Income_Value__c) FROM Income_New__c where Related_Loan__c= : LoanId and IsActive__c = true group by Related_Loan__c];
            resultsEmp = [SELECT RelatedLoan__c,
                          sum(IncomeValue__c) FROM Employment__c where RelatedLoan__c= : LoanId and is_Active__c = true group by RelatedLoan__c];
            if(!results.isEmpty())
            {
                IncomeTotal = ((decimal)results[0].get('expr0')==null?0:(decimal)results[0].get('expr0'));   
            }
            else
            {
                IncomeTotal=0.00;   
            }
            if(!resultsEmp.isEmpty())
            {
                EmpTotal = ((decimal)resultsEmp[0].get('expr0')==null?0:(decimal)resultsEmp[0].get('expr0'));   
            }
            else
            {
                EmpTotal=0.00;   
            }
                                   
                                   
        }
        catch(Exception ex)
        {
            system.debug(' getAllIncome----Exception---'+ex);
        }
        return IncomeTotal+EmpTotal;
    }
    @AuraEnabled
    public static void incomesave(Income_New__c ObjIncome, string ClientId,string LoanId) {
        Loan_New__c loanObj = new Loan_New__c();
        try
        {
            ObjIncome.IsActive__c = true;
            ObjIncome.RelatedClient__c = ClientId;
            ObjIncome.Related_Loan__c = LoanId;
            ObjIncome.Is_Income_Validated__c=true; 
            upsert ObjIncome;
            GenericController.UpdateIncomeFlag(LoanId);
            GenericController.UpdateEmploymentFlag(LoanId);
        }    
        catch(Exception ex)
        {
            system.debug(' incomesave----Exception---'+ex);
        }
    } 
    @AuraEnabled
    public static void DeleteIncome(String RecordId) {
        Income_New__c objIncome = new Income_New__c();
        try
        {
            objIncome= [Select Id,Income_Value__c from Income_New__c where Id = :RecordId];
            objIncome.isActive__c=false;
            objIncome.Income_Value__c=0.00;
            upsert ObjIncome;
             String loanID=[select Related_Loan__c from Income_New__c where id=:RecordId limit 1].Related_Loan__c;       
             GenericController.UpdateIncomeFlagAfterDelete(loanID);
              GenericController.UpdateEmploymentFlagAfterDelete(loanID);
            
        }    
        catch(Exception ex)
        {
            system.debug(' DeleteIncome----Exception---'+ex);
        }
    } 
    @AuraEnabled
    public static  void  SaveEmployment(Employment__c objEmp,string ClientId,string LoanId) 
    {
        try
        {
            objEmp.Client_id__c =ClientId;
            objEmp.is_Active__c = true;
            objEmp.RelatedLoan__c=LoanId;
            objEmp.Is_Employment_Validated__c=true;
        }
        catch(Exception ex)
        {
            system.debug(' SaveEmployment----Exception---'+ex);
        }
        upsert objEmp;
        GenericController.UpdateIncomeFlag(LoanId);
        GenericController.UpdateEmploymentFlag(LoanId);
    }
    @AuraEnabled
    public static void DeleteEmployment(String RecordId) {
        Employment__c objEmp = new Employment__c();
        try
        {
            objEmp= [Select Id,IncomeValue__c from Employment__c where Id = :RecordId];
            objEmp.is_Active__c=false;
            objEmp.IncomeValue__c=0.00;
            upsert objEmp;
             String loanID=[select RelatedLoan__c from Employment__c where id=:RecordId limit 1].RelatedLoan__c;
                GenericController.UpdateIncomeFlagAfterDelete(loanID);
              GenericController.UpdateEmploymentFlagAfterDelete(loanID);
        }    
        catch(Exception ex)
        {
            system.debug(' DeleteEmployment----Exception---'+ex);
        }
    }
    @AuraEnabled
    public static Employment__c  getEmploymentById(string RecordId) {
        Employment__c objEmp = new Employment__c(); 
        try
        {    
            objEmp = [SELECT Id, EmployerName__c, EmployerPhone__c, Zip__c, State__c, City__c, PositionTitle__c,
                     EmployerAddress__c,Income_Type__c ,YearEmployedinProfession__c,
                     IncomeCategory__c,IncomeValue__c,Years__c, Months__c,Client_id__c FROM Employment__c  
                      where Id=: RecordId];
        }
        catch(Exception ex)
        {
            system.debug(' getEmploymentById----Exception---'+ex);
        }
        return objEmp;
    }
    
      @AuraEnabled
    public static List<IncomeEmpResponse> getAllIncomeEmp(String LoanID)
    {
        List<IncomeEmpResponse> mainReslist=new List<IncomeEmpResponse>();
        //IncomeEmpResponse mainRes=new IncomeEmpResponse();
        List<Client__c> clientObj= new List<Client__c>();
        clientObj=GenericController.getAllClientList(LoanID);
         map<id,list<IncomeEmpListResponse>> MapIncomeEmpList=new  map<id,list<IncomeEmpListResponse>>();
          MapIncomeEmpList=GetClient_IncomeEmpList(LoanID);
        for(Client__c obj :clientObj){
            
            IncomeEmpResponse objRes=new IncomeEmpResponse();
            list<IncomeEmpListResponse> iel=new list<IncomeEmpListResponse>();
            iel=MapIncomeEmpList.get(obj.id);
            
            objRes.ClientId=obj.Id;
            objRes.ClientName=obj.Name;
            objRes.IncomeEmpList=iel;
           
            objRes.TotalIncome=getClient_IncomeEmp(obj.id);
           mainReslist.add(objRes);
        }
       return mainReslist;
    }
     @AuraEnabled
    public static map<id,list<IncomeEmpListResponse>> GetClient_IncomeEmpList(string LoanId)
    {
        map<id,list<IncomeEmpListResponse>> conIncomeEmpMap= new map<id,list<IncomeEmpListResponse>>();
        list<IncomeEmpListResponse> ResList =new list<IncomeEmpListResponse> ();
        List <Income_New__c> listOfIncome =new List <Income_New__c>(); 
        List <Employment__c> listOfEmployment =new List <Employment__c>(); 
        
        
        listOfIncome = [SELECT Id,Is_Income_Validated__c,Income_Source__c,Income_Types__c,Income_Value__c,RelatedClient__c,Related_Loan__c
                        FROM Income_New__c where Related_Loan__c= : LoanId and IsActive__c =: true];
        if(!listOfIncome.isEmpty())
        {
            for(Income_New__c obj :listOfIncome)
            {
                IncomeEmpListResponse ResIncome = new IncomeEmpListResponse();
                ResIncome.ClientId=obj.RelatedClient__c;
                ResIncome.IncomeType = obj.Income_Types__c;
                ResIncome.SourceName = obj.Income_Source__c;
                ResIncome.MonthlyIncomeValue = obj.Income_Value__c;
                ResIncome.IsValidated=obj.Is_Income_Validated__c;
                ResIncome.RecordID = obj.Id;
                ResIncome.ObjectType = 'Income';
                ResList.add(ResIncome);
            }   
        }
        
        listOfEmployment = [SELECT Id,IncomeCategory__c,Is_Employment_Validated__c,Income_Type__c   ,IncomeValue__c,Client_id__c,RelatedLoan__c
                            ,EmployerName__c FROM Employment__c where RelatedLoan__c= : LoanId
                            and is_Active__c =: true]; 
        if(!listOfEmployment.isEmpty())
        {
            for(Employment__c obj :listOfEmployment)
            {
                IncomeEmpListResponse ResEmployment = new IncomeEmpListResponse();
                ResEmployment.ClientId=obj.Client_id__c;
                ResEmployment.IncomeType = obj.Income_Type__c;
                ResEmployment.SourceName = obj.EmployerName__c;
                ResEmployment.IsValidated=obj.Is_Employment_Validated__c;
                ResEmployment.MonthlyIncomeValue = obj.IncomeValue__c;
                ResEmployment.RecordID = obj.Id;
                ResEmployment.ObjectType = 'Employment';
                ResList.add(ResEmployment);
            }    
        }        
        
        for(IncomeEmpListResponse resObj:ResList)
        {
            List<IncomeEmpListResponse> l = conIncomeEmpMap.get(resObj.ClientId);
            if (l == null) {
                l = new List<IncomeEmpListResponse>();
                conIncomeEmpMap.put(resObj.ClientId, l);
            }
            l.add(resObj);   
        }
        system.debug('conIncomeEmpMap'+conIncomeEmpMap);
        return conIncomeEmpMap;        
    }
     @AuraEnabled
    public static decimal getClient_IncomeEmp(string ClientId) {
        List<AggregateResult> results = new List<AggregateResult>();
        List<AggregateResult> resultsEmp = new List<AggregateResult>();
        decimal IncomeTotal=0.00;
        decimal EmpTotal=0.00;
        try
        {
            results = [SELECT RelatedClient__c,
                     sum(Income_Value__c) FROM Income_New__c where RelatedClient__c= : ClientId and IsActive__c = true group by RelatedClient__c];
            resultsEmp = [SELECT Client_id__c,
                          sum(IncomeValue__c) FROM Employment__c where Client_id__c= : ClientId and is_Active__c = true group by Client_id__c];
            
            if(!results.isEmpty())
            {
                IncomeTotal = ((decimal)results[0].get('expr0')==null?0:(decimal)results[0].get('expr0'));    
            }
            else
            {
                IncomeTotal=0.00;    
            }
            if(!resultsEmp.isEmpty())
            {
                EmpTotal = ((decimal)resultsEmp[0].get('expr0')==null?0:(decimal)resultsEmp[0].get('expr0'));    
            }
            else
            {
                EmpTotal=0.00;    
            }
                                   
                                   
        }
        catch(Exception ex)
        {
            system.debug(' getClient_IncomeEmp----Exception---'+ex);
        }       
        return IncomeTotal+EmpTotal;
    }
}