src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Cannot be the Future date</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
  <sharingModel>ReadWriteTransfer</sharingModel>

</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>PartnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/Get_portalUsers.cls
public class Get_portalUsers {

    @AuraEnabled
    Public Static list<user> get_portalUsers(){
        
        return [select id,Name from user where ContactId !=null];
    }
    
      @AuraEnabled
    Public Static void shareto_portalUsers(String cid,String recId){
       // Scenario__Share SS = new Scenario__Share();
        Scenario__c sn = [select id,OwnerId from Scenario__c where id=: recId];
        user u = [ select id from user where contactId=:cid];
        sn.OwnerId = u.id;
        update sn;
       // return [select id,Name from user where ContactId !=null];
    }
        
    @AuraEnabled
    public static List < Account > fetchAccount(String searchKeyWord) {
        
        System.debug('searchKeyWord '+searchKeyWord);
        String searchKey = searchKeyWord + '%';
        List <Account> returnList = new List < Account > ();
        try{
           // List <Client__c> lstOfAccount = [select Name, Id, Last_Name__c, State__c, Zip__c, Email_Optional__c,PartnerID__c,Phone_Number__c,Street_Address__c,DOB__c from Client__c where Name LIKE: searchKey and is_Active__c=true];
         // Id Lead_rec_id = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Loan Lead').getRecordTypeId();
          //  system.debug(Lead_rec_id);and RecordTypeid=:Lead_rec_id
            System.debug('searchKey '+searchKey);
            
            
            List <Account> lstOfAccount = [select id,Name from Account where Name LIKE: searchKey];
            
            for (Account acc: lstOfAccount) {
                system.debug('__________>>>>>>>>>>><<<<<<<<<<<<<<<_________');
                system.debug(acc);
                returnList.add(acc);
            }
        }
        catch(exception e)
        {
            system.debug('fetchAccount--Exception---'+ e);
        }
        return returnList;
    }
    
    
    
    @AuraEnabled
    public static List < Contact > fetchContact(String searchKeyWord,String AccId) {
        
        System.debug('searchKeyWord '+searchKeyWord);
        String searchKey = searchKeyWord + '%';
        List <Contact> returnList = new List < Contact > ();
        list<String> ContactIds = new list<String>();
        map<String,contact> cons = new map<String,Contact>();
        try{
            
            
            List <Contact> lstOfContact = [select id,Name from Contact where Name LIKE: searchKey and AccountId=:AccId];
            
            for (Contact acc: lstOfContact) {
                system.debug('__________>>>>>>>>>>><<<<<<<<<<<<<<<_________');
                system.debug(acc);
              //  returnList.add(acc);
                ContactIds.add(acc.id);
                cons.put(acc.id,acc);
            }
            
            for(user u:[select id,ContactId from user where ContactId in:ContactIds]){
                returnList.add(cons.get(u.ContactId));
            }
        }
        catch(exception e)
        {
         //   system.debug('fetchAccount--Exception---'+ e);
        }
        return returnList;
    }
}