src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Declaration__c.object
<CustomObject><fields>
        <fullName>DeclarationClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Declarations</relationshipLabel>
        <relationshipName>Declarations</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>DeclarationLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Declarations</relationshipLabel>
        <relationshipName>Declarations</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>IsDeclaration_Filled_From_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Declaration Filled From Tab</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Declaration</label><nameField>
        <label>Declaration Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Declarations</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/getClientfromDeclaration.cls
public class getClientfromDeclaration {

@AuraEnabled
public static List<ClientDeclarationDetails> AllClientsName(string loanID)
{
    //nausad
    
     	List<ClientDeclarationDetails> declarationList= new  List<ClientDeclarationDetails>();
        List <Declaration__c> ClientDeclarations =new List <Declaration__c>();
        ClientDeclarations = [SELECT DeclarationClient__c,IsDeclaration_Filled_From_Tab__c FROM Declaration__c where DeclarationLoan__c = :loanID];
        for(Declaration__c obj:ClientDeclarations)
        {
            ClientDeclarationDetails Objdeclaration= new  ClientDeclarationDetails();
            Client__c clientObj=new Client__c() ;
            clientObj=[Select First_Name__c ,Last_Name__c from Client__c where id = :obj.DeclarationClient__c limit 1];
            Objdeclaration.ClientFirstName= clientObj.First_Name__c;
            Objdeclaration.ClientLastName=clientObj.Last_Name__c ;
            Objdeclaration.ClientDeclarationStatus=obj.IsDeclaration_Filled_From_Tab__c;
            declarationList.Add(Objdeclaration);
           // system.debug(Objdeclaration);
        }
        return declarationList;
}
    
   
}