src/objects/Client__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Income__c.object
<CustomObject>
    <fields>
        <fullName>Alimony_ChildSupport_Income__c</fullName>
        <label>Alimony/Child Support Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Automobile_Expense_Income__c</fullName>
        <label>Automobile/Expense Account Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Base_Employment_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Base Employment Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Boarder_Income__c</fullName>
        <label>Boarder Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bonus_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Bonus Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capital_Gains__c</fullName>
        <label>Capital Gains</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Commissions Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disability_Income__c</fullName>
        <label>Disability Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dividents_Interest_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Dividend/Interest Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Foster_Care_Income__c</fullName>
        <label>Foster Care</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Base_Pay__c</fullName>
        <label>Military Base Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Clothes_Allowance__c</fullName>
        <label>Military Clothes Allowance</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Combat_Pay__c</fullName>
        <label>Military Combat Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Flight_Pay__c</fullName>
        <label>Military Flight Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Hazard_Pay__c</fullName>
        <label>Military Hazard Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Overseas_Pay__c</fullName>
        <label>Military Overseas Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Prop_Pay__c</fullName>
        <label>Military Prop Pay</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Quarters_Allowance__c</fullName>
        <label>Military Quarters Allowance</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Rations_Allowance__c</fullName>
        <label>Military Rations Allowance</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Military_Variable_Housing_allowance__c</fullName>
        <label>Military Variable Housing allowance</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mortgage_Credit_Certificate__c</fullName>
        <label>Mortgage Credit Certificate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mortgage_Differential_Certificate__c</fullName>
        <label>Mortgage Differential</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Rental_Income__c</fullName>
        <description>Must be greater than Zero</description>
        <label>Net Rental Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes_Receivable_Installment__c</fullName>
        <label>Notes Receivable/Installment</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Income__c</fullName>
        <label>Other types of Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverTime_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Pension/Retirement Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pension_Retirement_Income__c</fullName>
        <label>Pension/Retirement Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RelatedClient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipName>Incomes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Loan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Loan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipName>Incomes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Social_Security_Disability_Income__c</fullName>
        <label>Social Security Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubjectProperty_Income__c</fullName>
        <label>Subject Property Net Cash Flow</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Temporary_Leave_income__c</fullName>
        <label>Temporary Leave income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trust_Income__c</fullName>
        <description>Must be greater than 0</description>
        <label>Trust Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unemployment_Welfare_Income__c</fullName>
        <label>Unemployment/Welfare Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VA_Benefits_non_education__c</fullName>
        <label>VA Benefits (non-education)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Income Old</label>
    <nameField>
        <displayFormat>IN-{00000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes Old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>IsIncomeFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field for income tab</description>
        <label>IsIncomeFilled_Flag_ForTab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Rental_Income__c</fullName>
        <label>Net Rental Income</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Sal_IncomeController.cls
public with sharing class Sal_IncomeController {
    @AuraEnabled
    public static List <Client__c> getclientValue(string LoanId) {
        return GenericController.getAllClientList(LoanId);
    }
    
    @AuraEnabled
    public static Income__c getIncomeData(string ClientId) {
        Income__c listOfLiability=new Income__c();
        try
        {
            listOfLiability = [SELECT Id,Bonus_Income__c,OverTime_Income__c,Commissions_Income__c,
                               Dividents_Interest_Income__c,Base_Employment_Income__c,Net_Rental_Income__c,Alimony_ChildSupport_Income__c,
                               Automobile_Expense_Income__c,Boarder_Income__c,Capital_Gains__c,Disability_Income__c,Foster_Care_Income__c,Military_Base_Pay__c,
                               Military_Clothes_Allowance__c,Military_Combat_Pay__c,Military_Flight_Pay__c,Military_Hazard_Pay__c,
                               Military_Overseas_Pay__c,Military_Prop_Pay__c,Military_Quarters_Allowance__c,Military_Rations_Allowance__c,
                               Military_Variable_Housing_allowance__c,Mortgage_Credit_Certificate__c,Mortgage_Differential_Certificate__c,
                               Notes_Receivable_Installment__c,Other_Income__c,Pension_Retirement_Income__c,Social_Security_Disability_Income__c,
                               SubjectProperty_Income__c,Temporary_Leave_income__c,Trust_Income__c,
                               Unemployment_Welfare_Income__c,VA_Benefits_non_education__c
                               
                               FROM Income__c where RelatedClient__c= : ClientId and isActive__c = true limit 1];
            
        }
        catch(Exception ex)
        {
            system.debug(' getIncomeData----Exception---'+ex);
        }
        return listOfLiability;
    }
    @AuraEnabled
    public static decimal getAllIncome(string LoanId) {
        List<AggregateResult> results = new List<AggregateResult>();
        decimal Dividents,BaseEmployment,Net_Rental,AlimonyChildSupport,AutomobileExpense,Boarder,Capital_Gain,Foster_Care,
            MBasePay,MClothesAllowance,MCombatPay,MFlightPay,MHazardPay,MOverseasPay,MPropPay,MQuartersAllowance,
            MRationsAllowance,MVariableHousing,MCredit,MDifferential,NotesReceivable,OtherIncome,Pension,SocialSecurity,
            SubjectProperty,Temporary_Leave,TrustIncome,Unemployment_Welfare,VA_Benefits,Disability_Income;
                
        decimal IncomeValue=0;
        try
        {
          results = [SELECT Related_Loan__c,
                          sum(Dividents_Interest_Income__c),sum(Base_Employment_Income__c),sum(Net_Rental_Income__c),
                          sum(Alimony_ChildSupport_Income__c),sum(Automobile_Expense_Income__c),sum(Boarder_Income__c),
                          sum(Capital_Gains__c),sum(Foster_Care_Income__c),sum(Military_Base_Pay__c),
                          sum(Military_Clothes_Allowance__c),sum(Military_Combat_Pay__c),sum(Military_Flight_Pay__c),
                          sum(Military_Hazard_Pay__c),sum(Military_Overseas_Pay__c),sum(Military_Prop_Pay__c),sum(Military_Quarters_Allowance__c),
                          sum(Military_Rations_Allowance__c),sum(Military_Variable_Housing_allowance__c),sum(Mortgage_Credit_Certificate__c),
                          sum(Mortgage_Differential_Certificate__c),sum(Notes_Receivable_Installment__c),sum(Other_Income__c),sum(Pension_Retirement_Income__c),
                          sum(Social_Security_Disability_Income__c),sum(SubjectProperty_Income__c),sum(Temporary_Leave_income__c),sum(Trust_Income__c),
                          sum(Unemployment_Welfare_Income__c),sum(VA_Benefits_non_education__c),sum(Disability_Income__c)
                               
  FROM Income__c where Related_Loan__c= : LoanId and isActive__c = true group by Related_Loan__c];
                              // FROM Income__c where Related_Loan__c= : LoanId and isActive__c = true group by Id ];
            
            
            Dividents = ((decimal)results[0].get('expr0')==null?0:(decimal)results[0].get('expr0'));
            BaseEmployment = ((decimal)results[0].get('expr1')==null?0:(decimal)results[0].get('expr1'));
            Net_Rental = ((decimal)results[0].get('expr2')==null?0:(decimal)results[0].get('expr2'));
            AlimonyChildSupport = ((decimal)results[0].get('expr3')==null?0:(decimal)results[0].get('expr3'));
            AutomobileExpense = ((decimal)results[0].get('expr4')==null?0:(decimal)results[0].get('expr4'));
            Boarder = ((decimal)results[0].get('expr5')==null?0:(decimal)results[0].get('expr5'));
            Capital_Gain = ((decimal)results[0].get('expr6')==null?0:(decimal)results[0].get('expr6'));            
            Foster_Care = ((decimal)results[0].get('expr7')==null?0:(decimal)results[0].get('expr7'));
            MBasePay = ((decimal)results[0].get('expr8')==null?0:(decimal)results[0].get('expr8'));
            MClothesAllowance = ((decimal)results[0].get('expr9')==null?0:(decimal)results[0].get('expr9'));
            MCombatPay = ((decimal)results[0].get('expr10')==null?0:(decimal)results[0].get('expr10'));
            MFlightPay = ((decimal)results[0].get('expr11')==null?0:(decimal)results[0].get('expr11'));
            MHazardPay = ((decimal)results[0].get('expr12')==null?0:(decimal)results[0].get('expr12'));
            MOverseasPay = ((decimal)results[0].get('expr13')==null?0:(decimal)results[0].get('expr13'));
            MPropPay = ((decimal)results[0].get('expr14')==null?0:(decimal)results[0].get('expr14'));
            MQuartersAllowance = ((decimal)results[0].get('expr15')==null?0:(decimal)results[0].get('expr15'));
            MRationsAllowance = ((decimal)results[0].get('expr16')==null?0:(decimal)results[0].get('expr16'));
            MVariableHousing = ((decimal)results[0].get('expr17')==null?0:(decimal)results[0].get('expr17'));
            MCredit = ((decimal)results[0].get('expr18')==null?0:(decimal)results[0].get('expr18'));
            MDifferential = ((decimal)results[0].get('expr19')==null?0:(decimal)results[0].get('expr19'));
            NotesReceivable = ((decimal)results[0].get('expr20')==null?0:(decimal)results[0].get('expr20'));
            OtherIncome = ((decimal)results[0].get('expr21')==null?0:(decimal)results[0].get('expr21'));
            Pension = ((decimal)results[0].get('expr22')==null?0:(decimal)results[0].get('expr22'));
            SocialSecurity = ((decimal)results[0].get('expr23')==null?0:(decimal)results[0].get('expr23'));
            SubjectProperty = ((decimal)results[0].get('expr24')==null?0:(decimal)results[0].get('expr24'));
            Temporary_Leave = ((decimal)results[0].get('expr25')==null?0:(decimal)results[0].get('expr25'));
            TrustIncome = ((decimal)results[0].get('expr26')==null?0:(decimal)results[0].get('expr26'));
            Unemployment_Welfare = ((decimal)results[0].get('expr27')==null?0:(decimal)results[0].get('expr27'));
            VA_Benefits = ((decimal)results[0].get('expr28')==null?0:(decimal)results[0].get('expr28'));
            Disability_Income = ((decimal)results[0].get('expr29')==null?0:(decimal)results[0].get('expr29'));
            
            IncomeValue = Dividents+BaseEmployment+Net_Rental+AlimonyChildSupport+AutomobileExpense+Boarder+Capital_Gain+
            Foster_Care+MBasePay+MClothesAllowance+MCombatPay+MFlightPay+MHazardPay+MOverseasPay+MPropPay+MQuartersAllowance+
            MRationsAllowance+MVariableHousing+MCredit+MDifferential+NotesReceivable+OtherIncome+Pension+SocialSecurity+
            SubjectProperty+Temporary_Leave+TrustIncome+Unemployment_Welfare+VA_Benefits+Disability_Income;
           
        }
        catch(Exception ex)
        {
            system.debug(' getAllIncome----Exception---'+ex);
        }
        return IncomeValue;
    }
    @AuraEnabled
    public static void incomesave(Income__c ObjIncome, string ClientId,string LoanId) {
        Loan_New__c loanObj = new Loan_New__c();
        try
        {
            ObjIncome.isActive__c = true;
            ObjIncome.RelatedClient__c = ClientId;
            ObjIncome.Related_Loan__c = LoanId;
            loanObj.Id=LoanId;
            loanObj.IsIncomeFilled_Flag__c=true;
            upsert ObjIncome;
            update loanObj;
        }    
        catch(Exception ex)
        {
            system.debug(' incomesave----Exception---'+ex);
        }
    } 
}