src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/ClientInfo__c.object
<CustomObject>
    <fields>
        <fullName>Email_Optional__c</fullName>
        <label>Client Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <label>Scenario Client</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Name</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Mortgage_Balance__c</fullName>
        <label>Current Mortgage Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Mortgage_Interest_Rate__c</fullName>
        <label>Current Mortgage Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Estimated_Home_Value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MIP__c</fullName>
        <label>MIP</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Mortgage_Payment__c</fullName>
        <label>Monthly Mortgage Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Limit__c</fullName>
        <label>Principal Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>is_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Converted</label>
        <type>Checkbox</type>
    </fields>
  <sharingModel>ReadWriteTransfer</sharingModel>

</CustomObject>

src/objects/Scenario__c.object
<CustomObject><fields>
        <fullName>BarChartResponse__c</fullName>
        <label>BarChartResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>CashFlow10__c</fullName>
        <label>CashFlow10</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>CashFlow1__c</fullName>
        <label>CashFlow1</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>CashFlow5__c</fullName>
        <label>CashFlow5</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Cash_at_close__c</fullName>
        <label>Cash at close</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Cash_to_close__c</fullName>
        <label>Cash to close</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>ClientInfo__c</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Client_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Current_Mortgage_Balance__c</fullName>
        <label>Current Mortgage Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Current_Mortgage_Interest_Rate__c</fullName>
        <label>Current Mortgage Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields><fields>
        <fullName>EOF__c</fullName>
        <label>EOF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Estimated_home_value__c</fullName>
        <label>Estimated Home Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Line_of_Credit__c</fullName>
        <label>Line of Credit</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>MIP__c</fullName>
        <label>MIP</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Monthly_Mortgage_Payment__c</fullName>
        <label>Monthly Mortgage Payment</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>PieChartResponse__c</fullName>
        <label>PieChartResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Principal_Limit__c</fullName>
        <label>Principal Limit</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>RateType__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adjust</fullName>
                    <label>ARM</label>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Scenario_Type__c</fullName>
        <label>Scenario Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FHA Traditional HECM</fullName>
                </value>
                <value>
                    <fullName>HECM for Purchase</fullName>
                </value>
                <value>
                    <fullName>Hecm</fullName>
                    <isActive>false</isActive>
                    <label>Hecm</label>
                </value>
                <value>
                    <fullName>Purchase</fullName>
                    <isActive>false</isActive>
                    <label>Purchase</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>is_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Converted</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Saved Scenario</label><nameField>
        <displayFormat>{0}</displayFormat>
        <label>ScenarioId</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Saved Scenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/classes/savedScenarioController.cls
/**
 * @description: used to fetch run scenario values and generate saved scenario results along with PieGraph 
 * @author: Ravi
 * @date: 9/13/2017
 *
 * changelog:
 * 07/19/2018: Sahitya - added new fields for Helo PieGraph(Other_Estimated_Closing_Costs__c,Origination_to_orm__c)
 */
public class savedScenarioController {
    
     public class AccWrap{
        @AuraEnabled
        public list<scenario__c> Acc{get;set;}
        @AuraEnabled
        public integer Count{get;set;}
        
        public AccWrap(list<scenario__c> Acc,integer Count){
            this.Acc = Acc;
            this.Count = Count;
        }
   
    }
 @AuraEnabled
    public static List < Lead > fetchAccount(String searchKeyWord) {
       return  lookUpController.fetchAccount(searchKeyWord);
      }
    
           @AuraEnabled
    public static AccWrap getScenarioList(String ClientID,String sort_Column,String sortorder ) {
         List < scenario__c > Scenariolist=new List < scenario__c >();
        try{
       
        Scenariolist=[select Id,is_Converted__c,Margin__c,Date_of_birth__c,Client_Lead__r.Street,Client_Lead__r.Phone,Client_Lead__r.FirstName,
                      Client_Lead__r.LastName,Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,
                      Estimated_home_value__c,CreatedDate,RateType__c,Other_Estimated_Closing_Costs__c,Origination_to_orm__c
                      from scenario__c  order by CreatedDate desc limit 10];            
        }
        catch(exception ex ){
            system.debug('--------------------getScenarioList------------------'+ex);
            Exception_log.Log_exception(ex,'savedScenarioController','getScenarioList');
        }
        //system.debug(Scenariolist);
       return  new AccWrap(Scenariolist,[select count() from scenario__c]);
      }
    
      @AuraEnabled
    public static AccWrap getScenario_nextPage(Integer pageNumber,String sort_Column,String sortorder){
        System.debug('pageNumber ===> '+pageNumber);
        integer pageNum = integer.valueOf(pageNumber);
        String  Query = 'select Id,is_Converted__c,Margin__c,Client_Lead__r.Email,Client_Lead__r.Phone,Client_Lead__r.Street,Date_of_birth__c,Client_Lead__r.FirstName,Client_Lead__r.LastName,Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,Estimated_home_value__c,Other_Estimated_Closing_Costs__c,Origination_to_orm__c,CreatedDate from scenario__c   ';
        Query+= ' order by '+sort_Column+' '+sortorder +' nulls last limit 10 offset '+pageNum;
   //     return [select id,Name from Account   limit 10 offset:pageNumber];
   //     //[select Id,is_Converted__c,Margin__c,Date_of_birth__c,Client_Lead__r.Street,Client_Lead__r.Phone,Client_Lead__r.FirstName,Client_Lead__r.LastName,Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,Estimated_home_value__c,CreatedDate
                //      from scenario__c  order by CreatedDate desc limit 10 offset:pageNum]
           return new AccWrap(database.query(Query),[select count() from scenario__c ]);

    }
      @AuraEnabled
    public static scenario__c  getScenarioData(String ScenarioID) {
      //prsn  
      scenario__c  Scenariodata=new scenario__c();
      system.debug('ScenarioID from getScenarioData --> '+ ScenarioID);
        try{
        Scenariodata=[select Id,RateType__c,is_Converted__c,Principal_Limit__c,
                      MIP__c,
                      Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,Estimated_home_value__c,Date_of_birth__c,
                      CreatedDate,piechartresponse__c,barchartresponse__c,Line_of_Credit__c,Index__c,Margin__c,Scenario_Type__c,CashFlow1__c,CashFlow10__c,
                      CashFlow5__c,Cash_at_close__c,Cash_to_close__c,EOF__c,Other_Estimated_Closing_Costs__c,Origination_to_orm__c
                      from scenario__c where id=:ScenarioID];
         }
        catch(exception ex ){
            system.debug('--------------------getScenarioData------------------'+ex);
            Exception_log.Log_exception(ex,'savedScenarioController','getScenarioData');
        }
       return  Scenariodata;
      }
     @AuraEnabled
    public static AccWrap getsearchScenarioList(String searchdata,String ClientID,integer pageNum,String sort_Column,String sortorder) {
         List < scenario__c > Scenariolist=new List < scenario__c >();
        System.debug('searchdata '+searchdata);
        search_content sdata= new search_content();
         sdata = (search_content)System.JSON.deserialize(searchdata, search_content.class);
        String Query = '';
        String baseQuery = '';
        try{
       //Query = 'select Id,ClientId__r.Email_Optional__c,ClientId__r.Phone_Number__c,ClientId__r.Street_Address__c,Date_of_birth__c,ClientId__r.Name,ClientId__r.Last_Name__c,Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,Estimated_home_value__c,CreatedDate from scenario__c  where ClientId__c=:ClientID and ';
       Query = 'select Id,is_Converted__c,Margin__c,Client_Lead__r.Email,Client_Lead__r.Phone,Client_Lead__r.Street,Date_of_birth__c,Client_Lead__r.FirstName,Client_Lead__r.LastName,Monthly_Mortgage_Payment__c,Current_Mortgage_Balance__c,Current_Mortgage_Interest_Rate__c,Estimated_home_value__c,Other_Estimated_Closing_Costs__c,Origination_to_orm__c,CreatedDate from scenario__c   ';
       
            if(sdata.FirstName!='' || sdata.LastName!='' || sdata.DOB!=null|| sdata.Email!='' || sdata.Phone!='' || sdata.Address!=''){
            Query+= ' where ';
            if(sdata.FirstName!=''){
                Query+= ' Client_Lead__r.FirstName = '+ '\''+sdata.FirstName+'\' and ';   
          }
            if(sdata.LastName!=''){
                Query+= ' Client_Lead__r.LastName = '+ '\''+sdata.LastName+'\' and ';   
          }
             if(sdata.Address!=''){     Query+= ' Client_Lead__r.Street = '+ '\''+sdata.Address+'\' and ';   
          }
              if(sdata.Phone!=''){
                Query+= '  Client_Lead__r.Phone = '+ '\''+sdata.Phone+'\' and ';   
          }
            
            if(sdata.DOB!=null){
                string dt = ''+sdata.DOB;
                
                Query+= '  Date_of_birth__c = '+dt.replace(' 00:00:00','')+' and ';   
          }
            
            if(sdata.Email !=''){
                
                Query+= ' Client_Lead__r.Email= '+ '\''+sdata.Email+'\' and ';
            }
            
            
            
        }
            Query = Query.removeEnd(' and ');
            baseQuery = Query;
            Query += ' order by '+sort_Column+' '+sortorder+' NULLS LAST limit 10 offset '+pageNum;
                        
                        //Query.removeEnd(' and ');

        }
        catch(exception ex ){
            system.debug('--------------------getScenarioList------------------'+ex);
            Exception_log.Log_exception(ex,'savedScenarioController','getsearchScenarioList');
        }
        system.debug('Query > '+Query);
         List < scenario__c > sce = database.query(Query);
       return  new AccWrap(sce,database.query(baseQuery).size());
      }
    
    
            @AuraEnabled
    public static search_content get_searchInstance(){
        
        return new search_content();
    }
    
    @AuraEnabled
    public static void SendMailTMP(id ScenarioID)
    {
        lookUpController.SendMailTMP(ScenarioID);
    }
    
    @AuraEnabled
    public static void Senariodelete(List<id> sel_sn){
    
        system.debug('parameter id value '+ sel_sn);
        scenario__c sn = [select id from scenario__c where id=:sel_sn limit 1];
        delete sn;
    }
}