src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Current State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Current Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Client</label><nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Clients</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>Employer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedClient</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmployerAddress__c</fullName>
        <label>EmployerAddress</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerName__c</fullName>
        <label>EmployerName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployerPhone__c</fullName>
        <description>Make a validation to make it a 10 digit number, doesn&apos;t start with 0, does not allow all same digits</description>
        <label>EmployerPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <description>Can&apos;t be less than 0</description>
        <label>Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PositionTitle__c</fullName>
        <label>Position/Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedLoan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedLoan</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Employer State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YearEmployedinProfession__c</fullName>
        <label>YearEmployedinProfession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Years__c</fullName>
        <description>Can&apos;t be  less than zero</description>
        <label>Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Employer Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know whether the record is active or not</description>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SAL_EmploymentController.cls
public class SAL_EmploymentController {
    
    @AuraEnabled
    public static List <Client__c> getclientValue(string LoanId) {
        return GenericController.getAllClientList(LoanId);
    }
    @AuraEnabled
    public static  void  SaveEmployment(Employment__c objEmp,string ClientId,string LoanId) 
    {
        try
        {
            objEmp.Client_id__c =ClientId;
            objEmp.is_Active__c = true;
            objEmp.RelatedLoan__c=LoanId;
        }
        catch(Exception ex)
        {
            system.debug(' SaveEmployment----Exception---'+ex);
        }
        upsert objEmp;
    }
    
    @AuraEnabled
    public static List <Employment__c> getEmployment(string ClientId) {
        List <Employment__c> objEmp =new List <Employment__c>(); 
        try
        {    
            objEmp = [SELECT Id, EmployerName__c, EmployerPhone__c, Zip__c, State__c, City__c, PositionTitle__c, EmployerAddress__c FROM Employment__c where is_Active__c = true and  Client_id__c=: ClientId];
        }
        catch(Exception ex)
        {
            system.debug(' getEmployment----Exception---'+ex);
        }
        return objEmp;
    }
    
    @AuraEnabled
    public static Employment__c  getEmploymentById(string RecordId) {
        Employment__c objEmp = new Employment__c(); 
        try
        {    
            objEmp = [SELECT Id, EmployerName__c, EmployerPhone__c, Zip__c, State__c, City__c, PositionTitle__c, EmployerAddress__c,YearEmployedinProfession__c,Years__c, Months__c FROM Employment__c  
                      where Id=: RecordId];
        }
        catch(Exception ex)
        {
            system.debug(' getEmploymentById----Exception---'+ex);
        }
        return objEmp;
    }
    
    @AuraEnabled
    public static  void DeleteEmployment(String RecordId)
    {
        Employment__c objEmpL = new Employment__c();
        String Emp_Id='';
        try
        {
            objEmpL = [Select Id,Name from Employment__c where Id =: RecordId];
            Emp_Id = objEmpL.Id;
        }
        catch(Exception ex)
        {
            system.debug(' DeleteEmployment----Exception---'+ex);
        }
        if (Emp_Id == RecordId)
        {
            objEmpL.is_Active__c = false;
            update objEmpL;
        }
    }
    
}