src/objects/Contact.object
<CustomObject><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel><recordTypes>
        <fullName>Banker</fullName>
        <active>true</active>
        <label>Banker</label>
    </recordTypes></CustomObject>

src/classes/SendContactEmailBachable_Test.cls
/**
 * @description: For sending Hot Transfer emails
 * @author: Sahitya
 * @date: 1/17/2018
 *
 */
@istest(SeeAllData=true)
class SendContactEmailBachable_Test{

   static testmethod void test() {                       
        Contact con = new Contact();            
        con.Lastname = 'testing1';
        con.Email = 'balasahityadeekonda@quickenloans1.com';
        con.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();                        
        con.Office_Phone__c = '1234567899';
        con.title__c = 'QL Banker';
        insert con; 

        System.Test.startTest();
        // batch test job
        Id batchJobId = Database.executeBatch(new SendContactEmail(), 200);  
        System.assertEquals(con.LastName, 'testing1');          
        System.Test.stopTest();
   }   
}