src/objects/Contact.object
<CustomObject><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel><recordTypes>
        <fullName>Banker</fullName>
        <active>true</active>
        <label>Banker</label>
    </recordTypes></CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ql_Banker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ql Banker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_Date__c</fullName>
        <label>Transfer Date</label>
        <type>Date</type>
    </fields>
  <sharingModel>ReadWriteTransfer</sharingModel>

    <recordTypes>
        <fullName>Banker</fullName>
        <active>true</active>
        <businessProcess>Banker</businessProcess>
        <label>Banker</label>
        
        
    </recordTypes>
</CustomObject>

src/classes/ContactController_test.cls
@isTest()
private class ContactController_test {

    static testMethod void mainTest() {
    
    Contact c = new contact();
    c.firstname = 'test';
    c.LastName = 'last';
    c.email = 'test@gmail.com';
    c.Office_Phone__c = '1111111111';
    c.title__c = 'QL Banker';
    c.recordtypeid = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
    insert c;
    
    Lead l = new Lead();
    l.lastName = 'asd';
    l.recordtypeid = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Banker').getRecordTypeId();    
    l.QL_banker__c  = c.id;        
    l.transfer_date__c = Date.newInstance(2016, 12, 9);
    l.Company = 'QL';
    l.Status = 'New';
    
    insert l;
    
    ContactController classObject = new ContactController();
    List<Lead> leadlist = new  List<Lead>();
    List<Lead> leadList3 = new List<Lead>(); 
    classObject.contactId = c.Id;
    
    leadlist=  classObject.getleads();
    leadlist= classObject.getleads2();
    leadlist= classObject.getleads3();
    Integer transfer = classObject.getTransfer();
    Integer closed = classObject.getClosed();
    Integer folder = classObject.getFolder();
    Integer money = classObject.getClosedMoney();
    Integer transfer2 = classObject.getTransfer2();
    Integer closed2 = classObject.getClosed2();
    Integer folder2 = classObject.getFolder2();
    Integer money2 = classObject.getClosedMoney2();    
    ContactController.recordWrapper wrapper = new ContactController.recordWrapper(c.id); //to test wrapper class
        
    }
}