src/objects/Contact_Us__c.object
<CustomObject><fields>
        <fullName>Contact_Detail__c</fullName>
        <label>Contact Detail</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Contact_Us_Sequence__c</fullName>
        <label>Contact Us Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>Contact Us</label><nameField>
        <label>ContactHeader</label>
        <type>Text</type>
    </nameField><pluralLabel>Contact Us</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/FAQ__c.object
<CustomObject><fields>
        <fullName>FAQ_Detail__c</fullName>
        <label>FAQ Detail</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>FAQ_Sequence__c</fullName>
        <label>FAQ Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>FAQ</label><nameField>
        <label>FAQ Header</label>
        <type>Text</type>
    </nameField><pluralLabel>FAQs</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/Process_Videos__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProcessVideoHeader__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>ProcessVideoHeader</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProcessVideoImage__c</fullName>
        <label>ProcessVideoImage</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ProcessVideoURL__c</fullName>
        <label>ProcessVideoURL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Process Video</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessContents__c.object
<CustomObject><fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>Html</type>
    </fields><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>ProcessContent</label><nameField>
        <label>Header</label>
        <type>Text</type>
    </nameField><pluralLabel>ProcessContents</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/ResourceForms__c.object
<CustomObject>
    <fields>
        <fullName>DetailText__c</fullName>
        <label>DetailText</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resource_Form_Sequence__c</fullName>
        <label>Resource Form Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ResourceForm</label>
    <nameField>
        <label>Header</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReverseVideoContents__c.object
<CustomObject><fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>Html</type>
    </fields><fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>ReverseContent</label><nameField>
        <label>Header</label>
        <type>Text</type>
    </nameField><pluralLabel>ReverseContents</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

src/objects/YoutubeLinks__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thumbnails_Image__c</fullName>
        <label>Thumbnails Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Video_sequence__c</fullName>
        <label>Video sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>YouTubeHeader__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>YouTube Header</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>YoutubeURL__c</fullName>
        <label>YoutubeURL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Reversity Video</label>
    <nameField>
        <displayFormat>YID-{0000}</displayFormat>
        <label>YID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reversity Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerResourcesController.cls
global with sharing class PartnerResourcesController {
	
    //Start Class
    //Reversity Tab
    //YoutubeVideoListController
	@AuraEnabled
    public static List<YoutubeLinks__c> getYoutubeLinks( ) {
        List<YoutubeLinks__c> Links = 
        [SELECT Id, Name, Thumbnails_Image__c,YouTubeHeader__c,YoutubeURL__c from YoutubeLinks__c where IsActive__c=true
            	order by Video_sequence__c asc]; 
      
        return Links;
    }
    
    @AuraEnabled
    public static string getYoutubeLinkDetailById(id recid) {
            
	 string  linkDetail  =  [SELECT YoutubeURL__c from YoutubeLinks__c 
                                       where Id=:recid ].YoutubeURL__c;
        
        //system.debug(linkdetail);
        return linkDetail;
         
    }
    //ReversityContentController
     @AuraEnabled
    public static List<ReverseVideoContents__c> getReversityContents( ) {
        List<ReverseVideoContents__c> lenderslink = 
                [SELECT Id, Name, Details__c from  ReverseVideoContents__c	 where IsActive__c = true
            	order by LastModifiedDate desc];

      
        return lenderslink;
    }
    //Our Process Tab
    //ProcessVideosListController
   @AuraEnabled
    public static List<Process_Videos__c> getProcessVideoLinks( ) {
        List<Process_Videos__c> Links = 
        [SELECT Id, Name, ProcessVideoImage__c,ProcessVideoHeader__c,ProcessVideoURL__c from Process_Videos__c where IsActive__c=true
            	order by LastModifiedDate desc];
      
        return Links;
    }
  
    @AuraEnabled
    public static string getProcessVideoLinksById(id recid) {
            
	 string  linkDetail  =  [SELECT ProcessVideoURL__c from Process_Videos__c 
                                       where Id=:recid ].ProcessVideoURL__c;
        
        return linkDetail;
         
    }
    //ProcessContentController
    @AuraEnabled
    public static List<ProcessContents__c> getProcessContents( ) {
        List<ProcessContents__c> lenderslink = 
                [SELECT Id, Name, Details__c from  ProcessContents__c	 where IsActive__c = true
            	order by LastModifiedDate desc];

      
        return lenderslink;
    }
    //Forms Tab
    //ResourceFormsController
    @AuraEnabled
    public static List<ResourceForms__c> getResourceForms( ) {
        List<ResourceForms__c> lenderslink = 
                [SELECT Id, Name, DetailText__c from  ResourceForms__c where IsActive__c = true
            	order by Resource_Form_Sequence__c asc];

      
        return lenderslink;
    }
    //FAQ Tab
    //FAQController
    @AuraEnabled
    public Static List<FAQ__c> getFAQContents( ) {
        List<FAQ__c> FAQs = 
                [SELECT Id, Name, FAQ_Detail__c from  FAQ__c where IsActive__c = true
                order by FAQ_Sequence__c asc];
            return FAQs;
    }
    //ContactUs Tab
    //ContactUSController
    @AuraEnabled
    public static List<Contact_Us__c> getContacts( ) {
        List<Contact_Us__c> Contacts = 
                [SELECT Id, Name, Contact_Detail__c from  Contact_Us__c where Is_Active__c = true
            	order by Contact_Us_Sequence__c asc];

      
        return Contacts;

    }
    
    /*@AuraEnabled
    public static List<Contact_Us_Right__c> getContactsRight( ) {
        List<Contact_Us_Right__c> ContactsR = 
                [SELECT Id, Name, Contact_Detail__c from  Contact_Us_Right__c where IsActive__c = true
            	order by Contact_Us_Sequence__c asc];

      
        return ContactsR;

    }*/
    //End Class

}