src/objects/Contact.object
<CustomObject><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>IsLoanContactFilled_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoanContactFilled_Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanOfficer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Officer*</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LoanOfficer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Processor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Portal Loan Processors</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Portal Loan Processor</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>ORM Partner</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>ORM Partners</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Processor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Type__c</fullName>
        <label>Preferred Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Loan Processor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Date</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SAL_LoanContactController.cls
public class SAL_LoanContactController {
    
         @AuraEnabled
    public static Loan_New__c  LoanContact_TabsValidatedData(string RecordId) 
    {    
        Loan_New__c objLoan = new Loan_New__c();  
        try
        { 
            objLoan  = GenericController.TabsData(RecordId);
            
        }
        catch(Exception ex)
        {
            system.debug(' LoanContact_TabsValidatedData----Exception---'+ex);
        }
        return objLoan;
    } 
    @AuraEnabled
    public static Loan_New__c GetLoanContactsById(id LoanID)
    {
        Loan_New__c LoanContacts=new  Loan_New__c();
        try
        {
            LoanContacts =  [SELECT  Name,LoanOfficer__c, Loan_Processor__c, Preferred_Contact_Type__c FROM Loan_New__c where id = : LoanId];
        }
        catch(Exception ex)
        {
            system.debug(' GetLoanContactsById----Exception---'+ex);
        }
        return LoanContacts;
    }
    
    @AuraEnabled
    public static String getUserId(id LoanID) {
        
        return  UserInfo.getUserId(); 
        //return '005q0000003QP0GAAW';
    }
    
    @AuraEnabled
    public static List<LoanOfficerResponse>  getLoanOfficerList() {
        List<Contact> Objcon = new List<Contact>();
        List<Contact> ObjConId = new List<Contact>();
        User MatchedUsers = new User();
        List<LoanOfficerResponse> ListLoanOfficer = New List<LoanOfficerResponse>();
        try
        {
            //id CUId = '00539000005aJctAAE'; //UserInfo.getUserId();
            //userId='00539000005aJctAAE';
            //Profile p = [SELECT Id FROM Profile WHERE Name='ORM Partners'];
            MatchedUsers = [select id, Name, contactId,AccountId,ProfileID from User where id = : userinfo.getUserId()];
            //Objcon = [Select Id,AccountId,Title__c,Name from Contact where AccountId=:u.AccountId and Title__c='Loan officer'];
            //ObjConId=[Select Id from Contact where AccountId=:u.AccountId and Title__c='Loan officer'];
            //MatchedUsers = [select Id, Name,contactId from User where contactId IN: ObjConId and IsActive = true];
            List<user> usrList=new List<user>();
            usrList= [select Id, Name from User where AccountId =: MatchedUsers.AccountId and ProfileID =:MatchedUsers.ProfileID and IsActive = true];
            //for(Contact Contactusr: Objcon){
            
            for(user usr : usrList){
                LoanOfficerResponse ObjLoanOfficer = New LoanOfficerResponse();
                //if(Contactusr.Id == usr.ContactId){ 
                ObjLoanOfficer.Id = usr.Id;
                ObjLoanOfficer.LoanofficerName=usr.Name;
                ListLoanOfficer.add(ObjLoanOfficer);
            }
            //}
        }
        
        catch(Exception ex)
        {
            system.debug(' ListLoanOfficer----Exception---' + ex);
        }
        return ListLoanOfficer;
    }
    
    @AuraEnabled
    public static List<LoanProcessorResponse>  getLoanProcessorList() {
        List<Contact> Objcon = new List<Contact>();
        List<Contact> ObjConId = new List<Contact>();
        User MatchedUsers = new User();
        List<User> UserList = new List<User>();
        List<LoanProcessorResponse> ListLoanProcessor = New List<LoanProcessorResponse>();
        try
        {
            id CUId = '00539000005aJctAAE'; //UserInfo.getUserId();
            //userId='00539000005aJctAAE'; 0013900001YLlLmAAL
            MatchedUsers = [select id, Name, contactId,AccountId from User where id = : userinfo.getUserId()];
            Profile p = [SELECT Id FROM Profile WHERE Name='Portal Loan Processors'];
            Profile p1 = [SELECT Id FROM Profile WHERE Name='Portal Loan Processor'];
         
            //MatchedUsers = [select id, Name, contactId,AccountId from User where id = : userinfo.getUserId() and 
            // IsActive = true];
            //Objcon = [Select Id,AccountId,Title__c,Name from Contact where AccountId=:u.AccountId and Title__c='Processor'];
            //ObjConId=[Select Id from Contact where AccountId=:u.AccountId and Title__c='Processor'];
            UserList = [select Id, Name from User where AccountId =: MatchedUsers.AccountId and (ProfileID =:p.Id or ProfileID =:p1.Id) and IsActive = true];
            //for(Contact Contactusr: Objcon){
            
            for(user usr : UserList){
                LoanProcessorResponse ObjLoanProcessor = New LoanProcessorResponse();
                //if(Contactusr.Id == usr.ContactId){                         
                ObjLoanProcessor.Id = usr.Id;
                ObjLoanProcessor.LoanProcessorName=usr.Name;
                ListLoanProcessor.add(ObjLoanProcessor);                         
                //}
                
                
                //}
                
            }
        }
        catch(Exception ex)
        {
            system.debug(' ListLoanProcessor----Exception---' + ex);
        }
        return ListLoanProcessor;
    }
    
    //Save Asset(Insert/Update)
    @AuraEnabled
    public static integer SavePreferredContact(string LO,string LP,string PC,string LoanID) {
        integer i =0;
        try{
            Loan_new__c objloan=new loan_new__c();
            objloan.Id=LoanID;
            objloan.LoanOfficer__c =LO;
            objloan.Loan_Processor__c =   LP; 
            objloan.Preferred_Contact_Type__c = PC;
            objloan.IsLoanContactFilled_Flag__c=true;
            upsert objloan;
            i=1;
        }
        catch(Exception ex)
        {
            system.debug(' SavePreferredContact-'+ex);
            i=0;
        }
        return i;
    }
   
}