src/objects/Contact.object
<CustomObject><fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processor</fullName>
                </value>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Market</fullName>
                </value>
                <value>
                    <fullName>Post close contact</fullName>
                </value>
                <value>
                    <fullName>Assistant Loan Officer</fullName>
                </value>
                <value>
                    <fullName>Processing manager</fullName>
                </value>
                <value>
                    <fullName>Third party closer</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>QL Banker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><externalSharingModel>ControlledByParent</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ControlledByParent</sharingModel><recordTypes>
        <fullName>Banker</fullName>
        <active>true</active>
        <label>Banker</label>
    </recordTypes></CustomObject>

src/classes/SendContactEmailScheduler_Test.cls
@istest(SeeAllData=false)
class SendContactEmailScheduler_Test{

   static testmethod void test() {
        System.Test.startTest();
            Contact con = new Contact();
            con.Lastname = 'testing';
            con.Email = 'balasahityadeekonda@quickenloans.com';
          // con.recordtypeId = '012290000004a86';
            con.recordtypeid = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
   
            con.Office_Phone__c = '1234567899';
            con.Title__c = 'QL Banker';
            insert con;


            // Schedule the test job
            SendContactEmailScheduler sh1 = new SendContactEmailScheduler ();
            String sch = '0 0 23 * * ?'; 
            system.schedule('SendContactEmailScheduler_test', sch, sh1); 

           // System.assertNullEquals(0, jobId);
            SendContactEmail sc =  new SendContactEmail();
       Database.executeBatch(sc, 200);
       sc.execute(null,[select id,Email from contact ]);

       System.Test.stopTest();
       
     
   }
}