src/objects/Daily_Product_Rate__c.object
<CustomObject>
    <description>Update daily rates by product.  Updates here sent to Baydocs.</description>
    <fields>
        <fullName>Product_Rate_Type__c</fullName>
        <description>product rate type</description>
        <label>Product Rate Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HELO-LIBOR</fullName>
                </value>
                <value>
                    <fullName>HELO-BrokerComp</fullName>
                    <label>HELO-Broker Comp</label>
                </value>
                <value>
                    <fullName>HELO-OrigFee</fullName>
                    <label>HELO-Origination Fee</label>
                </value>
                <value>
                    <fullName>HELO-ORIGINATION</fullName>
                    <isActive>false</isActive>
                    <label>HELO-ORIGINATION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Date__c</fullName>
        <description>Date this rate is valid for</description>
        <label>Rate Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <label>Daily Product Rate</label>
    <nameField>
        <displayFormat>{0}-{YYYY}{MM}{DD}</displayFormat>
        <label>Product Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Product Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DailyProductRateUpdateCalloutTest.cls
//Test daily product rate update code that is typically called by DailyProductRate trigger
@IsTest
private class DailyProductRateUpdateCalloutTest {
    private class DailyProductRateUpdateCalloutTestGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
//        // Optionally, only send a mock response for a specific endpoint
//        // and method.
//        System.assertEquals('http://example.com/example/test', req.getEndpoint());
//        System.assertEquals('GET', req.getMethod());

            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }

    @IsTest
    static void testCallout() {
        Test.setMock(HttpCalloutMock.class, new DailyProductRateUpdateCalloutTestGenerator());

        Id profileId = TestUtils.getProfileId('System Administrator');
        Id userRoleId = TestUtils.getRoleId('System Administrator');
        User testUser = (User) TestFactory.createSObject(new User(ProfileId = profileId, UserRoleId = userRoleId), 'TestFactory.UserDefaults');
        Database.insert(testUser);

        System.runAs(testUser) {
            Daily_Product_Rate__c dpr = new Daily_Product_Rate__c(
                    Product_Rate_Type__c = 'HELO-LIBOR',
                    Rate__c = 3.01,
                    Rate_Date__c = Date.newInstance(2018, 2, 17)
            );
            Test.startTest();
            Database.insert(dpr); //the insert causes DailyProductRate trigger to fire, which inherently tests DailyProductRateUpdateCallout.makeCallout()
            Test.stopTest();
        }
    }
}