src/objects/Daily_Product_Rate__c.object
<CustomObject>
    <description>Update daily rates by product.  Updates here sent to Baydocs.</description>
    <fields>
        <fullName>Processed__c</fullName>
        <description>Has the rate been processed (ex:</description>
        <label>Processed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Type__c</fullName>
        <description>product rate type</description>
        <label>Product Rate Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HELO-LIBOR</fullName>
                </value>
                <value>
                    <fullName>HELO-BrokerComp</fullName>
                    <label>HELO-Broker Comp</label>
                </value>
                <value>
                    <fullName>HELO-OrigFee</fullName>
                    <label>HELO-Origination Fee</label>
                </value>
                <value>
                    <fullName>HELO-ORIGINATION</fullName>
                    <isActive>false</isActive>
                    <label>HELO-ORIGINATION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Date__c</fullName>
        <description>Date this rate is valid for</description>
        <label>Rate Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <label>Daily Product Rate</label>
    <nameField>
        <displayFormat>{0}-{YYYY}{MM}{DD}</displayFormat>
        <label>Product Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Product Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceRegistry__mdt.object
<CustomObject>
    <description>Entries represent control parameters for External Services.  Referenced by the ServiceName__c field of ExternalService__c records, and used within ExternalServiceDispatcher.cls</description>
    <fields>
        <fullName>NamedCredential__c</fullName>
        <description>The Named Credential connection parameters to use for this External Service.</description>
        <inlineHelpText>The Named Credential connection parameters to use for this External Service.</inlineHelpText>
        <label>Named Credential</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>ExternalServiceRegistry</label>
    <pluralLabel>ExternalServiceRegistries</pluralLabel>
</CustomObject>

src/classes/DailyProductRateUpdateCallout.cls
/**
* @description Update Helo product Index, Broker Comp, Originations to BayDocs
* @author Bala
* @date 8/30/2018
* @changlog 
* Bala 8/28/2019 - Added new libor rate for HELO ARM
*/
public with sharing class DailyProductRateUpdateCallout {
    @future(callout=true)
    public static void makeCallout(String productRateAsJson) {
        Daily_Product_Rate__c pr = (Daily_Product_Rate__c) JSON.deserialize(productRateAsJson, Daily_Product_Rate__c.class);

        system.debug('DailyProductRateUpdateCallout got Product_Rate_Type_c: ' + pr.Product_Rate_Type__c);

        system.debug('looking up BaydocsProductRateUpdate ExternalServiceRegistry__mdt entry');

        ExternalServiceRegistry__mdt[] esrEntries = [select NamedCredential__c, password__c,username__c from ExternalServiceRegistry__mdt where DeveloperName = 'BaydocsProductRateUpdate' limit 1];

        system.debug(esrEntries);

        if (esrEntries.size() != 1) {
            system.debug(LoggingLevel.ERROR, 'No ExternalServiceRegistry entry for BaydocsProductRateUpdate');
            return;
        }

        DateTime rateDateTime = DateTime.newInstance(pr.Rate_Date__c, Time.newInstance(0, 0, 0, 0));
        String rateDateS = rateDateTime.format('yyyy-MM-dd');

        JSONGenerator gen = JSON.createGenerator(true);
        String endpoint;

        HttpRequest request = new HttpRequest();
        if ('HELO-LIBOR' == pr.Product_Rate_Type__c) {
            String namedCredential = esrEntries[0].NamedCredential__c;

            endpoint = 'callout:' + namedCredential + '/app/lib/integration/OneReverse/HELO/UpdateLIBORswap/index.php';
            gen.writeStartObject();
            gen.writeStringField('UserCode', esrEntries[0].username__c);
            gen.writeStringField('PassCode', esrEntries[0].password__c);
            gen.writeStringField('DateFormat', 'Y-m-d');
            gen.writeStringField('RateDate', rateDateS);//'2018-08-01');
            gen.writeStringField('IndexValue', pr.Rate__c.toPlainString());
            gen.writeEndObject();
        } else if ('HELO-BrokerComp' == pr.Product_Rate_Type__c) {
            String namedCredential = esrEntries[0].NamedCredential__c;

            endpoint = 'callout:' + namedCredential + '/app/lib/integration/OneReverse/HELO/UpdateBrokerComp/index.php';
            gen.writeStartObject();
            gen.writeStringField('UserCode', esrEntries[0].username__c);
            gen.writeStringField('PassCode', esrEntries[0].password__c);
            gen.writeStringField('DateFormat', 'Y-m-d');
            gen.writeStringField('EffectiveDate', rateDateS);//'2018-08-01');
            gen.writeStringField('BrokerPrice', pr.Rate__c.toPlainString());
            gen.writeEndObject();
        } else if ('HELO-OrigFee' == pr.Product_Rate_Type__c) {
            String namedCredential = esrEntries[0].NamedCredential__c;
            endpoint = 'callout:' + namedCredential + '/app/lib/integration/OneReverse/HELO/UpdateOrigFee/index.php';
            gen.writeStartObject();
            gen.writeStringField('UserCode', esrEntries[0].username__c);
            gen.writeStringField('PassCode', esrEntries[0].password__c);
            gen.writeStringField('DateFormat', 'Y-m-d');
            gen.writeStringField('EffectiveDate', rateDateS);//'2018-08-01');
            gen.writeStringField('OrigFeeMargin1', pr.RateMargin1__c.toPlainString());
            gen.writeStringField('OrigFeeMargin2', pr.RateMargin2__c.toPlainString());
            gen.writeStringField('OrigFeeMargin3', pr.RateMargin3__c.toPlainString());
            gen.writeEndObject();
        } else if('HELO-ARM-INDEX' == pr.Product_Rate_Type__c){
            String namedCredential = esrEntries[0].NamedCredential__c;
            endpoint = 'callout:' + namedCredential + '/app/lib/integration/OneReverse/HELO/UpdateLIBORmonthly/index.php';
            gen.writeStartObject();
            gen.writeStringField('UserCode', esrEntries[0].username__c);
            gen.writeStringField('PassCode', esrEntries[0].password__c);
            gen.writeStringField('DateFormat', 'Y-m-d');
            gen.writeStringField('RateDate', rateDateS);//'2018-08-01');
            gen.writeStringField('IndexValue', pr.Rate__c.toPlainString());
            gen.writeEndObject();
        } else {
            system.debug(LoggingLevel.ERROR, 'Invalid daily product rate type type: ' + pr.Product_Rate_Type__c);
            return;
        }

        String jsonS = gen.getAsString();

        request.setEndPoint(endpoint);
        request.setMethod('POST');
        request.setBody(jsonS);

        system.debug('POSTing: ' + jsonS);
        HttpResponse res = new HTTP().send(request);

        if (200 != res.getStatusCode()) {
            system.debug(LoggingLevel.ERROR, 'ERROR calling baydocs to update product rate');
        } else {
            pr.Processed__c = DateTime.now();
            update pr;
        }

        system.debug(res.toString());
        system.debug(res.getBody());
    }
}