src/objects/EnglishChannelConfig__c.object
<CustomObject><fields>
        <fullName>ApiGatewayEndpoint__c</fullName>
        <description>The endpoint (url) for the english channel API gateway.</description>
        <label>ApiGatewayEndpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields><customSettingsType>Hierarchy</customSettingsType><description>English channel configuration.</description><enableFeeds>false</enableFeeds><label>English Channel Config</label><visibility>Public</visibility></CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>BayDocsOrderNumber__c</fullName>
        <label>BayDocsOrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/EnglishChannelClient.cls
/**
 * @description EnglishChannelClient - Orchestrate Callout to Baydocs for App Package Requests
 * @author GalaxE (Original Author)
 * @date 13th June 2018 (Updated by Mike)
 *
 * @changelog MG SFDC-226 Updates to support not saving Attachment back into SFDC
 *
 * @todo    MG Code review & tidy - In progress (02/08/2018)
 *          MG Compare and Merge with other DevSandbox before deploying to Partial/Prod
 */
global class EnglishChannelClient {

    /**
     * @description Invoke future call for sending payload to Baydocs
     *
     * @param eventName
     * @param eventPayload
     * @param loanId Salesforce Id of the Loan
     */
    public static void sendEvent(String eventName, Object eventPayload, String loanId) {
        Logger.push('sendEvent', 'EnglishChannelClient');

        String body = JSON.serialize(new Event(eventName, eventPayload));

        try {
            send(JSON.serialize(eventPayload), loanId);
        } catch (Exception ex) {
            Logger.debugException(ex);
        }
        Logger.pop();
    }

    /**
     * @description Async future callout to Baydocs
     *
     * @param body
     * @param loanId
     */
    @future(callout=true)
    private static void send(String body, String loanId) {
        Logger.push('send', 'EnglishChannelClient');

        HttpRequest request = new HttpRequest();

        if (body != null) Logger.debug(body); // This is the JSON Log

        request.setEndpoint(EnglishChannelConfig__c.getOrgDefaults().ApiGatewayEndpoint__c); // @TODO MG Add null check
        Logger.debug('request setEndpoint '+ EnglishChannelConfig__c.getOrgDefaults().ApiGatewayEndpoint__c); // @TODO MG Move into CMT
        request.setMethod('POST');
        request.setBody(body);
        request.setTimeout(120000);

        Http http = new Http();
        HttpResponse response;
        if (!test.isRunningTest()) {

            response = http.send(request);// = http.send(request);
        }
        //Logger.debug('Response=' + response);


        
        String xmlstring = '';//response.getBody();

        if (!Test.isRunningTest()) {
            xmlstring = response.getBody();
        }
        else {
            // @TODO move into correct mocking framework
            xmlstring = '<?xml version="1.0" encoding="UTF-8"?> <response> <status>success</status> <OrderNumber>7082227</OrderNumber> <PdfStatus>OK</PdfStatus> <PdfCreateTimeInSecs></PdfCreateTimeInSecs> <LoanNumber>1</LoanNumber> <Files> <File BayDocsOrderNumber="7082227" PackageType="1" FormatType="PDF" NoDocTriggered="0" PackageFound="1"> <Document xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">asda</Document> </File> <File BayDocsOrderNumber="7082227" PackageType="421" FormatType="PDF" NoDocTriggered="0" PackageFound="1"> <Document xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">sfsdfdsf</Document> </File> </Files> </response>';

        }


        //Logger.debug('response.getBody() '+ response.getBody().substring(0, 131000));
		//saveAppPackageToLoan(loanId, xmlstring); // SFDC-226 Not required to be saved back into SFDC
        Logger.pop(); // Popping further up stack

      

    }

	/**
	*  Surplus to Requirements for now
	 * @description New method saveAppPackageToLoan (chunk down original method, could require further splitting out...)
	 * @param  loanId Salesforce record Id
	 * @param  xmlstring xml response from Baydocs containing base64 attachment
	 */
    private static void saveAppPackageToLoan(Id loanId, String xmlstring){
        Logger.push('saveAppPackageToLoan','EnglishChannelClient');
        /**
            @TODO Pending review by Mike
            @TODO Lift and shift into separate method
        */

        /*
        list< String> outxmlstring = new list< String>();
        string OrdNumber = '0';
        DOM.Document xmlDOC = new DOM.Document();
        xmlDOC.load(xmlstring);
        DOM.XMLNode rootElement = xmlDOC.getRootElement();
        //outxmlstring=String.valueof(xmlDOC.getRootElement().getName());
        for (DOM.XMLNode xmlnodeobj : xmlDOC.getRootElement().getChildElements()) {
            //   System.debug( xmlnodeobj.getName() );
            if (xmlnodeobj.getName() == 'OrderNumber') {
                OrdNumber = xmlnodeobj.getText();
            }
            if (xmlnodeobj.getName() == 'files') {

                //System.debug()
                for (DOM.XMLNode xmlnodeobjinner : xmlnodeobj.getChildElements()) {
                    if (xmlnodeobjinner.getName() == 'file') {
                        for (DOM.XMLNode Newxmlnodeobjinner : xmlnodeobjinner.getChildElements()) {
                            if (Newxmlnodeobjinner.getName() == 'document') {
                                //outxmlstring = Newxmlnodeobjinner.getText();

                                //      System.debug('outxmlstring '+outxmlstring);
                                outxmlstring.add(Newxmlnodeobjinner.getText());
                            }

                        }
                    } 

                }

            }
        }

		// @TODO MG/QDA combine into single query and save, possibly move into new method
        Loan_new__c ln = [select name,createdby.email,createdby.name,BayDocsOrderNumber__c from Loan_New__c where id = :loanId];
        
        try {
            ln.BayDocsOrderNumber__c = OrdNumber;

            // update ln; // @TODO MG/QDA commented out for dev testing
        } catch (exception ex) {
			Logger.debugException(ex);
        }

		List<Attachment> Atts = new List<Attachment>(); // empty list for new attachments

        if (!outxmlstring.isEmpty()) {

            
            
            // Add App Package PDF
			string base64Data = outxmlstring[0];//EncodingUtil.urlDecode(''+soapNS.getChildElement('File','').getChildElement('Document',''), 'UTF-8');
            Attachment a = new Attachment();
            a.parentId = loanId;
            a.Body = EncodingUtil.base64Decode(base64Data);
            a.Name = ln.name + '_' + System.now() + '_AppPackage.pdf';
            Atts.add(a);

            // Add Lender Package PDF 
            if (outxmlstring.size() == 2) {
			string base64Datanew = outxmlstring[1];//EncodingUtil.urlDecode(''+soapNS.getChildElement('File','').getChildElement('Document',''), 'UTF-8');
			Attachment a1 = new Attachment();
			a1.parentId = loanId;
			a1.Body = EncodingUtil.base64Decode(base64Datanew);
			a1.Name = ln.name + '_' + System.now() + '_LenderPackage.pdf';
			Atts.add(a1);
            }

			
        }

		try{
			Logger.debug('Saving Attachments ' + Atts.size());
			insert Atts;	
			} 
		catch (Exception ex){
			Logger.debugException(ex);
		}
            

        
        // @TODO MG/QDA need to combine with update on lin 126
        Loan_New__c lnstatus = [select loanstatus__c from loan_new__c where id = :loanId];
        lnstatus.LoanStatus__c = 'Waiting for Full Package';
        //update lnstatus; // @TODO MG/QDA commented out for dev testing
        */
        Logger.pop();


    }

    global class Event {
        public String eventName { get; set; }
        public Object eventPayload { get; set; }

        public Event(String eventName, Object eventPayload) {
            this.eventName = eventName;
            this.eventPayload = eventPayload;
        }
    }
}