src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <description>this field stores Class/Trigger Name</description>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_type__c</fullName>
        <label>Exception type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Error Log</label><nameField>
        <displayFormat>El-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Error Logs</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/Exception_log.cls
/***********
**Author : Ravi Kiran
**Version : 1.0
**Purpose : capture/Save the exceptions into 'Error Log' Object
**Modified By : Nausad on 01/15/2018
**Modified By : Ravi on 01/23/2018
************/

public with sharing class Exception_log{
    
    public static void Log_exception(Exception ex,String ClassName,String MethodName){
        
        Error_Log__c ec = new Error_Log__c();
        ec.Running_User__c = Userinfo.getUserId();
        ec.Exception_Message__c = ex.getMessage();
        ec.Exception_type__c = '';
        ec.Entity_Name__c = ClassName;
        ec.Action_Name__c = MethodName;
        Database.insert(ec,false);
        sendEmail(ec.id);
        
    }
    public static void Create_Custom_Logs(String  Message,String ClassName,String MethodName,String Type){
        
        Error_Log__c ec = new Error_Log__c();
        ec.Running_User__c = Userinfo.getUserId();
        ec.Exception_Message__c = Message;
        ec.Exception_type__c = Type;
        ec.Entity_Name__c = ClassName;
        ec.Action_Name__c = MethodName;
        Database.insert(ec,false); 
    }
    
    public static void create_log(String ErrorMessage,String Type){
        Error_Log__c ec = new Error_Log__c();
        ec.Running_User__c = Userinfo.getUserId();
        ec.Exception_Message__c = ErrorMessage;
        ec.Exception_type__c = Type;
        Database.insert(ec,false);
        
    }
    
    public static void  sendEmail(String recId){
      List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
      // Step 1: Create a new Email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            // Step 2: Set list of people who should get the email
            List<String> sendTo = new List<String>();
           // string a=Label.Request_Calculator_Package_EmailID;
            sendTo.add(System.Label.EmailError);
            mail.setToAddresses(sendTo);
           // mail.setReplyTo(a);
            mail.setSubject('Issue with the system');
            String body ;             
            body='<html><body>'; 
            body+='<div> Somehing went wrong please find more details at '+recId+' </div>'; 
            body+=  '</body> </html>';      
            mail.setHtmlBody(body);
            mails.add(mail);Messaging.sendEmail(mails);
    
    }
    
}