src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>RequestPayload__c</fullName>
        <description>JSON representation of the Request to External Service</description>
        <inlineHelpText>JSON representation of the Request to External Service</inlineHelpText>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Estimate_of_Appraised_Value__c</fullName>
        <label>Estimate of Appraised Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Closing_Costs__c</fullName>
        <description>Other Closing Costs</description>
        <inlineHelpText>Title, Closing &amp; Recording Fees</inlineHelpText>
        <label>Other Closing Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Loan__c</fullName>
        <inlineHelpText>User can select more than one option. Please hold the Ctrl button on the keyboard to select more than one option.</inlineHelpText>
        <label>Purpose of Loan</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Additional Income</fullName>
                </value>
                <value>
                    <fullName>Home Improvement</fullName>
                </value>
                <value>
                    <fullName>Payment of Taxes</fullName>
                </value>
                <value>
                    <fullName>Payment of Insurance</fullName>
                </value>
                <value>
                    <fullName>Leisure</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Extinguish Forward Mortgage</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ARM</fullName>
                    <default>true</default>
                    <label>ARM</label>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Using_Title_Source_as_the_Closing_Agent__c</fullName>
        <inlineHelpText>Using AmRock as the Closing Agent/Escrow Officer and Title Company?</inlineHelpText>
        <label>Using AmRock as the Closing Agent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HECM</fullName>
                </value>
                <value>
                    <fullName>HELO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Property_State__c</fullName>
        <description>Property State</description>
        <inlineHelpText>Property State</inlineHelpText>
        <label>Subject Property State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_Property_Zip_Code__c</fullName>
        <description>Property Zip Code</description>
        <inlineHelpText>Property Zip Code</inlineHelpText>
        <label>Subject Property Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Applied_for__c</fullName>
        <label>Mortgage Applied for</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FHA Traditional HECM</fullName>
                </value>
                <value>
                    <fullName>HECM to HECM Refinance</fullName>
                </value>
                <value>
                    <fullName>HECM for Purchase</fullName>
                </value>
                <value>
                    <fullName>HELO Refinance</fullName>
                </value>
                <value>
                    <fullName>HELO for Purchase</fullName>
                </value>
                <value>
                    <fullName>FHA Refinance HECM</fullName>
                    <isActive>false</isActive>
                    <label>FHA Refinance HECM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_Property_Type__c</fullName>
        <label>Subject Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Family</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Co-operative</fullName>
                    <label>CO-OP</label>
                </value>
                <value>
                    <fullName>Two-to-four unit property</fullName>
                    <label>2 - 4 Family</label>
                </value>
                <value>
                    <fullName>Multifamily (more than 4 units)</fullName>
                </value>
                <value>
                    <fullName>Manufactured/Mobile Home</fullName>
                    <label>Manufactured</label>
                </value>
                <value>
                    <fullName>Commercial - Non-Residential</fullName>
                </value>
                <value>
                    <fullName>Farm</fullName>
                </value>
                <value>
                    <fullName>Home and Business Combined</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Planned Unit Development (PUD)</fullName>
                </value>
                <value>
                    <fullName>Site Condominium</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Manf Home/PUD</fullName>
                </value>
                <value>
                    <fullName>Mixed use - Residential</fullName>
                </value>
                <value>
                    <fullName>Mixed Use – Residential</fullName>
                    <isActive>false</isActive>
                    <label>Mixed Use – Residential</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/TriggerExternalServiceOutbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceOutbound.cls</description><label>TriggerExternalServiceOutbound</label><pluralLabel>TriggerExternalServiceOutbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/ExternalServicePayloadGenerator_Test.cls
/**
* @description test class for ExternalServicePayloadGenerator.cls
*
* @author Dennis Wilson
* @date 05/20/2018
*
* changelog:
* 06/04/2018: DWilson - changed to private class declaration
*
*/
@IsTest
private with sharing class ExternalServicePayloadGenerator_Test {

	private static final String EXTERNAL_SERVICE_NAME = 'AmrockBot';
	private static final String LOAN_STATUS_APPLICATIONREQUESTED = 'Proposal';
	private static final String LOAN_PROPERTY_TYPE = 'Single Family';
	private static final String LOAN_PROPERTY_ZIP = '90202';
	private static final Decimal LOAN_APPRAISED_VALUE = 500000;
    private static final String EXTERNAL_SERVICE_NAME_ONBASE = 'OnBase_Final';
    private static final String LOAN_ONBASE_LOAN_NUMBER = '2000000000';
    private static final String LOAN_ONBASE_SUBJECT_PROPERTY_STATE = 'Louisiana';
    private static final String LOAN_ONBASE_PRODUCT_TYPE = 'HECM';
    private static final String LOAN_ONBASE_MORTGAGE_APPLIED_FOR = 'HECM to HECM Refinance';
    private static final String LOAN_ONBASE_RATE_TYPE = 'ARM';
    private static final String LOAN_ONBASE_USING_TITLE_SOURCE = 'Yes';
    private static final String LOAN_ONBASE_PURPOSE_OF_LOAN = 'Home Improvement';

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description postive test of insertExternalService method
	*/
	static testMethod void testInsertExternalServicePositive() {

		// disable outbound external service trigger processing
		TriggerHandlerExternalServiceOutbound.tesoControlMap = testTESOmdtMap;
		Test.startTest();
		ExternalServicePayloadGenerator.insertExternalService( testRequestList );
		Test.stopTest();
		// check if JSON payload was generated properly
		ExternalService__c checkExternalService = [SELECT Id, RequestPayload__c FROM ExternalService__c LIMIT 1];
		Map<String, Object> checkPayloadMap = ( Map<String, Object> )JSON.deserializeUntyped( checkExternalService.RequestPayload__c );
		System.debug( '>>> checkExternalService.RequestPayload__c: ' + checkExternalService.RequestPayload__c );
		String checkZip = ( String )checkPayloadMap.get( 'zipCode' );
		System.assertEquals( checkZip, LOAN_PROPERTY_ZIP );
	}
    
    /*******************************************************************************************************
	* @description positive test of insertExternalService method for OnBase
	*/
	static testMethod void testInsertExternalServicePositive_OnBase() {

		// disable outbound external service trigger processing
		TriggerHandlerExternalServiceOutbound.tesoControlMap = testTESOmdtMap;
		Test.startTest();
		ExternalServicePayloadGenerator.insertExternalService(testRequestListOnBase);
		Test.stopTest();
		// check if JSON payload was generated properly
		ExternalService__c checkExternalService = [SELECT Id, RequestPayload__c FROM ExternalService__c LIMIT 1];
		Map<String, Object> checkPayloadMap = (Map<String, Object>)JSON.deserializeUntyped(checkExternalService.RequestPayload__c);
		System.debug('>>> checkExternalService_OnBase.RequestPayload__c: ' + checkExternalService.RequestPayload__c);
        
		String checkLoanNumber = (String)checkPayloadMap.get('loanNumber');
		System.assertEquals(LOAN_ONBASE_LOAN_NUMBER, checkLoanNumber);
        
        List<Object> keywords = (List<Object>)checkPayloadMap.get('keywords');
        System.debug('Keywords> ' + keywords);
        
        for(Object keyword : keywords) {
            Map<String, Object> kwmap = (Map<String, Object>)keyword;            
            String num = (String)kwmap.get('number');            
            switch on num {
                when '112' {
                    System.assertEquals(LOAN_ONBASE_PURPOSE_OF_LOAN, (String)kwmap.get('value'));
                }
            }
        }        
	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalServiceOutbound__mdt> testTESOmdtMap {
		get {
			return new Map<String, TriggerExternalServiceOutbound__mdt>{
				'processEvents' => ( TriggerExternalServiceOutbound__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "processEvents", "Enable__c" : false }', TriggerExternalServiceOutbound__mdt.class )
			};
		}
		private set;
	}

	private static Account testPartnerAccount {
		get {
			if ( testPartnerAccount == NULL ) {
				testPartnerAccount = new Account(
					Name = 'Test Partner Account'
				);
				Database.insert( testPartnerAccount );
			}
			return testPartnerAccount;
		}
		private set;
	}

	private static Loan_New__c testLoan {
		get {
			if ( testLoan == NULL ) {
				testLoan = new Loan_New__c(
					Related_Partner__c = testPartnerAccount.Id,
					LoanStatus__c = LOAN_STATUS_APPLICATIONREQUESTED,
					Subject_Property_Type__c = LOAN_PROPERTY_TYPE,
					Subject_Property_Zip_Code__c = LOAN_PROPERTY_ZIP,
					Estimate_of_Appraised_Value__c = LOAN_APPRAISED_VALUE,
					Other_Closing_Costs__c = NULL
				);
				Database.insert( testLoan );
			}
			return testLoan;
		}
		private set;
	}
    
    private static Loan_New__c testLoanOnBase {
		get {
			if (testLoanOnBase == NULL) {
				testLoanOnBase = new Loan_New__c(
					Related_Partner__c = testPartnerAccount.Id,
					LoanStatus__c = LOAN_STATUS_APPLICATIONREQUESTED,
					Subject_Property_Type__c = LOAN_PROPERTY_TYPE,
					Subject_Property_Zip_Code__c = LOAN_PROPERTY_ZIP,
					Estimate_of_Appraised_Value__c = LOAN_APPRAISED_VALUE,
					Other_Closing_Costs__c = NULL,
                    LoanNumber__c = LOAN_ONBASE_LOAN_NUMBER,
                    Subject_Property_State__c = LOAN_ONBASE_SUBJECT_PROPERTY_STATE,
                    Product_Type__c = LOAN_ONBASE_PRODUCT_TYPE, 
                    Mortgage_Applied_for__c = LOAN_ONBASE_MORTGAGE_APPLIED_FOR, 
                    Rate_Type__c = LOAN_ONBASE_RATE_TYPE,
                    Using_Title_Source_as_the_Closing_Agent__c = LOAN_ONBASE_USING_TITLE_SOURCE, 
                    Purpose_of_Loan__c = LOAN_ONBASE_PURPOSE_OF_LOAN
				);
				Database.insert(testLoanOnBase);
			}
			return testLoanOnBase;
		}
		private set;
	}

	// request passed to ExternalServicePayloadGenerator.insertExternalService() invocable method
	private static List<ExternalServicePayloadGenerator.Request> testRequestList{
		get {
			ExternalServicePayloadGenerator.Request testRequest = new ExternalServicePayloadGenerator.Request();
			testRequest.idList = new List<Id>{ testLoan.Id };
			testRequest.objectAPIName = 'Loan_New__c';
			testRequest.externalServiceType = EXTERNAL_SERVICE_NAME;
			return new List<ExternalServicePayloadGenerator.Request>{ testRequest };
		}
		private set;
	}

	// request passed to ExternalServicePayloadGenerator.insertExternalService() invocable method for OnBase
	private static List<ExternalServicePayloadGenerator.Request> testRequestListOnBase{
		get {
			ExternalServicePayloadGenerator.Request testRequest = new ExternalServicePayloadGenerator.Request();
			testRequest.idList = new List<Id>{ testLoanOnBase.Id };
			testRequest.objectAPIName = 'Loan_New__c';
			testRequest.externalServiceType = EXTERNAL_SERVICE_NAME_ONBASE;
			return new List<ExternalServicePayloadGenerator.Request>{ testRequest };
		}
		private set;
	}
}