src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>ResponsePayload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <inlineHelpText>JSON representation of Response from External Service</inlineHelpText>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceID__c</fullName>
        <description>Source Id</description>
        <inlineHelpText>Source Id</inlineHelpText>
        <label>Source ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SilverBulletFeesController.cls
public class SilverBulletFeesController{
   
    public class ServiceData {
        @AuraEnabled
        public Double totalAmount{get;set;}
        @AuraEnabled
        public List<FeeDetails> feeDetails{get;set;}
        
    }

    public class FeeDetails {
        @AuraEnabled
        public String feeDescription{get;set;}
        @AuraEnabled
        public String feeNumber{get;set;}
        @AuraEnabled
        public Double feeAmount{get;set;}
    }
    
    @AuraEnabled
    public static ServiceData getServiceData(string loanId) {
        List<ExternalService__c> eserviceList = [select Id,ResponsePayload__c from ExternalService__c where SourceID__c=:loanId
                                                and Status__c='Response Received'  and SourceID__c!=null 
                                                and ServiceName__c='AmrockBot' order by lastmodifieddate desc];
        
       if(eserviceList.size() > 0 && eserviceList[0].ResponsePayload__c != null)
       {
           return (ServiceData) System.JSON.deserialize(eserviceList[0].ResponsePayload__c, ServiceData.class);
       }
         else
      return null;
    }
    
}