src/objects/ExternalServiceOutbound__e.object
<CustomObject><fields>
        <fullName>ExternalServiceID__c</fullName>
        <description>Reference to ExternalService__c object associated with this Event</description>
        <label>External Service ID</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Payload__c</fullName>
        <description>JSON representation of Request to External Service</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <label>Service Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Platform Event to an External Service.</description><eventType>StandardVolume</eventType><label>External Service Outbound</label><pluralLabel>External Service Outbound</pluralLabel></CustomObject>

src/objects/TriggerExternalServiceOutbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceOutbound.cls</description><label>TriggerExternalServiceOutbound</label><pluralLabel>TriggerExternalServiceOutbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerExternalServiceOutbound.cls
/**
* @description TriggerHandlerExternalServiceOutbound is the overall trigger handler for ExternalServiceOutbound.trigger
* Implements and extends interface defined in TriggerHandler.class.
* See specific method descriptions for functionality.
* Custom Metadata Type records (TriggerExternalServiceOutbound__mdt) control method functionality.
*
* @author Dennis Wilson
* @date 5/10/2018
*
* changelog:
*
*/
public without sharing class TriggerHandlerExternalServiceOutbound extends TriggerHandler {

	/*******************************************************************************************************
	* @description custom metadata types enable/disable methods
	*/
	@testVisible
	private static Map<String, TriggerExternalServiceOutbound__mdt> tesoControlMap {
		get {
			if ( tesoControlMap == NULL ) {
				tesoControlMap = new Map<String, TriggerExternalServiceOutbound__mdt>();
				for ( TriggerExternalServiceOutbound__mdt tesoControl : [SELECT MasterLabel, Enable__c FROM TriggerExternalServiceOutbound__mdt] ) {
					tesoControlMap.put( tesoControl.MasterLabel, tesoControl );
				}
			}
			return tesoControlMap;
		}
		set;
	}

	/*******************************************************************************************************
	* @description used to induce exception coverage by test methods
	*/
	@TestVisible
	private Boolean testException = FALSE;

	public TriggerHandlerExternalServiceOutbound() {

//		System.debug( '>>> tesoControlMap: ' + tesoControlMap );
	}

	/* context overrides */

	public override void afterInsert() {
		if ( tesoControlMap.get( 'processEvents' ) != NULL ) {
			if ( tesoControlMap.get( 'processEvents' ).Enable__c ) processEvents( Trigger.new );
		}
	}

	/* private methods */

	/*******************************************************************************************************
	* @description processes an ExternalServiceOutbound__e event published to Platform Events Bus
	* @param newExternalServiceList list of ExternalServiceOutbound__e events to process
	*/
	private void processEvents( List<ExternalServiceOutbound__e> newESOlist ) {

		// must serialize ESO objects to pass to future method
		List<String> serialESOlist = new List<String>();
		for ( ExternalServiceOutbound__e eso : newESOlist ) {
			System.debug( '>>> eso.ExternalServiceID__c: ' + eso.ExternalServiceID__c );
			System.debug( '>>> eso.Payload__c: ' + eso.Payload__c );
			System.debug( '>>> eso.ServiceName__c: ' + eso.ServiceName__c );
			System.debug( '>>> eso.ReplayId: ' + eso.ReplayId );
			String serialESO = JSON.serialize( eso );
			serialESOlist.add( serialESO );
		}
		// pass the list to dispatcher for making service callouts
		ExternalServiceDispatcher.processESOlist( serialESOlist );
	}

}