src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>RequestPayload__c</fullName>
        <description>JSON representation of the Request to External Service</description>
        <inlineHelpText>JSON representation of the Request to External Service</inlineHelpText>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerExternalService__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalService.cls.</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalService.cls.</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalService.cls</description><label>TriggerExternalService</label><pluralLabel>TriggerExternalServices</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerExternalService_Test.cls
/**
* @description test class for TriggerHandlerExternalService.cls
*
* @author Dennis Wilson
* @date 5/8/2018
*
* changelog:
*
*/

@IsTest
private class TriggerHandlerExternalService_Test {

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description positive test of the publishEvents method
	*/
	static testMethod void testPublishEventsPositive() {

		Test.startTest();
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		System.assertNotEquals( testExternalServiceGood, NULL );
		Test.stopTest();
		ExternalService__c checkExternalService = [SELECT Id, Status__c, RequestPayload__c FROM ExternalService__c LIMIT 1];
		System.debug( '>>> checkExternalService.Status__c: ' + checkExternalService.Status__c );
		System.debug( '>>> checkExternalService.RequestPayload__c: ' + checkExternalService.RequestPayload__c );
		System.assertEquals( checkExternalService.Status__c, 'Requested' );
		// strictly for coverage:
		Database.delete( testExternalServiceGood );
		Database.undelete( testExternalServiceGood );
		// force reading of real controls
		TriggerHandlerExternalService.tesControlMap = NULL;
		Map<String, TriggerExternalService__mdt> checkControlMap = TriggerHandlerExternalService.tesControlMap;

	}

	/*******************************************************************************************************
	* @description exception test of the publishEvents method
	*/
	static testMethod void testPublishEventsExceptions() {

		Test.startTest();
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		System.assertNotEquals( testExternalServiceBad, NULL );
		Test.stopTest();
		ExternalService__c checkExternalService = [SELECT Id, Status__c, RequestPayload__c FROM ExternalService__c LIMIT 1];
		System.debug( '>>> checkExternalService.Status__c: ' + checkExternalService.Status__c );
		System.assertEquals( checkExternalService.Status__c, 'Error/Exception' );

	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalService__mdt> testTESmdtMap {
		get {
			return new Map<String, TriggerExternalService__mdt>{
				'publishEvents' => ( TriggerExternalService__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "publishEvents", "Enable__c" : true }', TriggerExternalService__mdt.class )
			};
		}
		private set;
	}

	private static ExternalService__c testExternalServiceGood {
		get {
			if ( testExternalServiceGood == NULL ) {
				testExternalServiceGood = new ExternalService__c(
					Status__c = 'New',
					RequestPayload__c = '{ "nothingHere" : "yet" }',
					ServiceName__c = 'JustTesting'
				);
				Database.insert( testExternalServiceGood );
			}
			return testExternalServiceGood;
		}
		private set;
	}

	private static ExternalService__c testExternalServiceBad {
		get {
			if ( testExternalServiceBad == NULL ) {
				testExternalServiceBad = new ExternalService__c(
					Status__c = 'New'
				);
				Database.insert( testExternalServiceBad );
			}
			return testExternalServiceBad;
		}
		private set;
	}
}