src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>RequestPayload__c</fullName>
        <description>JSON representation of the Request to External Service</description>
        <inlineHelpText>JSON representation of the Request to External Service</inlineHelpText>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceOutbound__e.object
<CustomObject><fields>
        <fullName>ExternalServiceID__c</fullName>
        <description>Reference to ExternalService__c object associated with this Event</description>
        <label>External Service ID</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Payload__c</fullName>
        <description>JSON representation of Request to External Service</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <label>Service Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Platform Event to an External Service.</description><eventType>StandardVolume</eventType><label>External Service Outbound</label><pluralLabel>External Service Outbound</pluralLabel></CustomObject>

src/objects/ExternalServiceRegistry__mdt.object
<CustomObject>
    <description>Entries represent control parameters for External Services.  Referenced by the ServiceName__c field of ExternalService__c records, and used within ExternalServiceDispatcher.cls</description>
    <label>ExternalServiceRegistry</label>
    <pluralLabel>ExternalServiceRegistries</pluralLabel>
</CustomObject>

src/objects/TriggerExternalService__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalService.cls.</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalService.cls.</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalService.cls</description><label>TriggerExternalService</label><pluralLabel>TriggerExternalServices</pluralLabel><visibility>Public</visibility></CustomObject>

src/objects/TriggerExternalServiceOutbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceOutbound.cls</description><label>TriggerExternalServiceOutbound</label><pluralLabel>TriggerExternalServiceOutbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerExternalServiceOutbnd_Test.cls
/**
* @description test class for TriggerHandlerExternalServiceOutbound.cls
*
* @author Dennis Wilson
* @date 5/10/2018
*
* changelog:
*
*/
@IsTest
private class TriggerHandlerExternalServiceOutbnd_Test {

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description tests the processEvents method
	*/
	static testMethod void testProcessEvents() {

		System.debug( '>>>> starting testProcessEvents...' );
		Test.startTest();
		// basically isolate and disable TriggerHandlerExternalService processing on insert of ExternalService__c
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// disable ExternalServiceDispatcher
		ExternalServiceDispatcher.esrControlMap = testEScontrolMap;
		// enable processing on insert of ExternalServiceOutbound__e
		TriggerHandlerExternalServiceOutbound.tesoControlMap = testTESOmdtMap;
		// publish test event
		Database.SaveResult checkSR = EventBus.publish( testExternalServiceOutbound );
		// strictly for coverage
		TriggerHandlerExternalServiceOutbound.tesoControlMap = NULL;
		Map<String, TriggerExternalServiceOutbound__mdt> checkControlMap = TriggerHandlerExternalServiceOutbound.tesoControlMap;
		Test.stopTest();
		// no meaningful assertions...

	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalService__mdt> testTESmdtMap {
		get {
			// basically isolate and disable TriggerHandlerExternalService processing on insert of ExternalService__c
			return new Map<String, TriggerExternalService__mdt>();
		}
		private set;
	}

	private static Map<String, TriggerExternalServiceOutbound__mdt> testTESOmdtMap {
		get {
			return new Map<String, TriggerExternalServiceOutbound__mdt>{
				'processEvents' => ( TriggerExternalServiceOutbound__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "processEvents", "Enable__c" : true }', TriggerExternalServiceOutbound__mdt.class )
			};
		}
		private set;
	}

	private static Map<String, ExternalServiceRegistry__mdt> testEScontrolMap {
		get {
			// disable ExternalServiceDispatcher from doing anything
			return new Map<String, ExternalServiceRegistry__mdt>();
		}
		private set;
	}



	private static ExternalService__c testExternalService {
		get {
			System.debug( '>>> getting testExternalService...' );
			if ( testExternalService == NULL ) {
				System.debug( '>>> constructing testExternalService...' );
				testExternalService = new ExternalService__c(
					Status__c = 'New',
					RequestPayload__c = '{ "nothingHere" : "yet" }',
					ServiceName__c = 'AmrockBot'
				);
				Database.insert( testExternalService );
			}
			return testExternalService;
		}
		private set;
	}

	private static ExternalServiceOutbound__e testExternalServiceOutbound {
		get {
			testExternalServiceOutbound = new ExternalServiceOutbound__e(
				ExternalServiceID__c = testExternalService.Id,
				Payload__c = testExternalService.RequestPayload__c,
				ServiceName__c = testExternalService.ServiceName__c
			);
			return testExternalServiceOutbound;
		}
		private set;
	}


}