src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>RequestPayload__c</fullName>
        <description>JSON representation of the Request to External Service</description>
        <inlineHelpText>JSON representation of the Request to External Service</inlineHelpText>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceInbound__e.object
<CustomObject><fields>
        <fullName>ExternalServiceID__c</fullName>
        <description>Reference to ExternalService__c object associated with this Event</description>
        <label>External Service ID</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Payload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Platform Event from an External Service</description><eventType>StandardVolume</eventType><label>External Service Inbound</label><pluralLabel>External Service Inbound</pluralLabel></CustomObject>

src/objects/TriggerExternalService__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalService.cls.</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalService.cls.</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalService.cls</description><label>TriggerExternalService</label><pluralLabel>TriggerExternalServices</pluralLabel><visibility>Public</visibility></CustomObject>

src/objects/TriggerExternalServiceInbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceInbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceInbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceInbound.cls</description><label>TriggerExternalServiceInbound</label><pluralLabel>TriggerExternalServiceInbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerExternalServiceInbnd_Test.cls
/**
* @description test class for TriggerHandlerExternalServiceInbound.cls
*
* @author Dennis Wilson
* @date 5/15/2018
*
* changelog:
*
*/
@IsTest
private class TriggerHandlerExternalServiceInbnd_Test {

	private static final String EXTERNAL_SERVICE_NAME = 'TestExternalService';

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description positive test of the processEvents() method
	*/
	static testMethod void testProcessEventsPositive() {

		Test.startTest();
		// disable trigger handler for ExternalService__c
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// enable processing on insert of ExternalServiceInbound__e
		TriggerHandlerExternalServiceInbound.tesiControlMap = testTESImdtMap;
		// publish an incoming event
		ExternalServiceInbound__e testESIevent = new ExternalServiceInbound__e(
			ExternalServiceID__c = testExternalService.Id,
			Payload__c = ExternalServiceDispatcher.fixPayloadReference( testExternalService.RequestPayload__c, testExternalService.Id ),
			ServiceName__c = testExternalService.ServiceName__c
		);
		Database.SaveResult publishSR = EventBus.publish( testESIevent );
		System.assertNotEquals( publishSR.getId(), NULL );
		// strictly for coverage
		TriggerHandlerExternalServiceInbound.tesiControlMap = NULL;
		Map<String, TriggerExternalServiceInbound__mdt> checkControlMap = TriggerHandlerExternalServiceInbound.tesiControlMap;
		Test.stopTest();
	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalServiceInbound__mdt> testTESImdtMap {
		get {
			return new Map<String, TriggerExternalServiceInbound__mdt>{
				'processEvents' => ( TriggerExternalServiceInbound__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "processEvents", "Enable__c" : true }', TriggerExternalServiceInbound__mdt.class )
			};
		}
		private set;
	}

	private static Map<String, TriggerExternalService__mdt> testTESmdtMap {
		get {
			return new Map<String, TriggerExternalService__mdt>();
		}
		private set;
	}

	private static ExternalService__c testExternalService {
		get {
			if ( testExternalService == NULL ) {
				System.debug( '>>> creating testExternalService...' );
				testExternalService = new ExternalService__c(
					Status__c = 'New',
					RequestPayload__c = '{ "reference" : "FixMe" }',
					ServiceName__c = EXTERNAL_SERVICE_NAME
				);
				Database.insert( testExternalService );
			}
			return testExternalService;
		}
		private set;
	}



}