src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>ReplayID__c</fullName>
        <description>ReplayID from ExternalServiceOutbound__e Request</description>
        <inlineHelpText>ReplayID from ExternalServiceOutbound__e Request</inlineHelpText>
        <label>Replay ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResponsePayload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <inlineHelpText>JSON representation of Response from External Service</inlineHelpText>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceID__c</fullName>
        <description>Source Id</description>
        <inlineHelpText>Source Id</inlineHelpText>
        <label>Source ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceRegistry__mdt.object
<CustomObject>
    <description>Entries represent control parameters for External Services.  Referenced by the ServiceName__c field of ExternalService__c records, and used within ExternalServiceDispatcher.cls</description>
    <fields>
        <fullName>ExternalServiceClass__c</fullName>
        <description>External Service Class - Instantiated dynamically at runtime</description>
        <inlineHelpText>External Service Class</inlineHelpText>
        <label>External Service Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NamedCredential__c</fullName>
        <description>The Named Credential connection parameters to use for this External Service.</description>
        <inlineHelpText>The Named Credential connection parameters to use for this External Service.</inlineHelpText>
        <label>Named Credential</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ExternalServiceRegistry</label>
    <pluralLabel>ExternalServiceRegistries</pluralLabel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Other_Closing_Costs_URL__c</fullName>
        <description>Title, Closing &amp; Recording Fees PDF</description>
        <inlineHelpText>Title, Closing &amp; Recording Fees PDF</inlineHelpText>
        <label>Other Closing Costs URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Other_Closing_Costs__c</fullName>
        <description>Other Closing Costs</description>
        <inlineHelpText>Title, Closing &amp; Recording Fees</inlineHelpText>
        <label>Other Closing Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerExternalServiceOutbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceOutbound.cls</description><label>TriggerExternalServiceOutbound</label><pluralLabel>TriggerExternalServiceOutbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/ExternalServicePayloadResponder_Test.cls
/**
* @description test class for ExternalServicePayloadResponder.cls
*
* @author Dennis Wilson
* @date 05/20/2018
*
* changelog:
*
*/
@IsTest
private class ExternalServicePayloadResponder_Test {

	private static final String EXTERNAL_SERVICE_NAME = 'AmrockBot';
	private static final String EXTERNAL_SERVICE_CLASSNAME = 'AmrockTitleFeesDomainService';
	private static final String EXTERNAL_SERVICE_STATUS_RESPONSERECEIVED = 'Response Received';
	private static final Decimal EXPECTED_CLOSING_COSTS = 1234;
	private static final String EXPECTED_CLOSING_COST_URL = 'https://test.org';

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description postive test of processESOlist method
	*/
	static testMethod void testUpdateDomainRecordsPositive() {

		// disable outbound external service trigger processing
		TriggerHandlerExternalServiceOutbound.tesoControlMap = testTESOmdtMap;
		Test.startTest();
		// override any ExternalServiceRegistry__mdt entries for ExternalServicePayloadResponder
		ExternalServicePayloadResponder.esrControlMap = testESRcontrolMap;
		// call invocable with request list
		ExternalServicePayloadResponder.updateDomainRecords( testRequestList );
		Test.stopTest();
		// check results
		Loan_New__c checkLoan = [SELECT Id, Other_Closing_Costs__c, Other_Closing_Costs_URL__c FROM Loan_New__c LIMIT 1];
		System.debug( '>>> checkLoan.Other_Closing_Costs__c: ' + checkLoan.Other_Closing_Costs__c );
		System.debug( '>>> checkLoan.Other_Closing_Costs_URL__c: ' + checkLoan.Other_Closing_Costs_URL__c );
		// expect closing costs to be updated
		System.assertEquals( checkLoan.Other_Closing_Costs__c, EXPECTED_CLOSING_COSTS );
		// expect closing cost url to be updated
		System.assertEquals( checkLoan.Other_Closing_Costs_URL__c, EXPECTED_CLOSING_COST_URL );
		// just for coverage
		ExternalServicePayloadResponder.esrControlMap = NULL;
		System.assertNotEquals( ExternalServicePayloadResponder.esrControlMap, NULL );
	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalServiceOutbound__mdt> testTESOmdtMap {
		get {
			return new Map<String, TriggerExternalServiceOutbound__mdt>{
				'processEvents' => ( TriggerExternalServiceOutbound__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "processEvents", "Enable__c" : false }', TriggerExternalServiceOutbound__mdt.class )
			};
		}
		private set;
	}

	private static Map<String, ExternalServiceRegistry__mdt> testESRcontrolMap {
		get {
			testESRcontrolMap = new Map<String, ExternalServiceRegistry__mdt> {
				EXTERNAL_SERVICE_NAME => ( ExternalServiceRegistry__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "' + EXTERNAL_SERVICE_NAME +
						'", "NamedCredential__c" : "' + EXTERNAL_SERVICE_NAME +
						'", "ExternalServiceClass__c" : "' + EXTERNAL_SERVICE_CLASSNAME +
						'" }',
					ExternalServiceRegistry__mdt.class )
			};
			return testESRcontrolMap;
		}
		private set;
	}

	private static Loan_New__c testLoan {
		get {
			if ( testLoan == NULL ) {
				testLoan = new Loan_New__c(

				);
				Database.insert( testLoan );
			}
			return testLoan;
		}
		private set;
	}

	private static ExternalService__c testExternalService {
		get {
			if ( testExternalService == NULL ) {
				Map<String, String> testResponseMap = new Map<String, String>{
					'pdfUrl'        => EXPECTED_CLOSING_COST_URL,
					'pdfShortUrl'   => EXPECTED_CLOSING_COST_URL,
					// note the stripping of commas from the quoteTotal token value!!!
					'quoteTotal'    => EXPECTED_CLOSING_COSTS.format().replaceAll( ',', '' )
				};
				System.debug( '>>> JSON.serialize( testResponseMap ): ' + JSON.serialize( testResponseMap ) );
				testExternalService = new ExternalService__c(
					ReplayID__c = '1',
					ServiceName__c = EXTERNAL_SERVICE_NAME,
					SourceID__c = testLoan.Id,
					Status__c = EXTERNAL_SERVICE_STATUS_RESPONSERECEIVED,
					ResponsePayload__c = JSON.serialize( testResponseMap )
				);
				Database.insert( testExternalService );
			}
			return testExternalService;
		}
		private set;
	}

	// request passed to ExternalServicePayloadResponder.updateDomainRecords() invocable method
	private static List<ExternalServicePayloadResponder.Request> testRequestList{
		get {
			ExternalServicePayloadResponder.Request testRequest = new ExternalServicePayloadResponder.Request();
			testRequest.idList = new List<Id>{ testExternalService.Id };
			testRequest.sourceIdList = new List<Id>{ testExternalService.SourceID__c };
			testRequest.payloadResponseList = new List<String>{ testExternalService.ResponsePayload__c };
			testRequest.objectAPIName = 'Loan_New__c';
			testRequest.externalServiceType = EXTERNAL_SERVICE_NAME;
			return new List<ExternalServicePayloadResponder.Request>{ testRequest };
		}
		private set;
	}
}