src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>ResponsePayload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <inlineHelpText>JSON representation of Response from External Service</inlineHelpText>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceInbound__e.object
<CustomObject><fields>
        <fullName>Payload__c</fullName>
        <description>JSON representation of Response from External Service</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Platform Event from an External Service</description><eventType>StandardVolume</eventType><label>External Service Inbound</label><pluralLabel>External Service Inbound</pluralLabel></CustomObject>

src/objects/TriggerExternalServiceInbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceInbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceInbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceInbound.cls</description><label>TriggerExternalServiceInbound</label><pluralLabel>TriggerExternalServiceInbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerExternalServiceInbound.cls
/**
* @description TriggerHandlerExternalServiceInbound is the overall trigger handler for ExternalServiceInbound.trigger
* Implements and extends interface defined in TriggerHandler.class.
* See specific method descriptions for functionality.
* Custom Metadata Type records (TriggerExternalServiceInbound__mdt) control method functionality.
*
* @author Dennis Wilson
* @date 5/11/2018
*
* changelog:
*
*/
public without sharing class TriggerHandlerExternalServiceInbound extends TriggerHandler {

	/*******************************************************************************************************
	* @description custom metadata types enable/disable methods
	*/
	@testVisible
	private static Map<String, TriggerExternalServiceInbound__mdt> tesiControlMap {
		get {
			if ( tesiControlMap == NULL ) {
				tesiControlMap = new Map<String, TriggerExternalServiceInbound__mdt>();
				for ( TriggerExternalServiceInbound__mdt tesiControl : [SELECT MasterLabel, Enable__c FROM TriggerExternalServiceInbound__mdt] ) {
					tesiControlMap.put( tesiControl.MasterLabel, tesiControl );
				}
			}
			return tesiControlMap;
		}
		set;
	}

	/*******************************************************************************************************
	* @description used to induce exception coverage by test methods
	*/
	@TestVisible
	private Boolean testException = FALSE;

	public TriggerHandlerExternalServiceInbound() {

//		System.debug( '>>> tesiControlMap: ' + tesiControlMap );
	}

	/* context overrides */

	public override void afterInsert() {
		if ( tesiControlMap.get( 'processEvents' ) != NULL ) {
			if ( tesiControlMap.get( 'processEvents' ).Enable__c ) processEvents( Trigger.new );
		}
	}

	/* private methods */

	/*******************************************************************************************************
	* @description processes an ExternalServiceInbound__e event published to Platform Events Bus
	* @param newExternalServiceList list of ExternalServiceInbound__e events to process
	*/
	private void processEvents( List<ExternalServiceInbound__e> newESIlist ) {

		// gather up ExternalService__c Ids from inbound events
		Set<Id> esIdSet = new Set<Id>();
		for ( ExternalServiceInbound__e esi : newESIlist ) {
			String esId = ExternalServiceDispatcher.getPayloadReference( esi.Payload__c );
			System.debug( '>>> TriggerHandlerExternalServiceInbound.processEvents.esi.Payload__c: ' + esi.Payload__c );
			System.debug( '>>> TriggerHandlerExternalServiceInbound.processEvents.esId: ' + esId );
			if ( String.isNotBlank( esId ) && esId instanceof Id ) {
				esIdSet.add( esId );
			}
		}
		// create map of ExternalService__c records to update
		Map<Id, ExternalService__c> updateESIdMap = new Map<Id, ExternalService__c>( [
			SELECT Id, Status__c
			FROM ExternalService__c
			WHERE Id IN :esIdSet
		] );
		if ( !updateESIdMap.isEmpty() ) {
			System.debug( '>>> TriggerHandlerExternalServiceInbound.processEvents:  updating ESI...' );
			for ( ExternalServiceInbound__e esi : newESIlist ) {
				Id esId = ExternalServiceDispatcher.getPayloadReference( esi.Payload__c );
				if ( esId != NULL ) {
					ExternalService__c updateES = updateESIdMap.get( esId );
					updateES.Status__c = 'Response Received';
					updateES.ResponsePayload__c = esi.Payload__c;
				}
			}
			Database.update( updateESIdMap.values() );
		}
	}
}