src/objects/ExternalServiceRegistry__mdt.object
<CustomObject>
    <description>Entries represent control parameters for External Services.  Referenced by the ServiceName__c field of ExternalService__c records, and used within ExternalServiceDispatcher.cls</description>
    <label>ExternalServiceRegistry</label>
    <pluralLabel>ExternalServiceRegistries</pluralLabel>
</CustomObject>

src/objects/ExternalServicesObjectFieldMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <description>Default Value</description>
        <inlineHelpText>Default Value</inlineHelpText>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <description>Field API Name</description>
        <inlineHelpText>Field API Name</inlineHelpText>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MappingProperty__c</fullName>
        <description>Mapping Property</description>
        <inlineHelpText>Mapping Property</inlineHelpText>
        <label>Mapping Property</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <description>Object API Name</description>
        <inlineHelpText>Object API Name</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Service Name</description>
        <inlineHelpText>Service Name</inlineHelpText>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
  <description>External Service Object / Field Mapping Configuration</description>
  <label>External Services Object/Field Mapping</label>
  <pluralLabel>External Services Object/Field Mapping</pluralLabel>
</CustomObject>

src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Estimate_of_Appraised_Value__c</fullName>
        <label>Estimate of Appraised Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Closing_Costs__c</fullName>
        <description>Other Closing Costs</description>
        <inlineHelpText>Title, Closing &amp; Recording Fees</inlineHelpText>
        <label>Other Closing Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Property_Zip_Code__c</fullName>
        <description>Property Zip Code</description>
        <inlineHelpText>Property Zip Code</inlineHelpText>
        <label>Subject Property Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Property_Type__c</fullName>
        <label>Subject Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Family</fullName>
                </value>
                <value>
                    <fullName>Condominium</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Co-operative</fullName>
                    <label>CO-OP</label>
                </value>
                <value>
                    <fullName>Two-to-four unit property</fullName>
                    <label>2 - 4 Family</label>
                </value>
                <value>
                    <fullName>Multifamily (more than 4 units)</fullName>
                </value>
                <value>
                    <fullName>Manufactured/Mobile Home</fullName>
                    <label>Manufactured</label>
                </value>
                <value>
                    <fullName>Commercial - Non-Residential</fullName>
                </value>
                <value>
                    <fullName>Farm</fullName>
                </value>
                <value>
                    <fullName>Home and Business Combined</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Planned Unit Development (PUD)</fullName>
                </value>
                <value>
                    <fullName>Site Condominium</fullName>
                </value>
                <value>
                    <fullName>PUD</fullName>
                </value>
                <value>
                    <fullName>Manf Home/PUD</fullName>
                </value>
                <value>
                    <fullName>Mixed use - Residential</fullName>
                </value>
                <value>
                    <fullName>Mixed Use – Residential</fullName>
                    <isActive>false</isActive>
                    <label>Mixed Use – Residential</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/TriggerExternalServiceOutbound__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalServiceOutbound.cls</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalServiceOutbound.cls</description><label>TriggerExternalServiceOutbound</label><pluralLabel>TriggerExternalServiceOutbound</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/ExternalServiceConfigComposer_Test.cls
/**
* @description test class for ExternalServiceConfigComposer.cls
*
* @author Dennis Wilson
* @date 05/20/2018
*
* changelog:
*
*/
@IsTest
private class ExternalServiceConfigComposer_Test {

	private static final String EXTERNAL_SERVICENAME = 'AmrockBot';
	private static final String OBJECT_APINAME = 'Loan_New__c';
	private static final String LOAN_STATUS_APPLICATIONREQUESTED = 'Proposal';
	private static final String LOAN_PROPERTY_TYPE = 'Single Family';
	private static final String LOAN_PROPERTY_ZIP = '90202';
	private static final Decimal LOAN_APPRAISED_VALUE = 500000;

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description postive test of getExternalServiceMapping method
	*/
	static testMethod void testGetExternalServiceMapping() {

		Test.startTest();
		List<ExternalServicesObjectFieldMapping__mdt> checkESOFMmdtList = ExternalServiceConfigComposer.getExternalServiceMapping( EXTERNAL_SERVICENAME );
		Test.stopTest();
		for ( ExternalServicesObjectFieldMapping__mdt ESOFMmdt : checkESOFMmdtList ) {
			System.debug( '>>> ESOFMmdt: ' + ESOFMmdt );
		}
	}

	/*******************************************************************************************************
	* @description postive test of getExternalServices method
	*/
	static testMethod void testGetExternalServices() {

		Test.startTest();
		List<ExternalServiceRegistry__mdt> checkESRmdtList = ExternalServiceConfigComposer.getExternalServices( EXTERNAL_SERVICENAME );
		Test.stopTest();
		for ( ExternalServiceRegistry__mdt ESRmdt : checkESRmdtList ) {
			System.debug( '>>> ESRmdt: ' + ESRmdt );
		}
	}

	/*******************************************************************************************************
	* @description postive test of getFieldAPIs method
	*/
	static testMethod void testGetFieldAPIs() {

		Test.startTest();
		Set<String> checkAPINameSet = ExternalServiceConfigComposer.getFieldAPIs( testESOFMlist );
		Test.stopTest();
		for ( String APIName : checkAPINameSet ) {
			System.debug( '>>> APIName: ' + APIName );
		}
	}

	/*******************************************************************************************************
	* @description postive test of composeQuery method
	*/
	static testMethod void testComposeQuery() {

		Test.startTest();
		Set<String> testAPINameSet = ExternalServiceConfigComposer.getFieldAPIs( testESOFMlist );
		String checkQuery = ExternalServiceConfigComposer.composeQuery( testAPINameSet, OBJECT_APINAME );
		Test.stopTest();
		System.debug( '>>> checkQuery: ' + checkQuery );
		System.assert( checkQuery.contains( 'SELECT' ) );
	}

	/*******************************************************************************************************
	* @description postive test of getAllFieldQueryString method
	*/
	static testMethod void testGetAllFieldQueryString() {

		Test.startTest();
		String checkQuery = ExternalServiceConfigComposer.getAllFieldQueryString( OBJECT_APINAME );
		Test.stopTest();
		System.debug( '>>> checkQuery: ' + checkQuery );
	}

	/*******************************************************************************************************
	* @description postive test of getSobjectDataFromIdList method
	*/
	static testMethod void testGetSobjectDataFromIdList() {

		// disable outbound external service trigger processing
		TriggerHandlerExternalServiceOutbound.tesoControlMap = testTESOmdtMap;
		Test.startTest();
		Map<Id, SObject> checkIdSObjectMap = ExternalServiceConfigComposer.getSobjectDataFromIdList( new List<Id>{ testLoan.Id } );
		Test.stopTest();
		System.debug( '>>> checkIdSObjectMap: ' + checkIdSObjectMap );
		Loan_New__c checkLoan = ( Loan_New__c )checkIdSObjectMap.get( testLoan.Id );
		System.assertEquals( checkLoan.Subject_Property_Zip_Code__c, LOAN_PROPERTY_ZIP );
	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalServiceOutbound__mdt> testTESOmdtMap {
		get {
			return new Map<String, TriggerExternalServiceOutbound__mdt>{
				'processEvents' => ( TriggerExternalServiceOutbound__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "processEvents", "Enable__c" : false }', TriggerExternalServiceOutbound__mdt.class )
			};
		}
		private set;
	}

	private static List<ExternalServicesObjectFieldMapping__mdt> testESOFMlist {
		get {
			return new List<ExternalServicesObjectFieldMapping__mdt>{
				( ExternalServicesObjectFieldMapping__mdt )JSON.deserialize(
					'{ ' +
						'"MasterLabel" : "Amrock_Subject_Property_Type", ' +
						'"DefaultValue__c" : "Single Family", ' +
						'"FieldAPIName__c" : "Subject_Property_Type__c", ' +
						'"MappingProperty__c" : "propertyType", ' +
						'"ObjectAPIName__c" : "Loan_New__c", ' +
						'"ServiceName__c" : "' + EXTERNAL_SERVICENAME + '"' +
						' }', ExternalServicesObjectFieldMapping__mdt.class ),
				( ExternalServicesObjectFieldMapping__mdt )JSON.deserialize(
					'{ ' +
						'"MasterLabel" : "Amrock_estAppraisedValue", ' +
						'"DefaultValue__c" : "", ' +
						'"FieldAPIName__c" : "Estimate_of_Appraised_Value__c", ' +
						'"MappingProperty__c" : "estAppraisedValue", ' +
						'"ObjectAPIName__c" : "Loan_New__c", ' +
						'"ServiceName__c" : "' + EXTERNAL_SERVICENAME + '"' +
						' }', ExternalServicesObjectFieldMapping__mdt.class )
			};
		}
		private set;
	}

	private static Account testPartnerAccount {
		get {
			if ( testPartnerAccount == NULL ) {
				testPartnerAccount = new Account(
					Name = 'Test Partner Account'
				);
				Database.insert( testPartnerAccount );
			}
			return testPartnerAccount;
		}
		private set;
	}

	private static Loan_New__c testLoan {
		get {
			if ( testLoan == NULL ) {
				testLoan = new Loan_New__c(
					Related_Partner__c = testPartnerAccount.Id,
					LoanStatus__c = LOAN_STATUS_APPLICATIONREQUESTED,
					Subject_Property_Type__c = LOAN_PROPERTY_TYPE,
					Subject_Property_Zip_Code__c = LOAN_PROPERTY_ZIP,
					Estimate_of_Appraised_Value__c = LOAN_APPRAISED_VALUE,
					Other_Closing_Costs__c = NULL
				);
				Database.insert( testLoan );
			}
			return testLoan;
		}
		private set;
	}


}