src/objects/ExternalService__c.object
<CustomObject>
    <fields>
        <fullName>RequestPayload__c</fullName>
        <description>JSON representation of the Request to External Service</description>
        <inlineHelpText>JSON representation of the Request to External Service</inlineHelpText>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <inlineHelpText>Name of External Service</inlineHelpText>
        <label>Service Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the status of the overall External Service transaction.</description>
        <inlineHelpText>Represents the status of the overall External Service transaction.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Request Sent</fullName>
                </value>
                <value>
                    <fullName>Response Received</fullName>
                </value>
                <value>
                    <fullName>Product Updated</fullName>
                </value>
                <value>
                    <fullName>Malformed Request</fullName>
                </value>
                <value>
                    <fullName>Error/Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Encapsulate a transaction with an External Service.</description>
    <label>External Service</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>External Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExternalServiceOutbound__e.object
<CustomObject><fields>
        <fullName>ExternalServiceID__c</fullName>
        <description>Reference to ExternalService__c object associated with this Event</description>
        <label>External Service ID</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Payload__c</fullName>
        <description>JSON representation of Request to External Service</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>ServiceName__c</fullName>
        <description>Name of External Service</description>
        <label>Service Name</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Platform Event to an External Service.</description><eventType>StandardVolume</eventType><label>External Service Outbound</label><pluralLabel>External Service Outbound</pluralLabel></CustomObject>

src/objects/ExternalServiceRegistry__mdt.object
<CustomObject>
    <description>Entries represent control parameters for External Services.  Referenced by the ServiceName__c field of ExternalService__c records, and used within ExternalServiceDispatcher.cls</description>
    <fields>
        <fullName>NamedCredential__c</fullName>
        <description>The Named Credential connection parameters to use for this External Service.</description>
        <inlineHelpText>The Named Credential connection parameters to use for this External Service.</inlineHelpText>
        <label>Named Credential</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ExternalServiceRegistry</label>
    <pluralLabel>ExternalServiceRegistries</pluralLabel>
</CustomObject>

src/objects/TriggerExternalService__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables (or disables) the method within TriggerHandlerExternalService.cls.</description>
        <inlineHelpText>Enables (or disables) the method within TriggerHandlerExternalService.cls.</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerExternalService.cls</description><label>TriggerExternalService</label><pluralLabel>TriggerExternalServices</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/ExternalServiceDispatcher_Test.cls
/**
* @description test class for ExternalServiceDispatcher.cls
*
* @author Dennis Wilson
* @date 5/14/2018
*
* changelog:
*
*/

@IsTest
private class ExternalServiceDispatcher_Test {

	private static final String EXTERNAL_SERVICE_NAME = 'TestExternalService';

	@TestSetup
	static void setup() {
		// Create common test data for use in all test methods
		// @TestSetup initializes test data for each method

	}

	/*******************************************************************************************************
	* @description postive test of processESOlist method
	*/
	static testMethod void testProcessESOlistPositive() {

		// override and disable trigger on external service after insert
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// overide dispatcher controls to register test external service
		ExternalServiceDispatcher.esrControlMap = testEScontrolMap;
		Test.startTest();
		// setup mock response for callout
		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource( 'WS_AmrockBotMock' );
		mock.setStatusCode( 200 );
		mock.setHeader( 'Content-Type', 'application/json' );
		Test.setMock( HttpCalloutMock.class, mock );
		// call dispatcher with list of ESOs
		ExternalServiceDispatcher.processESOlist( testSerialESOlist );
		Test.stopTest();
	}

	/*******************************************************************************************************
	* @description exception testing the processESOlist method
	*/
	static testMethod void testProcessESOlistExceptions1() {

		Test.startTest();
		// override and disable trigger on external service after insert
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// overide dispatcher controls to register test external service
		ExternalServiceDispatcher.esrControlMap = testEScontrolMap;
		// setup mock response for callout
		// exception:  bad status code returned from callout
		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource( 'WS_AmrockBotMock' );
		mock.setStatusCode( 400 );
		mock.setHeader( 'Content-Type', 'application/json' );
		Test.setMock( HttpCalloutMock.class, mock );
		// call dispatcher with list of ESOs
		ExternalServiceDispatcher.processESOlist( testSerialESOlist );
		Test.stopTest();
	}

	/*******************************************************************************************************
	* @description exception testing the processESOlist method
	*/
	static testMethod void testProcessESOlistExceptions2() {

		Test.startTest();
		// override and disable trigger on external service after insert
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// overide dispatcher controls to register test external service
		ExternalServiceDispatcher.esrControlMap = NULL;
		// setup mock response for callout
		// exception:  bad status code returned from callout
		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource( 'WS_AmrockBotMock' );
		mock.setStatusCode( 200 );
		mock.setHeader( 'Content-Type', 'application/json' );
		Test.setMock( HttpCalloutMock.class, mock );
		// call dispatcher with list of ESOs
		ExternalServiceDispatcher.processESOlist( testSerialESOlist );
		Test.stopTest();
	}

	/*******************************************************************************************************
	* @description testing fixPayloadReference() and getPayloadReference() methods
	*/
	static testMethod void testPayloads() {

		Test.startTest();
		// override and disable trigger on external service after insert
		TriggerHandlerExternalService.tesControlMap = testTESmdtMap;
		// with reference token
		String checkPayload1 = ExternalServiceDispatcher.fixPayloadReference( testPayloadWithReference, testExternalService.Id );
		String checkRefValue1 = ExternalServiceDispatcher.getPayloadReference( checkPayload1 );
		// without reference token
		String checkPayload2 = ExternalServiceDispatcher.fixPayloadReference( testPayloadWithoutReference, testExternalService.Id );
		String checkRefValue2 = ExternalServiceDispatcher.getPayloadReference( checkPayload2 );
		// malformed json (throws exception)
		String checkRefValue3 = ExternalServiceDispatcher.getPayloadReference( testPayloadMalformed );
		// malformed json (throws exception)
		String fixPayloadReferenceNull = ExternalServiceDispatcher.fixPayloadReference( NULL, testExternalService.Id );
		String getPayloadReferenceNull = ExternalServiceDispatcher.getPayloadReference( NULL );
		Test.stopTest();
		// round trip through injection/extraction should result in an id replacement
		System.assertNotEquals( checkRefValue1, 'JustTesting' );
		System.assertEquals( checkRefValue2, NULL );
		System.assertEquals( checkRefValue3, NULL );
		System.assertEquals( checkRefValue3, NULL );
		System.assertEquals( fixPayloadReferenceNull, NULL );
		System.assertEquals( getPayloadReferenceNull, NULL );
	}

	/***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

	private static Map<String, TriggerExternalService__mdt> testTESmdtMap {
		get {
			return new Map<String, TriggerExternalService__mdt>{
				'publishEvents' => ( TriggerExternalService__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "publishEvents", "Enable__c" : false }', TriggerExternalService__mdt.class )
			};
		}
		private set;
	}

	private static Map<String, ExternalServiceRegistry__mdt> testEScontrolMap {
		get {
			testEScontrolMap = new Map<String, ExternalServiceRegistry__mdt> {
				EXTERNAL_SERVICE_NAME => ( ExternalServiceRegistry__mdt ) JSON.deserialize(
					'{ "MasterLabel" : "' + EXTERNAL_SERVICE_NAME + '", "NamedCredential__c" : "' + EXTERNAL_SERVICE_NAME + '" }',
					ExternalServiceRegistry__mdt.class )
			};
			return testEScontrolMap;
		}
		private set;
	}

	private static ExternalService__c testExternalService {
		get {
			if ( testExternalService == NULL ) {
				System.debug( '>>> creating testExternalService...' );
				testExternalService = new ExternalService__c(
					Status__c = 'New',
					RequestPayload__c = '{ "nothingHere" : "yet" }',
					ServiceName__c = EXTERNAL_SERVICE_NAME
				);
				Database.insert( testExternalService );
			}
			return testExternalService;
		}
		private set;
	}

	private static List<String> testSerialESOlist {
		get {
			if ( testSerialESOlist == NULL ) {
				testSerialESOlist = new List<String>();
				List<ExternalServiceOutbound__e> testESOlist = new List<ExternalServiceOutbound__e>{
					new ExternalServiceOutbound__e(
						ExternalServiceID__c = testExternalService.Id,
						Payload__c = '{ "just" : "testing", "reference" : "JustTesting" }',
						ServiceName__c = EXTERNAL_SERVICE_NAME
					),
					new ExternalServiceOutbound__e(
						ExternalServiceID__c = testExternalService.Id,
						Payload__c = '{ "just" : "testing" }',
						ServiceName__c = EXTERNAL_SERVICE_NAME
					)
				};
				for ( ExternalServiceOutbound__e eso : testESOlist ) {
					String serialESO = JSON.serialize( eso );
					testSerialESOlist.add( serialESO );
				}
			}
			return testSerialESOlist;
		}
		private set;
	}

	private static String testPayloadWithReference {
		get {
			return '{ "just" : "testing", "reference" : "JustTesting" }';
		}
		private set;
	}

	private static String testPayloadWithoutReference {
		get {
			return '{ "just" : "testing" }';
		}
		private set;
	}

	private static String testPayloadMalformed {
		get {
			return '{ "just" : "testing" ';
		}
		private set;
	}

}