src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Who_Requested_the_Withdraw__c</fullName>
        <label>Who Requested the Withdraw?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>How_was_the_Withdrawn_status_captured__c</fullName>
        <label>How was the Withdrawn status captured?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LoanStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ORMS Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdrawn_Reason__c</fullName>
        <label>Withdrawn Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LoanStatus__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Another Lender - Better program/process</fullName>
                </value>
                <value>
                    <fullName>Another Lender - Better rate and/or fees</fullName>
                </value>
                <value>
                    <fullName>Another Lender - Realtor/builder referral</fullName>
                </value>
                <value>
                    <fullName>Client not Interested</fullName>
                </value>
                <value>
                    <fullName>Chose Another Lender</fullName>
                </value>
                <value>
                    <fullName>Loan no longer needed</fullName>
                </value>
                <value>
                    <fullName>No longer makes sense for Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoanNumber__c</fullName>
        <label>LoanNumber*</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/LoanStatusDate_Test.cls
@isTest
private class LoanStatusDate_Test{

    @isTest
    static void loanDateTest(){
 
        Loan_New__c loanStatus1 = new Loan_New__c(
            LoanStatus__c = 'Proposal'
        );         
        insert loanStatus1;
        
        Loan_New__c loanStatus2 = new Loan_New__c(
            LoanStatus__c = 'Waiting for Full Package',LoanNumber__c = '12345990', Id=loanStatus1.Id
        );                
        loanStatus1.LoanStatus__c = 'Waiting for Full Package';
        update loanStatus2;
                
        Loan_New__c loanStatus3 = new Loan_New__c(
            LoanStatus__c = 'Full Application Received - Incomplete',LoanNumber__c = '12345991', Id=loanStatus2.Id
        );                     
        loanStatus2.LoanStatus__c = 'Full Application Received - Incomplete';   
        update loanStatus3;

        Loan_New__c loanStatus4 = new Loan_New__c(
            LoanStatus__c = 'Application Package Received',LoanNumber__c = '12345992', Id=loanStatus3.Id
        );                     
        loanStatus3.LoanStatus__c = 'Application Package Received';   
        update loanStatus4;

        Loan_New__c loanStatus5 = new Loan_New__c(
            LoanStatus__c = 'In Processing',LoanNumber__c = '12345993', Id=loanStatus4.Id
        );                     
        loanStatus4.LoanStatus__c = 'In Processing';   
        update loanStatus5;

        Loan_New__c loanStatus6 = new Loan_New__c(
            LoanStatus__c = 'In final HUD Review',LoanNumber__c = '12345994', Id=loanStatus5.Id
        );                     
        loanStatus5.LoanStatus__c = 'In final HUD Review';   
        update loanStatus6;

        Loan_New__c loanStatus7 = new Loan_New__c(
            LoanStatus__c = 'Docs Out to Settlement Agent',LoanNumber__c = '12345994', Id=loanStatus6.Id
        );                     
        loanStatus6.LoanStatus__c = 'Docs Out to Settlement Agent';   
        update loanStatus7;

        Loan_New__c loanStatus8 = new Loan_New__c(
            LoanStatus__c = 'Closed - Awaiting Funding',LoanNumber__c = '12345994', Id=loanStatus7.Id
        );                     
        loanStatus7.LoanStatus__c = 'Closed - Awaiting Funding';   
        update loanStatus8;

        Loan_New__c loanStatus9 = new Loan_New__c(
            LoanStatus__c = 'Funded',LoanNumber__c = '12345994', Id=loanStatus8.Id
        );                     
        loanStatus8.LoanStatus__c = 'Funded';   
        update loanStatus9;

        Loan_New__c loanStatus10 = new Loan_New__c(
            LoanStatus__c = 'Funded',LoanNumber__c = '12345994', Id=loanStatus9.Id
        );                     
        loanStatus9.LoanStatus__c = 'Funded';   
        update loanStatus10;

        Loan_New__c loanStatus11 = new Loan_New__c(
            LoanStatus__c = 'Loan Rescinded',LoanNumber__c = '12345994', Id=loanStatus10.Id
        );                     
        loanStatus10.LoanStatus__c = 'Loan Rescinded';   
        update loanStatus11;

        Loan_New__c loanStatus12 = new Loan_New__c(
            LoanStatus__c = 'Application Approved but Not Accepted',LoanNumber__c = '12345994', Id=loanStatus11.Id
        );                     
        loanStatus11.LoanStatus__c = 'Application Approved but Not Accepted';   
        update loanStatus12;

        Loan_New__c loanStatus13 = new Loan_New__c(
            LoanStatus__c = 'File Closed for Incompleteness',LoanNumber__c = '12345994', Id=loanStatus12.Id
        );                     
        loanStatus12.LoanStatus__c = 'File Closed for Incompleteness';   
        update loanStatus13;

        Loan_New__c loanStatus14 = new Loan_New__c(
            LoanStatus__c = 'Suspended',LoanNumber__c = '12345994', Id=loanStatus13.Id
        );                     
        loanStatus13.LoanStatus__c = 'Suspended';   
        update loanStatus14;

        Loan_New__c loanStatus15 = new Loan_New__c(
            LoanStatus__c = 'Withdrawn',LoanNumber__c = '123459946',  Withdrawn_Reason__c = 'Client not Interested', 
            How_was_the_Withdrawn_status_captured__c = 'ORMS Partner', Who_Requested_the_Withdraw__c = 'test'
        );                     
        loanStatus1.LoanStatus__c = 'Withdrawn';   
        loanStatus1.Withdrawn_Reason__c = 'Client not Interested';  
        loanStatus1.How_was_the_Withdrawn_status_captured__c = 'ORMS Partner';
        loanStatus1.Who_Requested_the_Withdraw__c = 'test';
        insert loanStatus15;

        Loan_New__c loanStatus16 = new Loan_New__c(
            LoanStatus__c = 'Proposal',LoanNumber__c = '1234599456', Id=loanStatus15.Id
        );                     
        loanStatus15.LoanStatus__c = 'Proposal';   
        update loanStatus16;

        Test.startTest();
            LoanStatusDate.updateDates(loanStatus1, loanStatus2);
            LoanStatusDate.updateDates(loanStatus1, loanStatus3);
            LoanStatusDate.updateDates(loanStatus1, loanStatus4);
            LoanStatusDate.updateDates(loanStatus1, loanStatus5);
            LoanStatusDate.updateDates(loanStatus1, loanStatus6);
            LoanStatusDate.updateDates(loanStatus1, loanStatus7);
            LoanStatusDate.updateDates(loanStatus1, loanStatus8);
            LoanStatusDate.updateDates(loanStatus1, loanStatus9);
            LoanStatusDate.updateDates(loanStatus1, loanStatus10);
            LoanStatusDate.updateDates(loanStatus1, loanStatus11);
            LoanStatusDate.updateDates(loanStatus1, loanStatus12);
            LoanStatusDate.updateDates(loanStatus1, loanStatus13);
            LoanStatusDate.updateDates(loanStatus1, loanStatus14);
            LoanStatusDate.updateDates(loanStatus1, loanStatus15);
            LoanStatusDate.updateDates(loanStatus15, loanStatus16);
        Test.stopTest();
    }
}