src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanCompleteFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoanCompleteFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <description>Format: Last Name, First Name</description>
        <inlineHelpText>Format: Last Name, First Name</inlineHelpText>
        <label>Client Name*</label>
        <length>60</length>
        <type>Text</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoanController.cls
/** * File Name   : LoanController.cls
*     Description : 
*     Created     : 7/28/2017
*     Modified    : Prsn
*   * @author     : 
* */
public class LoanController {
    @AuraEnabled
    public static List<Loan_New__c> getName() {
        List<Loan_New__c> ListLoan = new List<Loan_New__c>();
        try{
            String User = UserInfo.getUserId();
            
            ListLoan =  [SELECT Name, LastModifiedDate, Client_Name__c FROM Loan_New__c where IsActiveFlag__c = true and LoanCompleteFlag__c= false
                         /*and OwnerId = :User and /-- prasen*/ order by lastmodifieddate desc];   
        }
        catch(exception e)
        {
            system.debug('getName--Exception---'+e);
        }
        return ListLoan;
    }
    
    @AuraEnabled
    public static  Integer getCount() {
        Integer GetIntCount;
        try{
            String User = UserInfo.getUserId();        
            GetIntCount =  [SELECT count() from Loan_New__c where LoanCompleteFlag__c= false and ISActiveFlag__c = true /*and OwnerId = :User*/];
        }
        catch(exception e)
        {
            system.debug('getCount--Exception---'+e);
        }
        return GetIntCount;
    }
    
    @AuraEnabled
    public static void deleteData(String id) {
        try{
            Loan_New__c L = [Select Id,Name from Loan_New__c where Id = :id];
            String Loan_Id = L.Id;
            
            if (Loan_Id == id)
            {
                L.IsActiveFlag__c = false;
                update L;
            }
            
        }
        catch(exception e)
        {
            system.debug('deleteData--Exception---'+e);
        }
    }
    
}