src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PCS_at_Loan_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PCS at loan level can be different from PCS at Partner level</inlineHelpText>
        <label>PCS at Loan Level</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Account Executive/PCS</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Partner Care Specialist Lead</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/DonutChartController.cls
/**
*    File Name: DonutChartController.apxc
*    Description: Controller to Display count of LoanStatus on PieChart for loggedin users
*    Author: Bala Sahitya 
*    Modified By: 
***/

public class DonutChartController {
    public List<PieWedgeData> getPieData() {
        Id userId = UserInfo.getUserId();
        User loggedInUser = [Select Id, Email, ProfileId From User Where Id = :userId];
        Integer ConApp = 0, InProcess = 0, Apprec = 0, Uwcc = 0, susp=0, awaiting= 0, closedawaiting = 0;  
                      
        ConApp = [Select Count() from Loan_New__c where LoanStatus__c = 'Conditionally Approved' AND PCS_at_Loan_Level__r.Id =: userId];
        InProcess = [Select Count() from Loan_New__c where Loanstatus__c = 'In Processing' AND PCS_at_Loan_Level__r.Id =: userId];     
        Apprec = [Select Count() from Loan_New__c where Loanstatus__c = 'Application Package Received' AND PCS_at_Loan_Level__r.Id =: userId];     
        Uwcc = [Select Count() from Loan_New__c where Loanstatus__c = 'Underwriting Clear to Close' AND PCS_at_Loan_Level__r.Id =: userId];     
        susp = [Select Count() from Loan_New__c where Loanstatus__c = 'Suspended' AND PCS_at_Loan_Level__r.Id =: userId];     
        awaiting = [Select Count() from Loan_New__c where Loanstatus__c = 'Awaiting Closing' AND PCS_at_Loan_Level__r.Id =: userId];     
        closedawaiting = [Select Count() from Loan_New__c where Loanstatus__c = 'Closed - Awaiting Funding' AND PCS_at_Loan_Level__r.Id =: userId];      
        
        List<PieWedgeData> data = new List<PieWedgeData>();        
            data.add(new PieWedgeData('Conditionally Approved', ConApp));
            data.add(new PieWedgeData('In Processing', InProcess));
            data.add(new PieWedgeData('App Package Received', Apprec ));
            data.add(new PieWedgeData('UW Clear to Close', Uwcc ));
            data.add(new PieWedgeData('Suspended', susp ));
            data.add(new PieWedgeData('Awaiting Closing', awaiting ));        
            data.add(new PieWedgeData('Closed - Awaiting Funding', awaiting ));                    
        return data;        
    }
    // Wrapper class
    public class PieWedgeData {

        public String loanStatus{ get; set; }
        public Integer loanCount { get; set; }        
        public PieWedgeData(String loanStatus, Integer loanCount) {            
            this.loanStatus = loanStatus + ' [' + loancount + ']';
            this.loanCount = loanCount;            
        }
    }
}