src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>LoanStatus</relationshipLabel>
        <relationshipName>LoanStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousStatus__c</fullName>
        <label>Previous Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status - Used By Executive Reporting</description>
        <inlineHelpText>Status - Used By Executive Reporting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Full Package Received</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/LoanStatusHandler.cls
/**
 * @description LoanStatusHandler
 * @author Mike Gill
 * @date 28th June 2018
 * @changelog 
 * 07/18/18 MG/QDA Add new Status Picklist field to aid Executive Reporting filtering SFDC-103
 * 07/27/18 MG/QDA BUG FIX - Add getLoanStatusMap method to map Loan Status values back to Label SFDC-222
 *
 */
public without sharing class LoanStatusHandler {


    public static void trackLoanStatus(Map<Id, Loan_New__c> newMap, Map<Id, Loan_New__c> oldMap ){
        Logger.push('TrackLoanStatus','LoanStatusHandler');

            List<LoanStatus__c> loanStatusRecords = new List<LoanStatus__c>();

			Map<String, String> valueLabelMap = getLoanStatusMap(); // Get Loan Status Map

            for (Loan_New__c l : newMap.values()){
                
                

                // Compare old/new to detect if loan status is changing
                if (l.LoanStatus__c != oldMap.get(l.Id).LoanStatus__c){
            
                    //Logger.debug('Loan Status has changed, tracking changes...');
                    LoanStatus__c loanStatusRecord = new LoanStatus__c();
                    loanStatusRecord.Name = valueLabelMap.get(l.LoanStatus__c); // Lookup Label from Map
                    loanStatusRecord.Status__c = valueLabelMap.get(l.LoanStatus__c); // Lookup Label from Map
                    loanStatusRecord.LoanId__c = l.Id;
                    loanStatusRecord.PreviousStatus__c=valueLabelMap.get(oldMap.get(l.Id).LoanStatus__c); // Lookup Label from Map
                    loanStatusRecords.add(loanStatusRecord);

                }

            }

            try{
                insert loanStatusRecords; // insert 
            } catch (Exception ex){
                Logger.debugException(ex);
            }

        Logger.pop();
    }

	/**
	 * @description Get Map of Loan Status API to Label
	 * @return Map of API to Label
	 */
    private static Map<String, String> getLoanStatusMap(){
		Logger.push('getLoanStatusMap','LoanStatusHandler');
		Schema.DescribeFieldResult fieldResult = Loan_New__c.LoanStatus__c.getDescribe();
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        Map<String, String> valueLabelMap = new Map<String,String>();
        for( Schema.PicklistEntry v : values) {
            valueLabelMap.put(v.getValue(), v.getLabel());
        }

		Logger.pop();
		return valueLabelMap;

    }


}