src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Application_Approved_Not_Accepted_Date__c</fullName>
        <label>Application Approved Not Accepted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>File_Closed_for_Incompleteness_Date__c</fullName>
        <label>File Closed for Incompleteness Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Docs_Out_to_Settlement_Agent_Date__c</fullName>
        <label>Docs Out to Settlement Agent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>App_Requested_Date__c</fullName>
        <description>Partner has requested application</description>
        <label>App Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Clear_to_Close_Date__c</fullName>
        <label>Clear to Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Closed_Awaiting_Funding_Date0__c</fullName>
        <label>Closed - Awaiting Funding Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Conditionally_Approved_Date0__c</fullName>
        <label>Conditionally Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Denied_Date0__c</fullName>
        <label>Denied Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_Processing_Date0__c</fullName>
        <label>In Processing Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_Underwriting_Review_Date__c</fullName>
        <description>All Vendor Items ordered and UW begins review</description>
        <label>In Underwriting Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Funded_Date__c</fullName>
        <label>Loan Funded Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Received_Awaiting_Review__c</fullName>
        <description>APCS reviews to move to In Processing</description>
        <label>Loan Received - Awaiting Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Rescinded_Date__c</fullName>
        <description>Loan was Rescinded</description>
        <label>Loan Rescinded Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Status_Change_Date__c</fullName>
        <label>Loan Status Change Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Submitted_Incomplete__c</fullName>
        <description>AE or Processor identifies that at least one of minimum required docs are missing</description>
        <label>Loan Submitted - Incomplete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submitted_to_Lender_Date__c</fullName>
        <description>Partner submitted signed app and supporting documents</description>
        <label>Submitted to Lender Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Suspended_Date0__c</fullName>
        <label>Suspended Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Waiting_for_Full_Package_Date0__c</fullName>
        <label>Waiting for Full Package Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Withdrawn_Date0__c</fullName>
        <label>Withdrawn Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_final_HUD_Review_Date__c</fullName>
        <label>In Final HUD Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/LoanStatusDate.cls
/**
* @description: LoanStatusDate class captures all the status dates when loan status
*               is updated
* @author Sahitya
* @date 6/28/2019
*
*/
public class LoanStatusDate{

    public static void loanDate(Map<Id, Loan_New__c> oldLoanMap, List<Loan_New__c> newLoans){
        Logger.push('loanDate','LoanStatusDate');        
        for(Loan_New__c newLoan : newLoans)
        {
            Loan_New__c oldLoan = oldLoanMap.get(newLoan.Id);
            updateDates(newLoan, oldLoan);            
        }                    
        Logger.pop();
    }

    public static void updateDates(Loan_New__c newLoan, Loan_New__c oldLoan){
        Logger.push('loanDate','LoanStatusDate');
        String newloanStatus = newLoan.loanstatus__c;

        if(newloanStatus == 'Proposal'){
           newLoan.Loan_Status_Change_Date__c = DateTime.now();
           newLoan.App_Requested_Date__c = DateTime.now();                
        }
        if(newloanStatus == 'Waiting for Full Package'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Waiting_for_Full_Package_Date0__c = DateTime.now();
        }
        if(newloanStatus == 'Application Package Received'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Submitted_to_Lender_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'Loan Submission Received- Awaiting Review'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Loan_Received_Awaiting_Review__c = DateTime.now();
        }
        if(newloanStatus == 'Full Application Received - Incomplete'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Loan_Submitted_Incomplete__c  = DateTime.now();
        }
        if(newloanStatus == 'In Processing'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.In_Processing_Date0__c  = DateTime.now();
        }
        //Logic in PB
       /* if(newloanStatus == 'In Underwriting Review'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.In_Underwriting_Review_Date__c  = DateTime.now();
        }*/
        if(newloanStatus == 'Conditionally Approved'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Conditionally_Approved_Date0__c  = DateTime.now();
        }
        if(newloanStatus == 'Underwriting Clear to Close'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Clear_to_Close_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'In final HUD Review'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.In_final_HUD_Review_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'Docs Out to Settlement Agent'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Docs_Out_to_Settlement_Agent_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'Closed - Awaiting Funding'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Closed_Awaiting_Funding_Date0__c  = DateTime.now();
        }
        if(newloanStatus == 'Funded'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Loan_Funded_Date__c  = DateTime.now();
        }        
        if(newloanStatus == 'Loan Rescinded'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Loan_Rescinded_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'Application Approved but Not Accepted'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Application_Approved_Not_Accepted_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'File Closed for Incompleteness'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.File_Closed_for_Incompleteness_Date__c  = DateTime.now();
        }
        if(newloanStatus == 'Suspended'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Suspended_Date0__c  = DateTime.now();
        }
        if(newloanStatus == 'Withdrawn'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Withdrawn_Date0__c  = DateTime.now();
        }
        if(newloanStatus == 'Denied'){
            newLoan.Loan_Status_Change_Date__c = DateTime.now();
            newLoan.Denied_Date0__c  = DateTime.now();
        }
        Logger.pop();
    }
}