src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Extend_Application_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Extend Application Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActiveFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Modified_Date__c</fullName>
        <label>Previous Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
    <fields>
        <fullName>LoanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipLabel>LoanStatus</relationshipLabel>
        <relationshipName>LoanStatus</relationshipName>
        <type>Lookup</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Confirm_to_Show_Notes_in_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>You are posting this note to the portal. Are you sure you would like to continue?</description>
        <inlineHelpText>Please check this checkbox to confirm that you are posting this note to the portal</inlineHelpText>
        <label>Confirm to Post Note to Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Id</label>
        <referenceTo>Loan_New__c</referenceTo>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeactivatePipelineLoan.cls
/**
* @description DeactivatePipelineLoan Batch Job
* @author Ravi (GalaxE)
* @date 2/24/2018
* @changlog 
* Bala 6/26/2018 - Change Loanstatus from "Waiting for Full package" to "withdrawn" 
                    if the Loan is in "Waiting for Full package" status for 31 days. Portal Notes, Emails and Tasks will be created. 
* QDA/MG 02/07/2018 - Refactor/review by Mike due to Async conflicts
* Bala 5/3/2019 - Added previous modified date instead of last modified, due to daily uploads from RV. added PB to update Previous Modified Date
*/

global class DeactivatePipelineLoan implements Database.Batchable<sObject>{
    
    public static string STR_GENTAL_REMINDER = 'This loan will be withdrawn in 10 days because the application has not yet been returned.';
    public static string STR_FINAL_REMINDER = 'This loan will be withdrawn in 1 day. If you would like to reactivate this loan after tomorrow, please contact your Account Executive.';

    global Database.QueryLocator start(Database.batchableContext BC) {

        Logger.push('start','DeactivatePipelineLoan'); 
        String query = 'SELECT Id, LoanStatus__c, IsActiveFlag__c, LastModifiedDate, Previous_Modified_Date__c,'
        + '(select id, Name, createdDate from loanstatus__r where name = \'Waiting for Full Package\' order by createdDate desc  limit 1)' 
        + 'FROM Loan_New__c where IsActiveFlag__c = true and Extend_Application_Time__c != true ' 
        + ' and LoanStatus__c = \'Waiting for Full Package\' order by LastModifiedDate ';
        Logger.pop();
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Loan_New__c> scope){
       Logger.push('execute','DeactivatePipelineLoan'); 
       
       List<Loan_New__c> loanUpdates =new List<Loan_New__c>();
       List<Note__c> noteInserts=new List<Note__c>();

       for ( Loan_New__c l : scope){
            
            dateTime systemDate = System.now();
            date todayDate = date.newinstance(systemDate.year(), systemDate.month(), systemDate.day()); 
            datetime lDate;
            
            if(l.Previous_Modified_Date__c != null){
                LDate = l.Previous_Modified_Date__c;
            }
            else{
               LDate = todayDate;
            }

            Date mDate = date.newinstance(lDate.year(), lDate.month(), lDate.day());
            Integer numberDaysDue = mDate.daysBetween(todayDate);
                    
            if(numberDaysDue==20){
                Note__c note = createNote(l.Id, 'Gentle Reminder', STR_GENTAL_REMINDER);
                noteInserts.add(note);
            }
            else if(numberDaysDue==30){
                Note__c note = createNote(l.Id, 'Final Reminder', STR_FINAL_REMINDER);
                noteInserts.add(note);
        
            }
            else if(numberDaysDue==31){
                Loan_New__c loan = new Loan_New__c( Id = l.Id, IsActiveFlag__c = false, LoanStatus__c = 'File Closed for Incompleteness');
                loanUpdates.add(loan);                    
            }  
        }
    
        // Update Loan records    
        try { if (loanUpdates.size()>0){ update loanUpdates; } } 
        catch (Exception ex){ Logger.debugException(ex); }    

        // Insert Notes records
        try { if (noteInserts.size()>0){ insert noteInserts; } } 
        catch (Exception ex){ Logger.debugException(ex); }
        
        Logger.pop();
    } 

    global void finish(Database.BatchableContext BC){
        Logger.push('finish','DeactivatePipelineLoan');
        Logger.pop();
    }

    /**
    * @description Return an instance of a note object for insertion
    * @param loanId - Salesforce record Id
    * @parma strTitle - Note title
    * @param strNote - Note body
    * @returns Note__c sObject instance
    */
    public static Note__c createNote(Id loanId, String strTitle, String strNote ){
        
        Note__c n = new Note__c();
        n.Body__c = strNote;
        n.Loan_Id__c = loanId;
        n.Name = strTitle;
        n.Confirm_to_Show_Notes_in_Portal__c = true;
        return n;
    }
    
}