src/objects/Loan_New__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Status_Number__c</fullName>
        <formula>CASE(  LoanStatus__c  , 
"Incomplete", 1, 
"Proposal", 10, 
"Waiting for Full Package", 10, 
"Application Package Received", 16, 
"Loan Submission Received- Awaiting Review", 20, 
"Full Application Received - Incomplete", 19, 
"In Processing", 21, 
"In Underwriting Review", 30, 
"Conditionally Approved", 35, 
"Underwriting Clear to Close", 40, 
"In final HUD Review", 38, 
"Docs Out to Settlement Agent", 57, 
"Closed - Awaiting Funding", 0, 
"Funded", 65, 
"Loan Rescinded", 111, 
"Application Approved but Not Accepted", 150, 
"File Closed for Incompleteness", 140, 
"Suspended", 33, 
"Withdrawn", 110, 
"Denied", 100, 
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Status Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LoanStatus__c</fullName>
        <label>LoanStatus*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Application Incomplete</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                    <label>Application Requested</label>
                </value>
                <value>
                    <fullName>Waiting for Full Package</fullName>
                </value>
                <value>
                    <fullName>Application Package Received</fullName>
                    <label>Submitted to Lender</label>
                </value>
                <value>
                    <fullName>Loan Submission Received- Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Full Application Received - Incomplete</fullName>
                    <label>Loan Submitted - Incomplete</label>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>In Underwriting Review</fullName>
                    <color>#33FF33</color>
                    <label>In Underwriting Review</label>
                </value>
                <value>
                    <fullName>Conditionally Approved</fullName>
                    <color>#33CC00</color>
                    <label>Conditionally Approved</label>
                </value>
                <value>
                    <fullName>Underwriting Clear to Close</fullName>
                    <label>Clear to Close</label>
                </value>
                <value>
                    <fullName>In final HUD Review</fullName>
                    <label>In Final HUD Review</label>
                </value>
                <value>
                    <fullName>Docs Out to Settlement Agent</fullName>
                </value>
                <value>
                    <fullName>Closed - Awaiting Funding</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <label>Loan Funded</label>
                </value>
                <value>
                    <fullName>Loan Rescinded</fullName>
                </value>
                <value>
                    <fullName>Application Approved but Not Accepted</fullName>
                </value>
                <value>
                    <fullName>File Closed for Incompleteness</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <color>#CC0000</color>
                    <label>Suspended</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Awaiting Closing</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Closing</label>
                </value>
                <value>
                    <fullName>Cancelled/Denied</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled/Denied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <label>Loan</label>
  <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
  <pluralLabel>Loans</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoanStatus__c.object
<CustomObject>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>LoanStatus</label><nameField>
        <label>Current Status</label>
        <type>Text</type>
    </nameField><pluralLabel>LoanStatus</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/objects/TriggerLoan__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable</description>
        <inlineHelpText>Enable</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerLoan.cls</description><label>TriggerLoan</label><pluralLabel>TriggerLoan</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerLoan.cls
/**
* @description TriggerHandlerLoan is the overall trigger handler for Loan.trigger
* Implements and extends interface defined in TriggerHandler.class.
* See specific method descriptions for functionality.
* Custom Metadata Type records (TriggerLoan__mdt) control method functionality.
*
* @author Mike Gill
* @date 6/19/2018
*
* changelog:
*
*/
public without sharing class TriggerHandlerLoan extends TriggerHandler {
    /**
    * @description custom metadata types enable/disable methods
    */
    @testVisible
    private static Map<String, TriggerLoan__mdt> testControlMap {
        get {
            if (testControlMap == NULL) {
                testControlMap = new Map<String, TriggerLoan__mdt>();
                for (TriggerLoan__mdt tesControl : [SELECT MasterLabel, Enable__c FROM TriggerLoan__mdt]) {
                    testControlMap.put(tesControl.MasterLabel, tesControl);
                }
            }
            return testControlMap;
        }
        set;
    }

    /**
     * @description After Update dispatcher method - used to sequence call domain/service class handler
     */
    public override void afterInsert() {
        Logger.push('afterInsert', 'TriggerHandlerLoan');
        system.debug('----------TriggerHandlerLoan afterInsert--------------');
        // Run Loan Update Partner Fields

        if (testControlMap.get('updatePartnerFields') != NULL) {
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('updatePartnerFields').Enable__c) {
                String jsonNewMap = JSON.serialize((Map<Id, sObject>) Trigger.newMap);
                Logger.debug('afterInsert is firing');
                LoanUpdatePartnerFieldsHandler.updatePartnerFields(jsonNewMap, null);

                Logger.debug('QA Called LoanUpdatePartnerFieldsHandler Future from afterInsert');
            }
        }
        Logger.pop();
    }

    public override void afterUndelete() {
        // Do nothing - Recommend this as no loans should be deleted and therefore this would not be fired
    }

    /**
     * @description After Update dispatcher method - used to sequence call domain/service class handler
     */
    public override void afterUpdate() {
        Logger.push('afterUpdate', 'TriggerHandlerLoan');
        system.debug('----------TriggerHandlerLoan afterUpdate--------------');

        List<Loan_New__c> loanList;
        Set<Id> changeStatusIdSet;
        system.debug('RecursiveTriggerHandler.isFirstTimeCopy-------'+RecursiveTriggerHandler.isFirstTimeCopy);
        if (RecursiveTriggerHandler.isFirstTimeCopy) {
            loanList = new List<Loan_New__c>();
            changeStatusIdSet = new Set<Id>();
            Set<String> statusSet =  new Set<String>{'Waiting for Full Package', 'Application Package Received', 'Loan Submission Received- Awaiting Review', 'Docs Out to Settlement Agent'};
            Map<Id, Loan_New__c> newMap = new Map<Id, Loan_New__c>();
            newMap = (Map<Id, Loan_New__c>)Trigger.newMap;
            Map<Id, Loan_New__c> oldMap = new Map<Id, Loan_New__c>();
            oldMap = (Map<Id, Loan_New__c>)Trigger.oldMap;
            
            Loan_New__c ln = (Loan_New__c)Trigger.new[0];
            Loan_New__c lo = (Loan_New__c)Trigger.old[0];
            Loan_New__c ln1 = (Loan_New__c)Trigger.newMap.values()[0];
            Loan_New__c lo2 = (Loan_New__c)Trigger.oldMap.values()[0];
            system.debug('in loanHandler new------'+ln.LoanStatus__c);
            system.debug('in loanHandler old------'+lo.LoanStatus__c);
            system.debug('in loanHandler new------'+ln1.LoanStatus__c);
            system.debug('in loanHandler old------'+lo2.LoanStatus__c);
            
            
            for(Loan_New__c newLoan :(List<Loan_New__c>)Trigger.new){
                Loan_New__c oldLoan = oldMap.get(newLoan.Id);
                system.debug('newLoan.LoanStatus__c------'+newLoan.LoanStatus__c);
                system.debug('oldLoan.LoanStatus__c------'+oldLoan.LoanStatus__c);
                
                if(newLoan.LoanStatus__c != oldLoan.LoanStatus__c && statusSet.contains(newLoan.LoanStatus__c)){
                system.debug('in------');
                   // changeStatusIdSet.add(newLoan.id);
                    OnBaseLookups.sendKeywords((List<Loan_New__c>)Trigger.new);
                }
            }
            //system.debug('changeStatusIdSet-111-----'+changeStatusIdSet);
            RecursiveTriggerHandler.isFirstTimeCopy = false;
        }


        // Run Loan Status Tracking Hanlder
        if (testControlMap.get('trackLoanStatus') != NULL) {
			system.debug('trackLoanStatus1-----------------');
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('trackLoanStatus').Enable__c) {

                LoanStatusHandler.trackLoanStatus((Map<Id, Loan_New__c>) Trigger.newMap, (Map<Id, Loan_New__c>) Trigger.oldMap);

                Logger.debug('QA Called LoanStatusHandler Future');
            }
        }

        // Run Loan Update Partner Fields
        if (testControlMap.get('updatePartnerFields') != NULL) {

            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('updatePartnerFields').Enable__c) {
				system.debug('updatePartnerFields2-----------------');
                String jsonNewMap = JSON.serialize((Map<Id, sObject>) Trigger.newMap);
                String jsonOldMap = JSON.serialize((Map<Id, sObject>) Trigger.oldMap);

                if (!System.isBatch()){ 
                     LoanUpdatePartnerFieldsHandler.updatePartnerFields(jsonNewMap, jsonOldMap); // Call future context safely    
                     Logger.debug('QA Called LoanUpdatePartnerFieldsHandler Future'); 
                } 
            }
        }

        // Run Loan Update Partner Fields
        if (testControlMap.get('updateLoanSharing') != NULL) {
			system.debug('updateLoanSharing3-----------------');
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('updateLoanSharing').Enable__c) {

                String jsonNewMap = JSON.serialize((Map<Id, sObject>) Trigger.newMap);
                String jsonOldMap = JSON.serialize((Map<Id, sObject>) Trigger.oldMap);

                if (!System.isBatch()){
                    LoanSharingHandler.updateLoanSharing(jsonNewMap, jsonOldMap);
                    Logger.debug('QA Called LoanStatusHandler Future');
                }
            }
        }
        
     
        // Run Loan Update Partner Fields
      /*  if (testControlMap.get('onbaseSendKeywords') != NULL) {
            system.debug('sendKeywords4-----------------');
            //try{
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('onbaseSendKeywords').Enable__c) {

                String jsonNewMap = JSON.serialize((Map<Id, sObject>) Trigger.newMap);
                String jsonOldMap = JSON.serialize((Map<Id, sObject>) Trigger.oldMap);
                System.debug('@@jsonnewmap---'+jsonNewMap);
                System.debug('@@jsonoldmap---'+jsonOldMap);

                string newLoanKey = jsonNewMap.substring(jsonNewMap.indexof('Loan_Status_Number__c":')+23,jsonNewMap.indexof('ORMS_AE')-2);
                system.debug('test---->'+newLoanKey);

                string oldLoanKey = jsonOldMap.substring(jsonOldMap.indexof('Loan_Status_Number__c":')+23,jsonOldMap.indexof('ORMS_AE')-2);
                system.debug('test2---->'+oldLoanKey);
                Loan_New__c ln = (Loan_New__c)Trigger.new[0];
                String loanValue = ln.loanstatus__c;

                if(newLoanKey != oldLoanKey && (loanValue != 'Proposal')){  
                    system.debug('--in here--');              
                    OnBaseLookups.sendKeywords((List<Loan_New__c>)Trigger.new);
                } 
            }
            //}catch(exception ex){ System.debug('@@after update error'+ex);}
        }*/
       
        RecursiveTriggerHandler.isFirstTime = false;
        Logger.pop();
    }
    
    public override void beforeUpdate() {
        Logger.push('beforeUpdate', 'TriggerHandlerLoan');
        System.debug('---------TriggerHandlerLoan-beforeUpdate-----------');

        // Validate required OnBase values for final send    
        if (testControlMap.get('onbaseValidateFinal') != NULL) {
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('onbaseValidateFinal').Enable__c) {
                OnBaseLookups.validateFinalSend((List<Loan_New__c>)Trigger.new);
            }
        }
        
        // Update OnBase values
        if (testControlMap.get('onbaseTriggerFields') != NULL) {
            if (RecursiveTriggerHandler.isFirstTime && testControlMap.get('onbaseTriggerFields').Enable__c) {
                OnBaseLookups.updateFields((Map<Id, Loan_New__c>)Trigger.oldMap, (List<Loan_New__c>)Trigger.new);
            }
        }
        
        Logger.pop();
    }
}