src/objects/RunScenario__c.object
<CustomObject>
    <fields>
        <fullName>Scenarios_Run__c</fullName>
        <label>Scenarios Run</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
<compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>RunScenario</label><nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>RunScenario Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>RunScenarios</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility>
</CustomObject>

src/classes/RunScenario_countTest.cls
@isTest
public with sharing class RunScenario_countTest {
    
    @isTest static void RunScenario_countTest1(){
    
    
      Profile p = [SELECT Id FROM Profile WHERE Name='Account Executive/PCS'];
        UserRole UR=[Select Id from UserRole where Name='Partner Care Specialist'];        
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User user1 = new User(Alias = uniqueName.substring(18, 23),  email = uniqueName + '@test1' + orgId + '.org',
                              Username = uniqueName + '@test1' + orgId + '.org', 
                              EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id,userroleid=UR.ID, 
                              TimeZoneSidKey='America/Los_Angeles');
        insert user1;            
        system.runAs(user1)
        {
    RunScenario__c  RS = new RunScenario__c  ();
    RS.Scenarios_Run__c  = 10;
    
    insert RS;
    }
    }

}