src/objects/TriggerLoan__mdt.object
<CustomObject><fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable</description>
        <inlineHelpText>Enable</inlineHelpText>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields><description>Controls (enables/disables) individual methods within TriggerHandlerLoan.cls</description><label>TriggerLoan</label><pluralLabel>TriggerLoan</pluralLabel><visibility>Public</visibility></CustomObject>

src/classes/TriggerHandlerLoanTest.cls
/**
 * @description Apex Test TriggerHandlerLoanTest
 * @date 29th June 2018
 * @author Mike Gill
 */

@isTest
private class TriggerHandlerLoanTest {



    /***************************************************************************************************
	*						 Initialize Test Data
	*************************************************************************************************/

    private static Map<String, TriggerLoan__mdt> testTESmdtMap {
        get {
            return new Map<String, TriggerLoan__mdt>{
                    'trackLoanStatus' => ( TriggerLoan__mdt ) JSON.deserialize(
                            '{ "MasterLabel" : "trackLoanStatus", "Enable__c" : true }', TriggerLoan__mdt.class )
            };
        }
        private set;
    }




}